// File: internal/httpapi/httpapi.go
// Purpose: Serve the authenticated, client-restricted, read-only HTTP monitoring API.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package httpapi

import (
	"crypto/sha256"
	"crypto/subtle"
	"encoding/json"
	"log/slog"
	"net"
	"net/http"
	"net/netip"
	"strings"
	"time"

	"github.com/tseiman/HomeAuthMonitorGW/internal/cache"
)

// Options controls static API metadata.
type Options struct {
	Version string
	Logger  *slog.Logger
}

// View is one coherent cache and authorization-policy generation.
type View struct {
	Store               *cache.Store
	TokenDigests        [][sha256.Size]byte
	AllowedClients      []netip.Prefix
	CertificateNotAfter time.Time
}

// ViewProvider returns the current coherent runtime generation for one request.
type ViewProvider func() View

// API routes authorized read-only requests to cached monitoring data.
type API struct {
	view    ViewProvider
	options Options
}

// New returns a cache-only HTTP handler that obtains one current runtime generation per request.
func New(view ViewProvider, options Options) http.Handler {
	api := &API{view: view, options: options}
	handler := http.Handler(http.HandlerFunc(api.serve))
	if options.Logger != nil {
		handler = accessLogger(options.Logger, handler)
	}
	return handler
}

type responseStatus struct {
	http.ResponseWriter
	status int
}

// WriteHeader records the first response status before forwarding it.
func (w *responseStatus) WriteHeader(status int) {
	if w.status != 0 {
		return
	}
	w.status = status
	w.ResponseWriter.WriteHeader(status)
}

// Write records an implicit success status before forwarding the body.
func (w *responseStatus) Write(body []byte) (int, error) {
	if w.status == 0 {
		w.WriteHeader(http.StatusOK)
	}
	return w.ResponseWriter.Write(body)
}

// Unwrap exposes the underlying writer to standard HTTP response controllers.
func (w *responseStatus) Unwrap() http.ResponseWriter { return w.ResponseWriter }

// accessLogger records request metadata without headers, credentials, query strings, or response bodies.
func accessLogger(logger *slog.Logger, next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		tracked := &responseStatus{ResponseWriter: w}
		next.ServeHTTP(tracked, r)
		status := tracked.status
		if status == 0 {
			status = http.StatusOK
		}
		client := r.RemoteAddr
		if host, _, err := net.SplitHostPort(r.RemoteAddr); err == nil {
			client = host
		}
		logger.Info("http request", "method", r.Method, "path", r.URL.EscapedPath(), "status", status, "client", client, "duration", time.Since(start))
	})
}

// serve loads one generation, enforces its client and bearer policy, and routes one read-only request.
func (a *API) serve(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.Header().Set("Cache-Control", "no-store")

	view := a.view()
	if view.Store == nil || !clientAllowed(r.RemoteAddr, view.AllowedClients) {
		writeError(w, http.StatusForbidden, "forbidden")
		return
	}
	if !validBearer(r.Header.Values("Authorization"), view.TokenDigests) {
		w.Header().Set("WWW-Authenticate", `Bearer realm="automation-gateway"`)
		writeError(w, http.StatusUnauthorized, "unauthorized")
		return
	}
	if r.Method != http.MethodGet {
		w.Header().Set("Allow", http.MethodGet)
		writeError(w, http.StatusMethodNotAllowed, "method not allowed")
		return
	}

	path := strings.TrimSuffix(r.URL.Path, "/")
	switch path {
	case "/api/v1/health":
		a.health(w, view.Store, view.CertificateNotAfter)
		return
	case "/api/v1/sources":
		a.sources(w, view.Store)
		return
	case "/api/v1/metrics":
		a.allMetrics(w, view.Store)
		return
	}
	const prefix = "/api/v1/sources/"
	if strings.HasPrefix(path, prefix) {
		rest := strings.TrimPrefix(path, prefix)
		parts := strings.Split(rest, "/")
		if len(parts) == 1 && parts[0] != "" {
			a.source(w, view.Store, parts[0], false, false)
			return
		}
		if len(parts) == 2 && parts[0] != "" && parts[1] == "metrics" {
			a.source(w, view.Store, parts[0], true, false)
			return
		}
		if len(parts) == 2 && parts[0] != "" && parts[1] == "discovery" {
			a.source(w, view.Store, parts[0], false, true)
			return
		}
	}
	writeError(w, http.StatusNotFound, "not found")
}

// clientAllowed reports whether RemoteAddr's actual TCP peer belongs to one configured prefix.
func clientAllowed(remoteAddress string, allowed []netip.Prefix) bool {
	host, _, err := net.SplitHostPort(remoteAddress)
	if err != nil {
		return false
	}
	address, err := netip.ParseAddr(host)
	if err != nil {
		return false
	}
	address = address.Unmap()
	for _, prefix := range allowed {
		if prefix.Contains(address) {
			return true
		}
	}
	return false
}

// validBearer requires one header with a Bearer scheme, ASCII-space separator, and one matching precomputed digest.
func validBearer(headers []string, expected [][sha256.Size]byte) bool {
	if len(headers) != 1 || len(expected) == 0 {
		return false
	}
	header := headers[0]
	separator := strings.IndexByte(header, ' ')
	if separator <= 0 || !strings.EqualFold(header[:separator], "Bearer") {
		return false
	}
	credentialStart := separator
	for credentialStart < len(header) && header[credentialStart] == ' ' {
		credentialStart++
	}
	if credentialStart == len(header) {
		return false
	}
	candidate := header[credentialStart:]
	for _, r := range candidate {
		if r < 0x21 || r == 0x7f || r == ',' {
			return false
		}
	}
	candidateDigest := sha256.Sum256([]byte(candidate))
	matched := 0
	// Evaluate every configured digest so token position never determines loop length.
	for _, tokenDigest := range expected {
		matched |= subtle.ConstantTimeCompare(candidateDigest[:], tokenDigest[:])
	}
	return matched == 1
}

// health writes gateway status derived from the selected generation's source snapshots.
func (a *API) health(w http.ResponseWriter, store *cache.Store, certificateNotAfter time.Time) {
	status := "ok"
	code := http.StatusOK
	all := store.All()
	if len(all) == 0 {
		status = "failed"
		code = http.StatusServiceUnavailable
	} else {
		for _, snapshot := range all {
			if !snapshot.Available || snapshot.Stale {
				status = "degraded"
				break
			}
		}
	}
	body := map[string]any{"status": status, "version": a.options.Version}
	if !certificateNotAfter.IsZero() {
		body["certificate_not_after"] = certificateNotAfter.UTC()
	}
	writeJSON(w, code, body)
}

// sources writes a compact JSON summary of every source in store.
func (a *API) sources(w http.ResponseWriter, store *cache.Store) {
	type summary struct {
		Name      string `json:"name"`
		Driver    string `json:"driver"`
		Available bool   `json:"available"`
		Stale     bool   `json:"stale"`
	}
	all := store.All()
	out := make([]summary, 0, len(all))
	for _, snapshot := range all {
		out = append(out, summary{snapshot.Name, snapshot.Driver, snapshot.Available, snapshot.Stale})
	}
	writeJSON(w, http.StatusOK, map[string]any{"sources": out})
}

// source writes status, metrics, or discovery JSON from store, or a not-found error when name is unknown.
func (a *API) source(w http.ResponseWriter, store *cache.Store, name string, metricsOnly, discovery bool) {
	snapshot, ok := store.Snapshot(name)
	if !ok {
		writeError(w, http.StatusNotFound, "source not found")
		return
	}
	if discovery {
		writeJSON(w, http.StatusOK, map[string]any{"source": name, "discovery": snapshot.Discovery})
		return
	}
	if metricsOnly {
		writeJSON(w, http.StatusOK, map[string]any{
			"source": name, "available": snapshot.Available, "stale": snapshot.Stale,
			"last_attempt": snapshot.LastAttempt, "last_success": snapshot.LastSuccess,
			"error": snapshot.Error, "metrics": snapshot.Metrics,
		})
		return
	}
	writeJSON(w, http.StatusOK, snapshot)
}

// allMetrics writes an object mapping every source name in store to its current snapshot.
func (a *API) allMetrics(w http.ResponseWriter, store *cache.Store) {
	out := map[string]cache.Snapshot{}
	for _, snapshot := range store.All() {
		out[snapshot.Name] = snapshot
	}
	writeJSON(w, http.StatusOK, out)
}

// writeJSON sends code and JSON-encodes value; encoding errors cannot be returned after headers commit.
func writeJSON(w http.ResponseWriter, code int, value any) {
	w.WriteHeader(code)
	_ = json.NewEncoder(w).Encode(value)
}

// writeError sends message in the standard JSON error envelope.
func writeError(w http.ResponseWriter, code int, message string) {
	writeJSON(w, code, map[string]string{"error": message})
}
