// File: internal/httpapi/httpapi_test.go
// Purpose: Verify API client policy, bearer authentication, routing, and response privacy.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package httpapi

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"net/netip"
	"strings"
	"testing"
	"time"

	"github.com/tseiman/HomeAuthMonitorGW/internal/cache"
	"github.com/tseiman/HomeAuthMonitorGW/internal/metrics"
)

// testHandler returns a populated API handler with two tokens and a documentation-network client allowlist.
func testHandler() http.Handler {
	store := cache.New(time.Now)
	store.Register("controller-main", "snmp", time.Minute)
	store.Success("controller-main", []metrics.Metric{{Name: "uptime", Value: uint64(7), ValueType: "counter", Timestamp: time.Unix(1, 0).UTC()}}, time.Millisecond)
	digests := [][sha256.Size]byte{sha256.Sum256([]byte("first-token-for-tests")), sha256.Sum256([]byte("second-token-for-tests"))}
	view := func() View {
		return View{Store: store, TokenDigests: digests, AllowedClients: []netip.Prefix{netip.MustParsePrefix("192.0.2.0/24"), netip.MustParsePrefix("2001:db8::/64")}, CertificateNotAfter: time.Date(2027, 1, 1, 0, 0, 0, 0, time.UTC)}
	}
	return New(view, Options{Version: "1.0.0-test"})
}

// request creates an allowed-client request with an optional Authorization value.
func request(method, path, authorization string) *http.Request {
	r := httptest.NewRequest(method, path, nil)
	r.RemoteAddr = "192.0.2.25:32100"
	if authorization != "" {
		r.Header.Set("Authorization", authorization)
	}
	return r
}

// TestAccessLoggerRecordsMetadataWithoutSecrets verifies normal request visibility without credential or query leakage.
func TestAccessLoggerRecordsMetadataWithoutSecrets(t *testing.T) {
	var output bytes.Buffer
	logger := slog.New(slog.NewTextHandler(&output, nil))
	handler := accessLogger(logger, http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusNoContent)
	}))
	r := httptest.NewRequest(http.MethodGet, "https://gateway.example/api/v1/health?token=query-secret", nil)
	r.RemoteAddr = "192.0.2.25:32100"
	r.Header.Set("Authorization", "Bearer header-secret")
	handler.ServeHTTP(httptest.NewRecorder(), r)

	text := output.String()
	for _, expected := range []string{"msg=\"http request\"", "method=GET", "path=/api/v1/health", "status=204", "client=192.0.2.25"} {
		if !strings.Contains(text, expected) {
			t.Fatalf("missing %q in access log: %s", expected, text)
		}
	}
	for _, secret := range []string{"query-secret", "header-secret"} {
		if strings.Contains(text, secret) {
			t.Fatalf("access log leaked %q: %s", secret, text)
		}
	}
}

// TestBearerAuthentication verifies both tokens, case-insensitive schemes, exact credentials, and duplicate-header rejection.
func TestBearerAuthentication(t *testing.T) {
	h := testHandler()
	for _, tc := range []struct {
		header string
		want   int
	}{
		{"", 401}, {"Bearer wrong", 401}, {"Basic first-token-for-tests", 401},
		{"bearer first-token-for-tests", 200}, {"Bearer   second-token-for-tests", 200},
		{" Bearer first-token-for-tests", 401}, {"Bearer	first-token-for-tests", 401},
		{"Bearer\u00a0first-token-for-tests", 401}, {"Bearer first-token-for-tests ", 401},
		{"Bearer first-token-for-tests,second-token-for-tests", 401},
	} {
		w := httptest.NewRecorder()
		h.ServeHTTP(w, request(http.MethodGet, "/api/v1/sources", tc.header))
		if w.Code != tc.want {
			t.Fatalf("header=%q code=%d", tc.header, w.Code)
		}
		if w.Header().Get("Cache-Control") != "no-store" {
			t.Fatalf("header=%q cache-control=%q", tc.header, w.Header().Get("Cache-Control"))
		}
		if tc.want == http.StatusUnauthorized && w.Header().Get("WWW-Authenticate") != `Bearer realm="automation-gateway"` {
			t.Fatalf("header=%q challenge=%q", tc.header, w.Header().Get("WWW-Authenticate"))
		}
	}

	r := request(http.MethodGet, "/api/v1/sources", "Bearer first-token-for-tests")
	r.Header.Add("Authorization", "Bearer second-token-for-tests")
	w := httptest.NewRecorder()
	h.ServeHTTP(w, r)
	if w.Code != http.StatusUnauthorized {
		t.Fatalf("duplicate authorization headers accepted: code=%d", w.Code)
	}
}

// TestClientAllowlistUsesRemoteAddr verifies direct IP/CIDR matching and ignores proxy-supplied addresses.
func TestClientAllowlistUsesRemoteAddr(t *testing.T) {
	h := testHandler()
	allowedIPv6 := request(http.MethodGet, "/api/v1/sources", "Bearer first-token-for-tests")
	allowedIPv6.RemoteAddr = "[2001:db8::42]:1234"
	w := httptest.NewRecorder()
	h.ServeHTTP(w, allowedIPv6)
	if w.Code != http.StatusOK {
		t.Fatalf("allowed IPv6 code=%d", w.Code)
	}

	denied := request(http.MethodGet, "/api/v1/sources", "Bearer first-token-for-tests")
	denied.RemoteAddr = "198.51.100.7:1234"
	denied.Header.Set("X-Forwarded-For", "192.0.2.25")
	denied.Header.Set("X-Real-IP", "192.0.2.25")
	w = httptest.NewRecorder()
	h.ServeHTTP(w, denied)
	if w.Code != http.StatusForbidden {
		t.Fatalf("proxy-spoofed client code=%d", w.Code)
	}
}

// TestSourceMetricsJSONAndNoClientSelectedOID verifies metrics ignore client-selected OID parameters.
func TestSourceMetricsJSONAndNoClientSelectedOID(t *testing.T) {
	h := testHandler()
	w := httptest.NewRecorder()
	h.ServeHTTP(w, request(http.MethodGet, "/api/v1/sources/controller-main/metrics?oid=1.2.3", "Bearer first-token-for-tests"))
	if w.Code != http.StatusOK {
		t.Fatalf("code=%d body=%s", w.Code, w.Body.String())
	}
	var body struct {
		Source  string           `json:"source"`
		Stale   bool             `json:"stale"`
		Metrics []metrics.Metric `json:"metrics"`
	}
	if err := json.Unmarshal(w.Body.Bytes(), &body); err != nil {
		t.Fatal(err)
	}
	if body.Source != "controller-main" || body.Stale || len(body.Metrics) != 1 {
		t.Fatalf("body=%+v", body)
	}
}

// TestMethodAndUnknownSource verifies method rejection and missing-source status codes for authorized clients.
func TestMethodAndUnknownSource(t *testing.T) {
	h := testHandler()
	for _, tc := range []struct {
		method, path string
		code         int
	}{{http.MethodPost, "/api/v1/sources", 405}, {http.MethodGet, "/api/v1/sources/missing", 404}} {
		w := httptest.NewRecorder()
		h.ServeHTTP(w, request(tc.method, tc.path, "Bearer first-token-for-tests"))
		if w.Code != tc.code {
			t.Fatalf("%s %s=%d", tc.method, tc.path, w.Code)
		}
	}
}

// TestHealthRequiresBothPolicyChecks verifies health is no longer publicly accessible.
func TestHealthRequiresBothPolicyChecks(t *testing.T) {
	h := testHandler()
	w := httptest.NewRecorder()
	h.ServeHTTP(w, request(http.MethodGet, "/api/v1/health", ""))
	if w.Code != http.StatusUnauthorized {
		t.Fatalf("unauthenticated health code=%d", w.Code)
	}
	w = httptest.NewRecorder()
	h.ServeHTTP(w, request(http.MethodGet, "/api/v1/health", "Bearer second-token-for-tests"))
	if w.Code != http.StatusOK {
		t.Fatalf("authenticated health code=%d", w.Code)
	}
}

// TestRequestLoadsExactlyOneGeneration verifies authorization and routing cannot mix two runtime views.
func TestRequestLoadsExactlyOneGeneration(t *testing.T) {
	store := cache.New(time.Now)
	store.Register("only-current", "nut", time.Minute)
	digest := sha256.Sum256([]byte("current-token-value"))
	calls := 0
	handler := New(func() View {
		calls++
		if calls == 1 {
			return View{Store: store, TokenDigests: [][sha256.Size]byte{digest}, AllowedClients: []netip.Prefix{netip.MustParsePrefix("192.0.2.0/24")}}
		}
		return View{}
	}, Options{})

	response := httptest.NewRecorder()
	handler.ServeHTTP(response, request(http.MethodGet, "/api/v1/sources", "Bearer current-token-value"))
	if response.Code != http.StatusOK || calls != 1 {
		t.Fatalf("status=%d provider calls=%d", response.Code, calls)
	}
}
