// File: zabbix/template_test.go
// Purpose: Validate the import template structure and its single-request dependent-item design.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package zabbix

import (
	"encoding/json"
	"os"
	"os/exec"
	"regexp"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

type templateDocument struct {
	Export struct {
		Version        string `yaml:"version"`
		TemplateGroups []struct {
			Name string `yaml:"name"`
		} `yaml:"template_groups"`
		Templates []struct {
			Items []struct {
				Name      string `yaml:"name"`
				Type      string `yaml:"type"`
				Key       string `yaml:"key"`
				URL       string `yaml:"url"`
				ValueType string `yaml:"value_type"`
				Units     string `yaml:"units"`
				ValueMap  struct {
					Name string `yaml:"name"`
				} `yaml:"valuemap"`
				MasterItem struct {
					Key string `yaml:"key"`
				} `yaml:"master_item"`
				Headers []struct {
					Name  string `yaml:"name"`
					Value string `yaml:"value"`
				} `yaml:"headers"`
				Preprocessing []struct {
					Type       string   `yaml:"type"`
					Parameters []string `yaml:"parameters"`
				} `yaml:"preprocessing"`
				Triggers []struct {
					Name       string `yaml:"name"`
					Expression string `yaml:"expression"`
				} `yaml:"triggers"`
			} `yaml:"items"`
			DiscoveryRules []struct {
				Type       string `yaml:"type"`
				Key        string `yaml:"key"`
				MasterItem struct {
					Key string `yaml:"key"`
				} `yaml:"master_item"`
				ItemPrototypes []struct {
					Name       string `yaml:"name"`
					Key        string `yaml:"key"`
					ValueType  string `yaml:"value_type"`
					Trends     string `yaml:"trends"`
					MasterItem struct {
						Key string `yaml:"key"`
					} `yaml:"master_item"`
					Preprocessing []struct {
						Type       string   `yaml:"type"`
						Parameters []string `yaml:"parameters"`
					} `yaml:"preprocessing"`
				} `yaml:"item_prototypes"`
				TriggerPrototypes []struct {
					Expression string `yaml:"expression"`
				} `yaml:"trigger_prototypes"`
				Preprocessing []struct {
					Type       string   `yaml:"type"`
					Parameters []string `yaml:"parameters"`
				} `yaml:"preprocessing"`
			} `yaml:"discovery_rules"`
			Macros []struct {
				Macro string `yaml:"macro"`
				Type  string `yaml:"type"`
				Value string `yaml:"value"`
			} `yaml:"macros"`
			Dashboards []struct {
				Name  string `yaml:"name"`
				Pages []struct {
					Widgets []struct {
						Type   string `yaml:"type"`
						Name   string `yaml:"name"`
						X      string `yaml:"x"`
						Y      string `yaml:"y"`
						Width  string `yaml:"width"`
						Height string `yaml:"height"`
						Fields []struct {
							Name  string `yaml:"name"`
							Value any    `yaml:"value"`
						} `yaml:"fields"`
					} `yaml:"widgets"`
				} `yaml:"pages"`
			} `yaml:"dashboards"`
			ValueMaps []struct {
				Name     string `yaml:"name"`
				Mappings []struct {
					Value    string `yaml:"value"`
					NewValue string `yaml:"newvalue"`
				} `yaml:"mappings"`
			} `yaml:"valuemaps"`
		} `yaml:"templates"`
	} `yaml:"zabbix_export"`
}

// TestTemplateUsesOneHTTPSMasterAndDependentDiscovery verifies the intended cache-efficient topology.
func TestTemplateUsesOneHTTPSMasterAndDependentDiscovery(t *testing.T) {
	data, err := os.ReadFile("template_homeauthmonitorgw.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var document templateDocument
	if err := yaml.Unmarshal(data, &document); err != nil {
		t.Fatalf("parse template: %v", err)
	}
	if document.Export.Version != "7.4" || len(document.Export.Templates) != 1 {
		t.Fatalf("version=%q templates=%d", document.Export.Version, len(document.Export.Templates))
	}
	if len(document.Export.TemplateGroups) != 1 || document.Export.TemplateGroups[0].Name != "Templates/HomeAuthMonitorGW" {
		t.Fatalf("template groups=%+v", document.Export.TemplateGroups)
	}
	template := document.Export.Templates[0]
	if len(template.Items) != 25 || template.Items[0].Type != "HTTP_AGENT" || template.Items[0].Key != "automation.gateway.snapshot" || !strings.HasSuffix(template.Items[0].URL, "/api/v1/metrics") {
		t.Fatalf("master items=%+v", template.Items)
	}
	for _, item := range template.Items[1:] {
		if item.Type != "DEPENDENT" || item.URL != "" || item.MasterItem.Key != "automation.gateway.snapshot" {
			t.Fatalf("device item is not dependent-only: %+v", item)
		}
	}
	if len(template.Items[0].Headers) != 1 || template.Items[0].Headers[0].Name != "Authorization" || template.Items[0].Headers[0].Value != "Bearer {$AUTOMATION_GATEWAY_TOKEN}" {
		t.Fatalf("headers=%+v", template.Items[0].Headers)
	}
	if len(template.Items[0].Preprocessing) != 1 || template.Items[0].Preprocessing[0].Type != "JAVASCRIPT" || len(template.Items[0].Preprocessing[0].Parameters) != 1 {
		t.Fatalf("master preprocessing=%+v", template.Items[0].Preprocessing)
	}
	if len(template.DiscoveryRules) != 3 {
		t.Fatalf("discovery rules=%d", len(template.DiscoveryRules))
	}
	prototypeCounts := map[string]int{"automation.gateway.sources.discovery": 4, "automation.gateway.metrics.discovery": 2, "automation.gateway.numeric_metrics.discovery": 2}
	triggerCounts := map[string]int{"automation.gateway.sources.discovery": 2, "automation.gateway.metrics.discovery": 0, "automation.gateway.numeric_metrics.discovery": 0}
	foundGenericHealth := false
	for _, rule := range template.DiscoveryRules {
		if rule.Type != "DEPENDENT" || rule.MasterItem.Key != "automation.gateway.snapshot" {
			t.Fatalf("rule=%+v", rule)
		}
		if len(rule.ItemPrototypes) != prototypeCounts[rule.Key] || len(rule.TriggerPrototypes) != triggerCounts[rule.Key] {
			t.Fatalf("rule %q has %d items and %d triggers", rule.Key, len(rule.ItemPrototypes), len(rule.TriggerPrototypes))
		}
		for _, prototype := range rule.ItemPrototypes {
			if prototype.Key == `automation.gateway.source.health["{#SOURCE}"]` {
				foundGenericHealth = true
			}
			if prototype.MasterItem.Key != "automation.gateway.snapshot" {
				t.Fatalf("prototype %q master=%q", prototype.Key, prototype.MasterItem.Key)
			}
			if strings.HasPrefix(prototype.Key, "automation.gateway.metric") && !strings.Contains(prototype.Key, "{#METRIC_KEY}") {
				t.Fatalf("metric prototype uses unsafe identity: %q", prototype.Key)
			}
			if strings.HasPrefix(prototype.Key, "automation.gateway.metric.numeric[") && (prototype.ValueType != "FLOAT" || prototype.Trends == "0") {
				t.Fatalf("numeric metric prototype is not trendable: %+v", prototype)
			}
		}
		if len(rule.Preprocessing) != 1 || rule.Preprocessing[0].Type != "JAVASCRIPT" || len(rule.Preprocessing[0].Parameters) != 1 {
			t.Fatalf("rule %q preprocessing=%+v", rule.Key, rule.Preprocessing)
		}
	}
	if !foundGenericHealth {
		t.Fatal("missing per-source generic health prototype")
	}
	foundSecret := false
	for _, macro := range template.Macros {
		if macro.Macro == "{$AUTOMATION_GATEWAY_TOKEN}" {
			foundSecret = macro.Type == "SECRET_TEXT" && macro.Value == ""
		}
	}
	if !foundSecret {
		t.Fatal("missing valueless SECRET_TEXT token macro")
	}
}

// TestTemplateUUIDsAreUnique verifies every import object has a unique lowercase RFC 4122 UUIDv4 without dashes.
func TestTemplateUUIDsAreUnique(t *testing.T) {
	data, err := os.ReadFile("template_homeauthmonitorgw.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var root yaml.Node
	if err := yaml.Unmarshal(data, &root); err != nil {
		t.Fatal(err)
	}
	pattern := regexp.MustCompile(`^[0-9a-f]{12}4[0-9a-f]{3}[89ab][0-9a-f]{15}$`)
	seen := map[string]bool{}
	var visit func(*yaml.Node)
	visit = func(node *yaml.Node) {
		if node.Kind == yaml.MappingNode {
			for index := 0; index+1 < len(node.Content); index += 2 {
				key, value := node.Content[index], node.Content[index+1]
				if key.Value == "uuid" {
					if !pattern.MatchString(value.Value) || seen[value.Value] {
						t.Fatalf("invalid or duplicate UUID %q", value.Value)
					}
					seen[value.Value] = true
				}
				visit(value)
			}
			return
		}
		for _, child := range node.Content {
			visit(child)
		}
	}
	visit(&root)
	if len(seen) != 52 {
		t.Fatalf("UUID count=%d", len(seen))
	}
}

// TestDiscoveryJavaScriptTransformsSnapshot executes both LLD transforms against representative API JSON.
func TestDiscoveryJavaScriptTransformsSnapshot(t *testing.T) {
	node, err := exec.LookPath("node")
	if err != nil {
		t.Skip("node is not installed")
	}
	data, err := os.ReadFile("template_homeauthmonitorgw.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var document templateDocument
	if err := yaml.Unmarshal(data, &document); err != nil {
		t.Fatal(err)
	}
	snapshot := `{"controller-main":{"driver":"snmp","available":true,"stale":false,"last_success":"2026-10-04T00:00:00Z","metrics":[{"name":"sysUpTime","value":123,"value_type":"counter","unit":"centiseconds","timestamp":"2026-10-04T00:00:00Z","labels":{"oid":"1.3.6.1.2.1.1.3.0"}},{"name":"display.name","value":"device","value_type":"string","timestamp":"2026-10-04T00:00:00Z"}]}}`
	for _, rule := range document.Export.Templates[0].DiscoveryRules {
		script := "const value = process.argv[1]; function transform() {\n" + rule.Preprocessing[0].Parameters[0] + "\n} process.stdout.write(transform());"
		output, err := exec.Command(node, "-e", script, snapshot).CombinedOutput()
		if err != nil {
			t.Fatalf("rule %q: %v: %s", rule.Key, err, output)
		}
		var discovered []map[string]any
		if err := json.Unmarshal(output, &discovered); err != nil {
			t.Fatalf("rule %q output: %v: %q", rule.Key, err, output)
		}
		if len(discovered) == 0 || discovered[0]["{#SOURCE}"] != "controller-main" {
			t.Fatalf("rule %q output=%v", rule.Key, discovered)
		}
		switch rule.Key {
		case "automation.gateway.sources.discovery":
			if len(discovered) != 1 || discovered[0]["{#SOURCEPATH}"] != `$["controller-main"]` {
				t.Fatalf("source discovery=%v", discovered)
			}
		case "automation.gateway.metrics.discovery":
			if len(discovered) != 1 {
				t.Fatalf("metric discovery=%v", discovered)
			}
			byID := map[string]map[string]any{}
			for _, metric := range discovered {
				byID[metric["{#METRIC_ID}"].(string)] = metric
			}
			if byID["display.name"]["{#VALUE_JSONPATH}"] != `$["controller-main"].metrics[?(@.name == "display.name")].value.first()` {
				t.Fatalf("name metric=%v", byID["display.name"])
			}
		case "automation.gateway.numeric_metrics.discovery":
			if len(discovered) != 1 {
				t.Fatalf("numeric metric discovery=%v", discovered)
			}
			metric := discovered[0]
			if metric["{#METRIC_ID}"] != "1.3.6.1.2.1.1.3.0" || metric["{#VALUE_JSONPATH}"] != `$["controller-main"].metrics[?(@.labels.oid == "1.3.6.1.2.1.1.3.0")].value.first()` || !regexp.MustCompile(`^[0-9a-f]+$`).MatchString(metric["{#METRIC_KEY}"].(string)) {
				t.Fatalf("numeric OID metric=%v", metric)
			}
		default:
			t.Fatalf("unexpected discovery key %q", rule.Key)
		}
	}
}

// TestMasterJavaScriptRejectsInvalidPayloads verifies HTTP 200 alone cannot keep monitoring supported.
func TestMasterJavaScriptRejectsInvalidPayloads(t *testing.T) {
	node, err := exec.LookPath("node")
	if err != nil {
		t.Skip("node is not installed")
	}
	data, err := os.ReadFile("template_homeauthmonitorgw.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var document templateDocument
	if err := yaml.Unmarshal(data, &document); err != nil {
		t.Fatal(err)
	}
	script := "const value = process.argv[1]; function transform() {\n" + document.Export.Templates[0].Items[0].Preprocessing[0].Parameters[0] + "\n} process.stdout.write(transform());"
	valid := `{"source-one":{"driver":"nut","available":false,"stale":true,"last_success":"0001-01-01T00:00:00Z","metrics":[]}}`
	output, err := exec.Command(node, "-e", script, valid).CombinedOutput()
	if err != nil || string(output) != valid {
		t.Fatalf("valid payload: %v output=%q", err, output)
	}
	invalid := []string{
		`not JSON`,
		`[]`,
		`{"bad/source":{"driver":"nut","available":true,"stale":false,"last_success":"x","metrics":[]}}`,
		`{"source-one":{"driver":"nut","available":"yes","stale":false,"last_success":"2026-10-04T00:00:00Z","metrics":[]}}`,
		`{"source-one":{"driver":"nut","available":true,"stale":false,"last_success":"not-a-time","metrics":[]}}`,
		`{"source-one":{"driver":"nut","available":true,"stale":false,"last_success":"2026-10-04T00:00:00Z","metrics":[{"name":"bad-time","value":1,"value_type":"number","timestamp":"not-a-time"}]}}`,
		`{"source-one":{"driver":"nut","available":true,"stale":false,"last_success":"2026-10-04T00:00:00Z","metrics":[{"name":"missing-fields"}]}}`,
	}
	for _, payload := range invalid {
		if output, err := exec.Command(node, "-e", script, payload).CombinedOutput(); err == nil {
			t.Fatalf("accepted payload %q with output %q", payload, output)
		}
	}
}

// TestLastSuccessJavaScriptHandlesNeverSuccessfulSources verifies zero time has a supported sentinel.
func TestLastSuccessJavaScriptHandlesNeverSuccessfulSources(t *testing.T) {
	node, err := exec.LookPath("node")
	if err != nil {
		t.Skip("node is not installed")
	}
	data, err := os.ReadFile("template_homeauthmonitorgw.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var document templateDocument
	if err := yaml.Unmarshal(data, &document); err != nil {
		t.Fatal(err)
	}
	var scriptBody string
	for _, rule := range document.Export.Templates[0].DiscoveryRules {
		for _, prototype := range rule.ItemPrototypes {
			if strings.HasPrefix(prototype.Key, "automation.gateway.source.last_success[") && len(prototype.Preprocessing) == 2 {
				scriptBody = prototype.Preprocessing[1].Parameters[0]
			}
		}
	}
	if scriptBody == "" {
		t.Fatal("last_success JavaScript preprocessing not found")
	}
	script := "const value = process.argv[1]; function transform() {\n" + scriptBody + "\n} process.stdout.write(String(transform()));"
	for input, expected := range map[string]string{
		"0001-01-01T00:00:00Z": "0",
		"2026-10-04T00:00:00Z": "1791072000",
	} {
		output, err := exec.Command(node, "-e", script, input).CombinedOutput()
		if err != nil || string(output) != expected {
			t.Fatalf("input=%q error=%v output=%q", input, err, output)
		}
	}
	if output, err := exec.Command(node, "-e", script, "invalid").CombinedOutput(); err == nil {
		t.Fatalf("invalid timestamp accepted with output %q", output)
	}
}

// TestDeviceDashboardsExposeStableHumanReadableKPIs verifies both device views use stable core items while LLD retains detail metrics.
func TestDeviceDashboardsExposeStableHumanReadableKPIs(t *testing.T) {
	data, err := os.ReadFile("template_homeauthmonitorgw.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var document templateDocument
	if err := yaml.Unmarshal(data, &document); err != nil {
		t.Fatal(err)
	}
	template := document.Export.Templates[0]
	dashboards := map[string]int{}
	for _, dashboard := range template.Dashboards {
		widgets := 0
		for _, page := range dashboard.Pages {
			widgets += len(page.Widgets)
		}
		dashboards[dashboard.Name] = widgets
	}
	if dashboards["WAGO 750-880"] < 8 || dashboards["Phoenix Contact UPS"] < 7 {
		t.Fatalf("dashboards=%v", dashboards)
	}
	items := map[string]struct{ valueType, units, valueMap string }{}
	for _, item := range template.Items {
		items[item.Key] = struct{ valueType, units, valueMap string }{item.ValueType, item.Units, item.ValueMap.Name}
	}
	if item := items["automation.gateway.wago.uptime"]; item.valueType != "FLOAT" || item.units != "uptime" {
		t.Fatalf("WAGO uptime=%+v", item)
	}
	if item := items["automation.gateway.wago.rtc_battery"]; item.valueMap != "WAGO RTC battery status" {
		t.Fatalf("RTC item=%+v", item)
	}
	if item := items["automation.gateway.wago.iec_cycle_time"]; item.valueType != "FLOAT" || item.units != "µs" {
		t.Fatalf("WAGO IEC cycle time=%+v", item)
	}
	if item := items["automation.gateway.phoenix.status"]; item.valueMap != "" {
		t.Fatalf("UPS status item=%+v", item)
	}
	valueMaps := map[string]bool{}
	for _, valueMap := range template.ValueMaps {
		valueMaps[valueMap.Name] = true
	}
	if !valueMaps["WAGO RTC battery status"] || valueMaps["NUT UPS status"] {
		t.Fatalf("value maps=%v", valueMaps)
	}
}

// TestDashboardLayoutMatchesUserExport protects the dashboard geometry customized in Zabbix.
func TestDashboardLayoutMatchesUserExport(t *testing.T) {
	data, err := os.ReadFile("template_homeauthmonitorgw.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var document templateDocument
	if err := yaml.Unmarshal(data, &document); err != nil {
		t.Fatal(err)
	}
	type geometry struct{ x, y, width, height, widgetType string }
	expected := map[string]map[string]geometry{
		"Phoenix Contact UPS": {
			"Health": {"0", "0", "18", "", "item"}, "Battery charge": {"0", "2", "12", "", "item"},
			"Battery temperature": {"12", "2", "12", "", "item"}, "UPS status": {"18", "0", "12", "", "item"},
			"Output voltage": {"24", "2", "12", "", "item"}, "Model": {"30", "0", "18", "", "item"},
			"Battery runtime": {"36", "2", "12", "", "item"}, "<graph>": {"0", "4", "48", "5", "svggraph"},
		},
		"WAGO 750-880": {
			"Health": {"0", "0", "11", "", "item"}, "Uptime": {"11", "0", "15", "", "item"},
			"RTC battery": {"26", "0", "10", "", "item"}, "Firmware": {"36", "0", "12", "", "item"},
			"Diagnostic": {"0", "2", "24", "", "item"}, "Error code": {"24", "2", "12", "", "item"},
			"IEC task status": {"36", "2", "12", "", "item"}, "<graph>": {"0", "4", "48", "5", "svggraph"},
			"CODESYS software": {"0", "9", "24", "8", "itemhistory"}, "K-bus modules": {"24", "9", "24", "8", "wago_kbus"},
		},
	}
	for _, dashboard := range document.Export.Templates[0].Dashboards {
		want, found := expected[dashboard.Name]
		if !found {
			continue
		}
		got := map[string]geometry{}
		for _, page := range dashboard.Pages {
			for _, widget := range page.Widgets {
				name := widget.Name
				if name == "" {
					name = "<graph>"
				}
				x, y := widget.X, widget.Y
				if x == "" {
					x = "0"
				}
				if y == "" {
					y = "0"
				}
				got[name] = geometry{x, y, widget.Width, widget.Height, widget.Type}
			}
		}
		if len(got) != len(want) {
			t.Fatalf("dashboard %q widget count/layout=%v", dashboard.Name, got)
		}
		for name, wanted := range want {
			if got[name] != wanted {
				t.Fatalf("dashboard %q widget %q=%+v, want %+v", dashboard.Name, name, got[name], wanted)
			}
		}
		delete(expected, dashboard.Name)
	}
	if len(expected) != 0 {
		t.Fatalf("missing dashboards: %v", expected)
	}
}

// TestPhoenixStatusTranslation verifies every RFC 9271 status token remains understandable in combinations.
func TestPhoenixStatusTranslation(t *testing.T) {
	node, err := exec.LookPath("node")
	if err != nil {
		t.Skip("node is not installed")
	}
	data, err := os.ReadFile("template_homeauthmonitorgw.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var document templateDocument
	if err := yaml.Unmarshal(data, &document); err != nil {
		t.Fatal(err)
	}
	body := ""
	for _, item := range document.Export.Templates[0].Items {
		if item.Key != "automation.gateway.phoenix.status" {
			continue
		}
		if item.ValueMap.Name != "" {
			t.Fatalf("status translation must not depend on an exact-value map: %q", item.ValueMap.Name)
		}
		for _, step := range item.Preprocessing {
			if step.Type == "JAVASCRIPT" {
				body = step.Parameters[0]
			}
		}
	}
	if body == "" {
		t.Fatal("Phoenix status item has no JavaScript translation")
	}
	run := func(value string) string {
		t.Helper()
		script := "const value = process.argv[1]; function transform() {\n" + body + "\n} process.stdout.write(String(transform()));"
		output, err := exec.Command(node, "-e", script, value).CombinedOutput()
		if err != nil {
			t.Fatalf("translate %q: %v: %s", value, err, output)
		}
		return string(output)
	}
	if got := run("OL"); got != "Online / utility power (OL)" {
		t.Fatalf("OL=%q", got)
	}
	if got := run("OB LB"); got != "On battery (OB) / Low battery (LB)" {
		t.Fatalf("OB LB=%q", got)
	}
	if got := run("OL CHRG FUTURE"); got != "Online / utility power (OL) / Battery charging (CHRG) / Unknown status (FUTURE)" {
		t.Fatalf("combined status=%q", got)
	}
	for _, token := range []string{"ALARM", "BOOST", "BYPASS", "CAL", "CHRG", "COMM", "DISCHRG", "FSD", "LB", "NOCOMM", "OB", "OFF", "OL", "OVER", "RB", "TEST", "TICK", "TOCK", "TRIM"} {
		if strings.Contains(run(token), "Unknown status") {
			t.Fatalf("RFC 9271 token %q is not translated", token)
		}
	}
}

// TestWAGOProjectAndModuleInventory verifies the specialized software and K-bus views and hardware-change alert.
func TestWAGOProjectAndModuleInventory(t *testing.T) {
	node, err := exec.LookPath("node")
	if err != nil {
		t.Skip("node is not installed")
	}
	data, err := os.ReadFile("template_homeauthmonitorgw.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var document templateDocument
	if err := yaml.Unmarshal(data, &document); err != nil {
		t.Fatal(err)
	}
	template := document.Export.Templates[0]
	items := map[string]struct {
		valueType     string
		preprocessing []struct {
			Type       string   `yaml:"type"`
			Parameters []string `yaml:"parameters"`
		}
		triggers []struct {
			Name       string `yaml:"name"`
			Expression string `yaml:"expression"`
		}
	}{}
	for _, item := range template.Items {
		items[item.Key] = struct {
			valueType     string
			preprocessing []struct {
				Type       string   `yaml:"type"`
				Parameters []string `yaml:"parameters"`
			}
			triggers []struct {
				Name       string `yaml:"name"`
				Expression string `yaml:"expression"`
			}
		}{item.ValueType, item.Preprocessing, item.Triggers}
	}
	required := []string{
		"automation.gateway.wago.project_id",
		"automation.gateway.wago.project_name",
		"automation.gateway.wago.project_version",
		"automation.gateway.wago.software_info",
		"automation.gateway.wago.module_count",
		"automation.gateway.wago.module_inventory",
		"automation.gateway.wago.module_inventory.signature",
	}
	for _, key := range required {
		if _, found := items[key]; !found {
			t.Fatalf("missing WAGO item %q", key)
		}
	}
	if items["automation.gateway.wago.project_id"].valueType != "UNSIGNED" || items["automation.gateway.wago.project_name"].valueType != "TEXT" || items["automation.gateway.wago.project_version"].valueType != "TEXT" {
		t.Fatalf("project items=%+v", items)
	}
	if items["automation.gateway.wago.module_count"].valueType != "UNSIGNED" || items["automation.gateway.wago.module_inventory"].valueType != "TEXT" || items["automation.gateway.wago.module_inventory.signature"].valueType != "TEXT" {
		t.Fatalf("module items=%+v", items)
	}
	mapping := ""
	for _, macro := range template.Macros {
		if macro.Macro == "{$WAGO_MODULE_DESCRIPTIONS}" {
			mapping = macro.Value
		}
	}
	if mapping != `{"750-652/000-000":"Serial interface"}` {
		t.Fatalf("module mapping=%q", mapping)
	}
	snapshot := `{"wago-750-880-snmp3":{"metrics":[{"name":"wioProjectId","value":16507229},{"name":"wioProjectName","value":"Althegnenberg_Heimauto10.pro"},{"name":"wioProjectVersion","value":""},{"name":"wioIecTaskName[1]","value":"MainTask"},{"name":"wioIecTaskStatus[1]","value":0},{"name":"wioIecTaskMode[1]","value":0},{"name":"wioIecTaskCycleTime[1]","value":6},{"name":"wioIecTaskCycleTimeMin[1]","value":5},{"name":"wioIecTaskCycleTimeMax[1]","value":1044},{"name":"wioIecTaskCycleTimeAvg[1]","value":7},{"name":"wioModulCount","value":2},{"name":"wioModuleNumber[2]","value":2},{"name":"wioModuleName[2]","value":"750-652/000-000"},{"name":"wioModuleType[2]","value":163},{"name":"wioModuleNumber[1]","value":1},{"name":"wioModuleName[1]","value":"750-4xx"},{"name":"wioModuleType[1]","value":1}]}}`
	runJavaScript := func(key string) string {
		t.Helper()
		body := ""
		for _, step := range items[key].preprocessing {
			if step.Type == "JAVASCRIPT" {
				body = step.Parameters[0]
			}
		}
		if body == "" {
			t.Fatalf("item %q has no JavaScript", key)
		}
		body = strings.NewReplacer("{$WAGO_SOURCE}", "wago-750-880-snmp3", "{$WAGO_MODULE_DESCRIPTIONS}", mapping).Replace(body)
		script := "const value = process.argv[1]; function transform() {\n" + body + "\n} process.stdout.write(String(transform()));"
		output, err := exec.Command(node, "-e", script, snapshot).CombinedOutput()
		if err != nil {
			t.Fatalf("item %q: %v: %s", key, err, output)
		}
		return string(output)
	}
	if got := runJavaScript("automation.gateway.wago.project_version"); got != "Not set" {
		t.Fatalf("project version=%q", got)
	}
	software := runJavaScript("automation.gateway.wago.software_info")
	for _, want := range []string{"Project ID: 16507229", "Project name: Althegnenberg_Heimauto10.pro", "Project version: Not set", "Task 1: MainTask", "Status: 0", "Cycle time: 6 µs", "Minimum: 5 µs", "Maximum: 1044 µs", "Average: 7 µs"} {
		if !strings.Contains(software, want) {
			t.Fatalf("software information missing %q: %q", want, software)
		}
	}
	if got := runJavaScript("automation.gateway.wago.module_inventory.signature"); got != "1|750-4xx|1\n2|750-652/000-000|163" {
		t.Fatalf("module signature=%q", got)
	}
	inventory := runJavaScript("automation.gateway.wago.module_inventory")
	for _, want := range []string{"Reported module count: 2", "01: 750-4xx (type 1)", "02: 750-652/000-000 — Serial interface (type 163)"} {
		if !strings.Contains(inventory, want) {
			t.Fatalf("module inventory missing %q: %q", want, inventory)
		}
	}
	signature := items["automation.gateway.wago.module_inventory.signature"]
	if len(signature.triggers) != 1 || signature.triggers[0].Name != "WAGO K-bus module inventory changed" || !strings.Contains(signature.triggers[0].Expression, "change(/Template HomeAuthMonitorGW by HTTP/automation.gateway.wago.module_inventory.signature)=1") {
		t.Fatalf("module inventory triggers=%+v", signature.triggers)
	}
	widgets := map[string]string{}
	widgetTypes := map[string]string{}
	widgetSettings := map[string]map[string]any{}
	for _, dashboard := range template.Dashboards {
		if dashboard.Name != "WAGO 750-880" {
			continue
		}
		for _, page := range dashboard.Pages {
			for _, widget := range page.Widgets {
				if widget.Type == "plaintext" {
					t.Fatalf("Zabbix 7.4 has no plaintext widget: %+v", widget)
				}
				settings := map[string]any{}
				for _, field := range widget.Fields {
					settings[field.Name] = field.Value
					// Accept both itemhistory-style (columns.0.itemid) and direct item refs (itemid.0).
					if field.Name == "columns.0.itemid" || field.Name == "itemid.0" {
						if value, ok := field.Value.(map[string]any); ok {
							if key, ok2 := value["key"].(string); ok2 {
								widgets[widget.Name] = widget.Type + ":" + key
							}
						}
					}
				}
				widgetSettings[widget.Name] = settings
				widgetTypes[widget.Name] = widget.Type
			}
		}
	}
	if widgets["CODESYS software"] != "itemhistory:automation.gateway.wago.software_info" {
		t.Fatalf("CODESYS software widget=%q", widgets["CODESYS software"])
	}
	// K-bus modules is now the custom wago_kbus widget backed by the kbus_layout item.
	if widgetTypes["K-bus modules"] != "wago_kbus" {
		t.Fatalf("K-bus modules widget type=%q, want wago_kbus", widgetTypes["K-bus modules"])
	}
	kbusSettings := widgetSettings["K-bus modules"]
	hostRef, ok := kbusSettings["hostid.0"].(map[string]any)
	if !ok || hostRef["host"] != "Template HomeAuthMonitorGW by HTTP" {
		t.Fatalf("K-bus modules wago_kbus hostid field=%v", kbusSettings["hostid.0"])
	}
	// itemhistory-specific settings apply only to CODESYS software.
	settings := widgetSettings["CODESYS software"]
	if settings["show_lines"] != "1" || settings["show_column_header"] != "0" || settings["columns.0.monospace_font"] != "1" {
		t.Fatalf("CODESYS software widget settings=%v", settings)
	}
}

// TestOverallHealthJavaScriptAggregatesEveryCollector verifies the five-state summary and worst-state precedence.
func TestOverallHealthJavaScriptAggregatesEveryCollector(t *testing.T) {
	node, err := exec.LookPath("node")
	if err != nil {
		t.Skip("node is not installed")
	}
	data, err := os.ReadFile("template_homeauthmonitorgw.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var document templateDocument
	if err := yaml.Unmarshal(data, &document); err != nil {
		t.Fatal(err)
	}
	var scriptBody string
	for _, item := range document.Export.Templates[0].Items {
		if item.Key != "automation.gateway.health.overall" {
			continue
		}
		if item.Name != "TS Service health: HeimAuto" || item.ValueType != "UNSIGNED" || item.ValueMap.Name != "Overall collector health" || item.MasterItem.Key != "automation.gateway.snapshot" {
			t.Fatalf("overall health item=%+v", item)
		}
		for _, preprocessing := range item.Preprocessing {
			if preprocessing.Type == "JAVASCRIPT" {
				scriptBody = preprocessing.Parameters[0]
			}
		}
	}
	if scriptBody == "" {
		t.Fatal("overall health JavaScript not found")
	}
	wantMap := map[string]string{
		"0": "Good",
		"1": "Degraded",
		"2": "Real issue / unavailable",
	}
	foundMap := false
	for _, valueMap := range document.Export.Templates[0].ValueMaps {
		if valueMap.Name != "Overall collector health" {
			continue
		}
		foundMap = true
		if len(valueMap.Mappings) != len(wantMap) {
			t.Fatalf("overall value map=%+v", valueMap.Mappings)
		}
		for _, mapping := range valueMap.Mappings {
			if wantMap[mapping.Value] != mapping.NewValue {
				t.Fatalf("overall value map entry=%+v", mapping)
			}
		}
	}
	if !foundMap {
		t.Fatal("overall health value map not found")
	}
	foundCollectorMap := false
	for _, valueMap := range document.Export.Templates[0].ValueMaps {
		if valueMap.Name != "Collector health" {
			continue
		}
		foundCollectorMap = true
		if len(valueMap.Mappings) != len(wantMap) {
			t.Fatalf("collector value map=%+v", valueMap.Mappings)
		}
		for _, mapping := range valueMap.Mappings {
			if wantMap[mapping.Value] != mapping.NewValue {
				t.Fatalf("collector value map entry=%+v", mapping)
			}
		}
	}
	if !foundCollectorMap {
		t.Fatal("collector health value map not found")
	}
	scriptBody = strings.NewReplacer(
		"{$PHOENIX_BATTERY_CRITICAL}", "20",
		"{$PHOENIX_BATTERY_WARNING}", "50",
		"{$PHOENIX_TEMPERATURE_CRITICAL}", "55",
		"{$PHOENIX_TEMPERATURE_WARNING}", "45",
	).Replace(scriptBody)
	initialized := `"driver":"snmp","available":true,"stale":false,"last_success":"2026-10-04T00:00:00Z"`
	goodGeneric := `{"generic":{` + initialized + `,"metrics":[{"name":"sysUpTime","value":123,"value_type":"counter","timestamp":"2026-10-04T00:00:00Z"}]}}`
	goodWAGO := `{"controller":{` + initialized + `,"metrics":[{"name":"wioErrorGroup","value":0,"labels":{"oid":"1.3.6.1.4.1.13576.10.1.20.1.0"}},{"name":"wioErrorCode","value":0,"labels":{"oid":"1.3.6.1.4.1.13576.10.1.20.2.0"}},{"name":"wioErrorDescription","value":"Coupler running, OK","labels":{"oid":"1.3.6.1.4.1.13576.10.1.20.4.0"}},{"name":"wioRtcBatteryStatus","value":0,"labels":{"oid":"1.3.6.1.4.1.13576.10.1.11.5.0"}}]}}`
	tests := []struct {
		name, snapshot, want string
	}{
		{"no sources", `{}`, "1"},
		{"registered but never successful", `{"new":{"driver":"snmp","available":false,"stale":true,"last_success":"0001-01-01T00:00:00Z","metrics":[]}}`, "1"},
		{"previously successful but unavailable", `{"failed":{"driver":"snmp","available":false,"stale":true,"last_success":"2026-10-04T00:00:00Z","metrics":[{"name":"retained","value":1}]}}`, "2"},
		{"previously successful but stale", `{"stale":{"driver":"snmp","available":true,"stale":true,"last_success":"2026-10-04T00:00:00Z","metrics":[{"name":"retained","value":1}]}}`, "1"},
		{"successful but empty", `{"empty":{` + initialized + `,"metrics":[]}}`, "1"},
		{"NUT data reports a problem", `{"ups":{"driver":"nut","available":true,"stale":false,"last_success":"2026-10-04T00:00:00Z","metrics":[{"name":"ups.status","value":"OB LB"},{"name":"battery.charge","value":10},{"name":"battery.temperature","value":28}]}}`, "2"},
		{"NUT health metrics are incomplete", `{"ups":{"driver":"nut","available":true,"stale":false,"last_success":"2026-10-04T00:00:00Z","metrics":[{"name":"ups.status","value":"OL"}]}}`, "1"},
		{"SNMP diagnostics report a problem", strings.Replace(goodWAGO, `"name":"wioErrorCode","value":0`, `"name":"wioErrorCode","value":7`, 1), "2"},
		{"known generic data is healthy", goodGeneric, "0"},
		{"complete healthy SNMP diagnostics are healthy", goodWAGO, "0"},
		{"empty collector degrades healthy aggregate", `{"empty":{` + initialized + `,"metrics":[]},"generic":{` + initialized + `,"metrics":[{"name":"sysUpTime","value":123}]}}`, "1"},
		{"real issue dominates uninitialized collector", `{"new":{"driver":"snmp","available":false,"stale":true,"last_success":"0001-01-01T00:00:00Z","metrics":[]},"failed":{"driver":"snmp","available":false,"stale":true,"last_success":"2026-10-04T00:00:00Z","metrics":[{"name":"retained","value":1}]}}`, "2"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			script := "const value = process.argv[1]; function transform() {\n" + scriptBody + "\n} process.stdout.write(String(transform()));"
			output, err := exec.Command(node, "-e", script, test.snapshot).CombinedOutput()
			if err != nil || string(output) != test.want {
				t.Fatalf("want=%q error=%v output=%q", test.want, err, output)
			}
		})
	}
}

// TestDeviceHealthJavaScriptScoresCollectorsIndependently executes both static health transforms.
func TestDeviceHealthJavaScriptScoresCollectorsIndependently(t *testing.T) {
	node, err := exec.LookPath("node")
	if err != nil {
		t.Skip("node is not installed")
	}
	data, err := os.ReadFile("template_homeauthmonitorgw.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var document templateDocument
	if err := yaml.Unmarshal(data, &document); err != nil {
		t.Fatal(err)
	}
	tests := []struct {
		key, source string
		want        string
	}{
		{"automation.gateway.wago.health", `{"available":true,"stale":false,"metrics":[{"value":0,"labels":{"oid":"1.3.6.1.4.1.13576.10.1.20.1.0"}},{"value":0,"labels":{"oid":"1.3.6.1.4.1.13576.10.1.20.2.0"}},{"value":"Coupler running, OK","labels":{"oid":"1.3.6.1.4.1.13576.10.1.20.4.0"}},{"value":0,"labels":{"oid":"1.3.6.1.4.1.13576.10.1.11.5.0"}}]}`, "0"},
		{"automation.gateway.wago.health", `{"available":true,"stale":false,"metrics":[{"value":7,"labels":{"oid":"1.3.6.1.4.1.13576.10.1.20.2.0"}}]}`, "2"},
		{"automation.gateway.wago.health", `{"available":true,"stale":false,"metrics":[{"value":"Coupler running, OK","labels":{"oid":"1.3.6.1.4.1.13576.10.1.20.4.0"}}]}`, "1"},
		{"automation.gateway.wago.health", `{"available":false,"stale":true,"metrics":[]}`, "2"},
		{"automation.gateway.phoenix.health", `{"available":true,"stale":false,"metrics":[{"name":"ups.status","value":"OL"},{"name":"battery.charge","value":100},{"name":"battery.temperature","value":28}]}`, "0"},
		{"automation.gateway.phoenix.health", `{"available":true,"stale":false,"metrics":[{"name":"ups.status","value":"OB LB"},{"name":"battery.charge","value":10}]}`, "2"},
		{"automation.gateway.phoenix.health", `{"available":true,"stale":false,"metrics":[{"name":"ups.status","value":"OL"}]}`, "1"},
		{"automation.gateway.phoenix.health", `{"available":true,"stale":true,"metrics":[{"name":"ups.status","value":"OL"},{"name":"battery.charge","value":100},{"name":"battery.temperature","value":28}]}`, "1"},
	}
	wantNames := map[string]string{
		"automation.gateway.wago.health":    "TS Service health: WAGO 750-880",
		"automation.gateway.phoenix.health": "TS Service health: Phoenix Contact UPS",
	}
	checkedTriggers := map[string]bool{}
	for _, test := range tests {
		var scriptBody string
		for _, item := range document.Export.Templates[0].Items {
			if item.Key != test.key {
				continue
			}
			if item.Name != wantNames[test.key] {
				t.Fatalf("key=%q name=%q", test.key, item.Name)
			}
			if !checkedTriggers[test.key] {
				if len(item.Triggers) != 2 {
					t.Fatalf("key=%q triggers=%+v", test.key, item.Triggers)
				}
				expressions := item.Triggers[0].Expression + "\n" + item.Triggers[1].Expression
				if !strings.Contains(expressions, ")=2") || !strings.Contains(expressions, ")=1") || strings.Contains(expressions, ")=3") {
					t.Fatalf("key=%q trigger expressions=%q", test.key, expressions)
				}
				checkedTriggers[test.key] = true
			}
			for _, preprocessing := range item.Preprocessing {
				if preprocessing.Type == "JAVASCRIPT" {
					scriptBody = preprocessing.Parameters[0]
				}
			}
		}
		if scriptBody == "" {
			t.Fatalf("JavaScript not found for %q", test.key)
		}
		scriptBody = strings.NewReplacer(
			"{$PHOENIX_BATTERY_CRITICAL}", "20",
			"{$PHOENIX_BATTERY_WARNING}", "50",
			"{$PHOENIX_TEMPERATURE_CRITICAL}", "55",
			"{$PHOENIX_TEMPERATURE_WARNING}", "45",
		).Replace(scriptBody)
		script := "const value = process.argv[1]; function transform() {\n" + scriptBody + "\n} process.stdout.write(String(transform()));"
		output, err := exec.Command(node, "-e", script, test.source).CombinedOutput()
		if err != nil || string(output) != test.want {
			t.Fatalf("key=%q want=%q error=%v output=%q", test.key, test.want, err, output)
		}
	}
	var genericName, genericScript string
	for _, rule := range document.Export.Templates[0].DiscoveryRules {
		for _, prototype := range rule.ItemPrototypes {
			if prototype.Key != `automation.gateway.source.health["{#SOURCE}"]` {
				continue
			}
			genericName = prototype.Name
			for _, preprocessing := range prototype.Preprocessing {
				if preprocessing.Type == "JAVASCRIPT" {
					genericScript = preprocessing.Parameters[0]
				}
			}
		}
	}
	if genericName != "TS Service health: {#SOURCE}" || genericScript == "" {
		t.Fatalf("generic health name=%q script=%q", genericName, genericScript)
	}
	for source, want := range map[string]string{
		`{"available":true,"stale":false,"last_success":"2026-10-04T00:00:00Z","metrics":[{"name":"metric","value":1}]}`: "0",
		`{"available":true,"stale":true,"last_success":"2026-10-04T00:00:00Z","metrics":[{"name":"metric","value":1}]}`:  "1",
		`{"available":true,"stale":false,"last_success":"2026-10-04T00:00:00Z","metrics":[]}`:                            "1",
		`{"available":false,"stale":true,"last_success":"2026-10-04T00:00:00Z","metrics":[{"name":"metric","value":1}]}`: "2",
	} {
		script := "const value = process.argv[1]; function transform() {\n" + genericScript + "\n} process.stdout.write(String(transform()));"
		output, err := exec.Command(node, "-e", script, source).CombinedOutput()
		if err != nil || string(output) != want {
			t.Fatalf("generic health source=%q want=%q error=%v output=%q", source, want, err, output)
		}
	}
}
