// File: zabbix/template_test.go
// Purpose: Validate the import template structure and its single-request dependent-item design.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package zabbix

import (
	"encoding/json"
	"os"
	"os/exec"
	"regexp"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

type templateDocument struct {
	Export struct {
		Version        string `yaml:"version"`
		TemplateGroups []struct {
			Name string `yaml:"name"`
		} `yaml:"template_groups"`
		Templates []struct {
			Items []struct {
				Name      string `yaml:"name"`
				Type      string `yaml:"type"`
				Key       string `yaml:"key"`
				URL       string `yaml:"url"`
				ValueType string `yaml:"value_type"`
				Units     string `yaml:"units"`
				ValueMap  struct {
					Name string `yaml:"name"`
				} `yaml:"valuemap"`
				MasterItem struct {
					Key string `yaml:"key"`
				} `yaml:"master_item"`
				Headers []struct {
					Name  string `yaml:"name"`
					Value string `yaml:"value"`
				} `yaml:"headers"`
				Preprocessing []struct {
					Type       string   `yaml:"type"`
					Parameters []string `yaml:"parameters"`
				} `yaml:"preprocessing"`
			} `yaml:"items"`
			DiscoveryRules []struct {
				Type       string `yaml:"type"`
				Key        string `yaml:"key"`
				MasterItem struct {
					Key string `yaml:"key"`
				} `yaml:"master_item"`
				ItemPrototypes []struct {
					Key        string `yaml:"key"`
					ValueType  string `yaml:"value_type"`
					Trends     string `yaml:"trends"`
					MasterItem struct {
						Key string `yaml:"key"`
					} `yaml:"master_item"`
					Preprocessing []struct {
						Type       string   `yaml:"type"`
						Parameters []string `yaml:"parameters"`
					} `yaml:"preprocessing"`
				} `yaml:"item_prototypes"`
				TriggerPrototypes []struct {
					Expression string `yaml:"expression"`
				} `yaml:"trigger_prototypes"`
				Preprocessing []struct {
					Type       string   `yaml:"type"`
					Parameters []string `yaml:"parameters"`
				} `yaml:"preprocessing"`
			} `yaml:"discovery_rules"`
			Macros []struct {
				Macro string `yaml:"macro"`
				Type  string `yaml:"type"`
				Value string `yaml:"value"`
			} `yaml:"macros"`
			Dashboards []struct {
				Name  string `yaml:"name"`
				Pages []struct {
					Widgets []struct {
						Type string `yaml:"type"`
					} `yaml:"widgets"`
				} `yaml:"pages"`
			} `yaml:"dashboards"`
			ValueMaps []struct {
				Name string `yaml:"name"`
			} `yaml:"valuemaps"`
		} `yaml:"templates"`
	} `yaml:"zabbix_export"`
}

// TestTemplateUsesOneHTTPSMasterAndDependentDiscovery verifies the intended cache-efficient topology.
func TestTemplateUsesOneHTTPSMasterAndDependentDiscovery(t *testing.T) {
	data, err := os.ReadFile("template_homeauthmonitorgw.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var document templateDocument
	if err := yaml.Unmarshal(data, &document); err != nil {
		t.Fatalf("parse template: %v", err)
	}
	if document.Export.Version != "7.4" || len(document.Export.Templates) != 1 {
		t.Fatalf("version=%q templates=%d", document.Export.Version, len(document.Export.Templates))
	}
	if len(document.Export.TemplateGroups) != 1 || document.Export.TemplateGroups[0].Name != "Templates/HomeAuthMonitorGW" {
		t.Fatalf("template groups=%+v", document.Export.TemplateGroups)
	}
	template := document.Export.Templates[0]
	if len(template.Items) != 16 || template.Items[0].Type != "HTTP_AGENT" || template.Items[0].Key != "automation.gateway.snapshot" || !strings.HasSuffix(template.Items[0].URL, "/api/v1/metrics") {
		t.Fatalf("master items=%+v", template.Items)
	}
	for _, item := range template.Items[1:] {
		if item.Type != "DEPENDENT" || item.URL != "" || item.MasterItem.Key != "automation.gateway.snapshot" {
			t.Fatalf("device item is not dependent-only: %+v", item)
		}
	}
	if len(template.Items[0].Headers) != 1 || template.Items[0].Headers[0].Name != "Authorization" || template.Items[0].Headers[0].Value != "Bearer {$AUTOMATION_GATEWAY_TOKEN}" {
		t.Fatalf("headers=%+v", template.Items[0].Headers)
	}
	if len(template.Items[0].Preprocessing) != 1 || template.Items[0].Preprocessing[0].Type != "JAVASCRIPT" || len(template.Items[0].Preprocessing[0].Parameters) != 1 {
		t.Fatalf("master preprocessing=%+v", template.Items[0].Preprocessing)
	}
	if len(template.DiscoveryRules) != 3 {
		t.Fatalf("discovery rules=%d", len(template.DiscoveryRules))
	}
	prototypeCounts := map[string]int{"automation.gateway.sources.discovery": 4, "automation.gateway.metrics.discovery": 2, "automation.gateway.numeric_metrics.discovery": 2}
	triggerCounts := map[string]int{"automation.gateway.sources.discovery": 2, "automation.gateway.metrics.discovery": 0, "automation.gateway.numeric_metrics.discovery": 0}
	foundGenericHealth := false
	for _, rule := range template.DiscoveryRules {
		if rule.Type != "DEPENDENT" || rule.MasterItem.Key != "automation.gateway.snapshot" {
			t.Fatalf("rule=%+v", rule)
		}
		if len(rule.ItemPrototypes) != prototypeCounts[rule.Key] || len(rule.TriggerPrototypes) != triggerCounts[rule.Key] {
			t.Fatalf("rule %q has %d items and %d triggers", rule.Key, len(rule.ItemPrototypes), len(rule.TriggerPrototypes))
		}
		for _, prototype := range rule.ItemPrototypes {
			if prototype.Key == `automation.gateway.source.health["{#SOURCE}"]` {
				foundGenericHealth = true
			}
			if prototype.MasterItem.Key != "automation.gateway.snapshot" {
				t.Fatalf("prototype %q master=%q", prototype.Key, prototype.MasterItem.Key)
			}
			if strings.HasPrefix(prototype.Key, "automation.gateway.metric") && !strings.Contains(prototype.Key, "{#METRIC_KEY}") {
				t.Fatalf("metric prototype uses unsafe identity: %q", prototype.Key)
			}
			if strings.HasPrefix(prototype.Key, "automation.gateway.metric.numeric[") && (prototype.ValueType != "FLOAT" || prototype.Trends == "0") {
				t.Fatalf("numeric metric prototype is not trendable: %+v", prototype)
			}
		}
		if len(rule.Preprocessing) != 1 || rule.Preprocessing[0].Type != "JAVASCRIPT" || len(rule.Preprocessing[0].Parameters) != 1 {
			t.Fatalf("rule %q preprocessing=%+v", rule.Key, rule.Preprocessing)
		}
	}
	if !foundGenericHealth {
		t.Fatal("missing per-source generic health prototype")
	}
	foundSecret := false
	for _, macro := range template.Macros {
		if macro.Macro == "{$AUTOMATION_GATEWAY_TOKEN}" {
			foundSecret = macro.Type == "SECRET_TEXT" && macro.Value == ""
		}
	}
	if !foundSecret {
		t.Fatal("missing valueless SECRET_TEXT token macro")
	}
}

// TestTemplateUUIDsAreUnique verifies every import object has one canonical stable identifier.
func TestTemplateUUIDsAreUnique(t *testing.T) {
	data, err := os.ReadFile("template_homeauthmonitorgw.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var root yaml.Node
	if err := yaml.Unmarshal(data, &root); err != nil {
		t.Fatal(err)
	}
	pattern := regexp.MustCompile(`^[0-9a-f]{32}$`)
	seen := map[string]bool{}
	var visit func(*yaml.Node)
	visit = func(node *yaml.Node) {
		if node.Kind == yaml.MappingNode {
			for index := 0; index+1 < len(node.Content); index += 2 {
				key, value := node.Content[index], node.Content[index+1]
				if key.Value == "uuid" {
					if !pattern.MatchString(value.Value) || seen[value.Value] {
						t.Fatalf("invalid or duplicate UUID %q", value.Value)
					}
					seen[value.Value] = true
				}
				visit(value)
			}
			return
		}
		for _, child := range node.Content {
			visit(child)
		}
	}
	visit(&root)
	if len(seen) != 42 {
		t.Fatalf("UUID count=%d", len(seen))
	}
}

// TestDiscoveryJavaScriptTransformsSnapshot executes both LLD transforms against representative API JSON.
func TestDiscoveryJavaScriptTransformsSnapshot(t *testing.T) {
	node, err := exec.LookPath("node")
	if err != nil {
		t.Skip("node is not installed")
	}
	data, err := os.ReadFile("template_homeauthmonitorgw.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var document templateDocument
	if err := yaml.Unmarshal(data, &document); err != nil {
		t.Fatal(err)
	}
	snapshot := `{"controller-main":{"driver":"snmp","available":true,"stale":false,"last_success":"2026-10-04T00:00:00Z","metrics":[{"name":"sysUpTime","value":123,"value_type":"counter","unit":"centiseconds","timestamp":"2026-10-04T00:00:00Z","labels":{"oid":"1.3.6.1.2.1.1.3.0"}},{"name":"display.name","value":"device","value_type":"string","timestamp":"2026-10-04T00:00:00Z"}]}}`
	for _, rule := range document.Export.Templates[0].DiscoveryRules {
		script := "const value = process.argv[1]; function transform() {\n" + rule.Preprocessing[0].Parameters[0] + "\n} process.stdout.write(transform());"
		output, err := exec.Command(node, "-e", script, snapshot).CombinedOutput()
		if err != nil {
			t.Fatalf("rule %q: %v: %s", rule.Key, err, output)
		}
		var discovered []map[string]any
		if err := json.Unmarshal(output, &discovered); err != nil {
			t.Fatalf("rule %q output: %v: %q", rule.Key, err, output)
		}
		if len(discovered) == 0 || discovered[0]["{#SOURCE}"] != "controller-main" {
			t.Fatalf("rule %q output=%v", rule.Key, discovered)
		}
		switch rule.Key {
		case "automation.gateway.sources.discovery":
			if len(discovered) != 1 || discovered[0]["{#SOURCEPATH}"] != `$["controller-main"]` {
				t.Fatalf("source discovery=%v", discovered)
			}
		case "automation.gateway.metrics.discovery":
			if len(discovered) != 1 {
				t.Fatalf("metric discovery=%v", discovered)
			}
			byID := map[string]map[string]any{}
			for _, metric := range discovered {
				byID[metric["{#METRIC_ID}"].(string)] = metric
			}
			if byID["display.name"]["{#VALUE_JSONPATH}"] != `$["controller-main"].metrics[?(@.name == "display.name")].value.first()` {
				t.Fatalf("name metric=%v", byID["display.name"])
			}
		case "automation.gateway.numeric_metrics.discovery":
			if len(discovered) != 1 {
				t.Fatalf("numeric metric discovery=%v", discovered)
			}
			metric := discovered[0]
			if metric["{#METRIC_ID}"] != "1.3.6.1.2.1.1.3.0" || metric["{#VALUE_JSONPATH}"] != `$["controller-main"].metrics[?(@.labels.oid == "1.3.6.1.2.1.1.3.0")].value.first()` || !regexp.MustCompile(`^[0-9a-f]+$`).MatchString(metric["{#METRIC_KEY}"].(string)) {
				t.Fatalf("numeric OID metric=%v", metric)
			}
		default:
			t.Fatalf("unexpected discovery key %q", rule.Key)
		}
	}
}

// TestMasterJavaScriptRejectsInvalidPayloads verifies HTTP 200 alone cannot keep monitoring supported.
func TestMasterJavaScriptRejectsInvalidPayloads(t *testing.T) {
	node, err := exec.LookPath("node")
	if err != nil {
		t.Skip("node is not installed")
	}
	data, err := os.ReadFile("template_homeauthmonitorgw.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var document templateDocument
	if err := yaml.Unmarshal(data, &document); err != nil {
		t.Fatal(err)
	}
	script := "const value = process.argv[1]; function transform() {\n" + document.Export.Templates[0].Items[0].Preprocessing[0].Parameters[0] + "\n} process.stdout.write(transform());"
	valid := `{"source-one":{"driver":"nut","available":false,"stale":true,"last_success":"0001-01-01T00:00:00Z","metrics":[]}}`
	output, err := exec.Command(node, "-e", script, valid).CombinedOutput()
	if err != nil || string(output) != valid {
		t.Fatalf("valid payload: %v output=%q", err, output)
	}
	invalid := []string{
		`not JSON`,
		`[]`,
		`{"bad/source":{"driver":"nut","available":true,"stale":false,"last_success":"x","metrics":[]}}`,
		`{"source-one":{"driver":"nut","available":"yes","stale":false,"last_success":"2026-10-04T00:00:00Z","metrics":[]}}`,
		`{"source-one":{"driver":"nut","available":true,"stale":false,"last_success":"not-a-time","metrics":[]}}`,
		`{"source-one":{"driver":"nut","available":true,"stale":false,"last_success":"2026-10-04T00:00:00Z","metrics":[{"name":"bad-time","value":1,"value_type":"number","timestamp":"not-a-time"}]}}`,
		`{"source-one":{"driver":"nut","available":true,"stale":false,"last_success":"2026-10-04T00:00:00Z","metrics":[{"name":"missing-fields"}]}}`,
	}
	for _, payload := range invalid {
		if output, err := exec.Command(node, "-e", script, payload).CombinedOutput(); err == nil {
			t.Fatalf("accepted payload %q with output %q", payload, output)
		}
	}
}

// TestLastSuccessJavaScriptHandlesNeverSuccessfulSources verifies zero time has a supported sentinel.
func TestLastSuccessJavaScriptHandlesNeverSuccessfulSources(t *testing.T) {
	node, err := exec.LookPath("node")
	if err != nil {
		t.Skip("node is not installed")
	}
	data, err := os.ReadFile("template_homeauthmonitorgw.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var document templateDocument
	if err := yaml.Unmarshal(data, &document); err != nil {
		t.Fatal(err)
	}
	var scriptBody string
	for _, rule := range document.Export.Templates[0].DiscoveryRules {
		for _, prototype := range rule.ItemPrototypes {
			if strings.HasPrefix(prototype.Key, "automation.gateway.source.last_success[") && len(prototype.Preprocessing) == 2 {
				scriptBody = prototype.Preprocessing[1].Parameters[0]
			}
		}
	}
	if scriptBody == "" {
		t.Fatal("last_success JavaScript preprocessing not found")
	}
	script := "const value = process.argv[1]; function transform() {\n" + scriptBody + "\n} process.stdout.write(String(transform()));"
	for input, expected := range map[string]string{
		"0001-01-01T00:00:00Z": "0",
		"2026-10-04T00:00:00Z": "1791072000",
	} {
		output, err := exec.Command(node, "-e", script, input).CombinedOutput()
		if err != nil || string(output) != expected {
			t.Fatalf("input=%q error=%v output=%q", input, err, output)
		}
	}
	if output, err := exec.Command(node, "-e", script, "invalid").CombinedOutput(); err == nil {
		t.Fatalf("invalid timestamp accepted with output %q", output)
	}
}

// TestDeviceDashboardsExposeStableHumanReadableKPIs verifies both device views use stable core items while LLD retains detail metrics.
func TestDeviceDashboardsExposeStableHumanReadableKPIs(t *testing.T) {
	data, err := os.ReadFile("template_homeauthmonitorgw.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var document templateDocument
	if err := yaml.Unmarshal(data, &document); err != nil {
		t.Fatal(err)
	}
	template := document.Export.Templates[0]
	dashboards := map[string]int{}
	for _, dashboard := range template.Dashboards {
		widgets := 0
		for _, page := range dashboard.Pages {
			widgets += len(page.Widgets)
		}
		dashboards[dashboard.Name] = widgets
	}
	if dashboards["WAGO 750-880"] < 8 || dashboards["Phoenix Contact UPS"] < 7 {
		t.Fatalf("dashboards=%v", dashboards)
	}
	items := map[string]struct{ valueType, units, valueMap string }{}
	for _, item := range template.Items {
		items[item.Key] = struct{ valueType, units, valueMap string }{item.ValueType, item.Units, item.ValueMap.Name}
	}
	if item := items["automation.gateway.wago.uptime"]; item.valueType != "FLOAT" || item.units != "uptime" {
		t.Fatalf("WAGO uptime=%+v", item)
	}
	if item := items["automation.gateway.wago.rtc_battery"]; item.valueMap != "WAGO RTC battery status" {
		t.Fatalf("RTC item=%+v", item)
	}
	if item := items["automation.gateway.phoenix.status"]; item.valueMap != "NUT UPS status" {
		t.Fatalf("UPS status item=%+v", item)
	}
	valueMaps := map[string]bool{}
	for _, valueMap := range template.ValueMaps {
		valueMaps[valueMap.Name] = true
	}
	if !valueMaps["WAGO RTC battery status"] || !valueMaps["NUT UPS status"] {
		t.Fatalf("value maps=%v", valueMaps)
	}
}

// TestDeviceHealthJavaScriptScoresCollectorsIndependently executes both static health transforms.
func TestDeviceHealthJavaScriptScoresCollectorsIndependently(t *testing.T) {
	node, err := exec.LookPath("node")
	if err != nil {
		t.Skip("node is not installed")
	}
	data, err := os.ReadFile("template_homeauthmonitorgw.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var document templateDocument
	if err := yaml.Unmarshal(data, &document); err != nil {
		t.Fatal(err)
	}
	tests := []struct {
		key, source string
		want        string
	}{
		{"automation.gateway.wago.health", `{"available":true,"stale":false,"metrics":[{"value":0,"labels":{"oid":"1.3.6.1.4.1.13576.10.1.20.1.0"}},{"value":0,"labels":{"oid":"1.3.6.1.4.1.13576.10.1.20.2.0"}},{"value":"Coupler running, OK","labels":{"oid":"1.3.6.1.4.1.13576.10.1.20.4.0"}},{"value":0,"labels":{"oid":"1.3.6.1.4.1.13576.10.1.11.5.0"}}]}`, "1"},
		{"automation.gateway.wago.health", `{"available":true,"stale":false,"metrics":[{"value":7,"labels":{"oid":"1.3.6.1.4.1.13576.10.1.20.2.0"}}]}`, "3"},
		{"automation.gateway.wago.health", `{"available":true,"stale":false,"metrics":[{"value":"Coupler running, OK","labels":{"oid":"1.3.6.1.4.1.13576.10.1.20.4.0"}}]}`, "2"},
		{"automation.gateway.phoenix.health", `{"available":true,"stale":false,"metrics":[{"name":"ups.status","value":"OL"},{"name":"battery.charge","value":100},{"name":"battery.temperature","value":28}]}`, "1"},
		{"automation.gateway.phoenix.health", `{"available":true,"stale":false,"metrics":[{"name":"ups.status","value":"OB LB"},{"name":"battery.charge","value":10}]}`, "3"},
		{"automation.gateway.phoenix.health", `{"available":true,"stale":false,"metrics":[{"name":"ups.status","value":"OL"}]}`, "2"},
	}
	for _, test := range tests {
		var scriptBody string
		for _, item := range document.Export.Templates[0].Items {
			if item.Key != test.key {
				continue
			}
			for _, preprocessing := range item.Preprocessing {
				if preprocessing.Type == "JAVASCRIPT" {
					scriptBody = preprocessing.Parameters[0]
				}
			}
		}
		if scriptBody == "" {
			t.Fatalf("JavaScript not found for %q", test.key)
		}
		scriptBody = strings.NewReplacer(
			"{$PHOENIX_BATTERY_CRITICAL}", "20",
			"{$PHOENIX_BATTERY_WARNING}", "50",
			"{$PHOENIX_TEMPERATURE_CRITICAL}", "55",
			"{$PHOENIX_TEMPERATURE_WARNING}", "45",
		).Replace(scriptBody)
		script := "const value = process.argv[1]; function transform() {\n" + scriptBody + "\n} process.stdout.write(String(transform()));"
		output, err := exec.Command(node, "-e", script, test.source).CombinedOutput()
		if err != nil || string(output) != test.want {
			t.Fatalf("key=%q want=%q error=%v output=%q", test.key, test.want, err, output)
		}
	}
}
