// File: cmd/mib2json/main.go
// Purpose: Provide an offline, explicitly selected Net-SNMP MIB-to-JSON conversion command.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package main

import (
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/tseiman/HomeAuthMonitorGW/internal/metrics"
	"github.com/tseiman/HomeAuthMonitorGW/internal/mibconvert"
)

var (
	version   = "dev"
	commit    = "unknown"
	buildTime = "unknown"
)

type stringList []string

// String renders repeated flag values for diagnostics.
func (values *stringList) String() string { return fmt.Sprint([]string(*values)) }

// Set appends one non-empty repeated flag value.
func (values *stringList) Set(value string) error {
	if value == "" {
		return errors.New("value must not be empty")
	}
	*values = append(*values, value)
	return nil
}

type commandRunner struct {
	path string
}

// Run executes snmptranslate directly without a shell and returns bounded diagnostics on failure.
func (runner commandRunner) Run(ctx context.Context, args ...string) (string, error) {
	command := exec.CommandContext(ctx, runner.path, args...)
	output, err := command.CombinedOutput()
	if err == nil {
		return string(output), nil
	}
	diagnostic := strings.TrimSpace(string(output))
	if len(diagnostic) > 4096 {
		diagnostic = diagnostic[:4096] + "..."
	}
	if diagnostic == "" {
		return "", err
	}
	return "", fmt.Errorf("%w: %s", err, diagnostic)
}

// main runs the converter with process arguments and streams.
func main() { os.Exit(run(os.Args[1:], os.Stdout, os.Stderr, nil)) }

// run parses the command line, performs conversion, and returns a stable process exit code.
func run(args []string, stdout, stderr io.Writer, runner mibconvert.Runner) int {
	var directories, objects stringList
	fs := flag.NewFlagSet("mib2json", flag.ContinueOnError)
	fs.SetOutput(stderr)
	module := fs.String("module", "", "MIB module name")
	fs.Var(&directories, "mib-dir", "MIB search directory; repeat to include dependencies")
	fs.Var(&objects, "object", "approved object name; repeat for each exported object")
	output := fs.String("output", "-", "output JSON path, or - for stdout")
	translator := fs.String("snmptranslate", "snmptranslate", "snmptranslate executable path")
	showVersion := fs.Bool("version", false, "print version and exit")
	if err := fs.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return 0
		}
		return 2
	}
	if fs.NArg() != 0 {
		fmt.Fprintln(stderr, "unexpected positional arguments")
		return 2
	}
	if *showVersion {
		fmt.Fprintf(stdout, "mib2json %s (commit %s, built %s)\n", version, commit, buildTime)
		return 0
	}
	if *module == "" || len(directories) == 0 || len(objects) == 0 || *output == "" || *translator == "" {
		fmt.Fprintln(stderr, "--module, at least one --mib-dir, and at least one --object are required; output and executable paths must not be empty")
		return 2
	}
	if runner == nil {
		runner = commandRunner{path: *translator}
	}
	definitions, err := mibconvert.Convert(context.Background(), runner, mibconvert.Options{
		Module: *module, MIBDirs: append([]string(nil), directories...), Objects: append([]string(nil), objects...),
	})
	if err != nil {
		fmt.Fprintf(stderr, "conversion failed: %v\n", err)
		return 1
	}
	if err := writeDefinitions(*output, stdout, definitions); err != nil {
		fmt.Fprintf(stderr, "write output: %v\n", err)
		return 1
	}
	return 0
}

// writeDefinitions emits stable indented JSON to stdout or atomically replaces a regular output path.
func writeDefinitions(path string, stdout io.Writer, definitions []metrics.Definition) error {
	data, err := json.MarshalIndent(definitions, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	if path == "-" {
		_, err = stdout.Write(data)
		return err
	}
	directory := filepath.Dir(path)
	mode := os.FileMode(0o644)
	if info, statErr := os.Lstat(path); statErr == nil {
		if !info.Mode().IsRegular() {
			return fmt.Errorf("existing output is not a regular file")
		}
		mode = info.Mode().Perm()
	} else if !errors.Is(statErr, os.ErrNotExist) {
		return statErr
	}
	temporary, err := os.CreateTemp(directory, ".mib2json-*")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(mode); err != nil {
		temporary.Close()
		return err
	}
	if _, err := temporary.Write(data); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Sync(); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryPath, path)
}
