// File: cmd/mib2json/main_test.go
// Purpose: Verify the offline MIB conversion command interface and JSON output.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	snmpdriver "github.com/tseiman/HomeAuthMonitorGW/internal/drivers/snmp"
	"github.com/tseiman/HomeAuthMonitorGW/internal/metrics"
)

type cannedRunner struct{}

// Run returns deterministic outputs for one selected test object.
func (cannedRunner) Run(_ context.Context, args ...string) (string, error) {
	joined := strings.Join(args, " ")
	switch {
	case strings.Contains(joined, " -On TEST-MIB::temperature"):
		return ".1.3.6.1.4.1.999.2\n", nil
	case strings.Contains(joined, " -Td TEST-MIB::temperature"):
		return "temperature OBJECT-TYPE\n  SYNTAX Integer32\n  UNITS \"degrees Celsius\"\n  DESCRIPTION \"Measured temperature\"\n::= { objects 2 }\n", nil
	case strings.HasSuffix(joined, " -Tz"):
		return "\"temperature\"	\"1.3.6.1.4.1.999.2\"\n", nil
	default:
		return "", errors.New("unexpected command")
	}
}

// TestCommandRunnerRejectsTranslatorDiagnostics verifies missing-import warnings cannot look like success.
func TestCommandRunnerRejectsTranslatorDiagnostics(t *testing.T) {
	tool := filepath.Join(t.TempDir(), "snmptranslate")
	script := "#!/bin/sh\nprintf '%s\\n' '\"temperature\"  \"1.3.6.1.4.1.999.2\"'\nprintf '%s\\n' 'Cannot find module (SNMPv2-SMI)' >&2\n"
	if err := os.WriteFile(tool, []byte(script), 0o700); err != nil {
		t.Fatal(err)
	}

	_, err := (commandRunner{path: tool}).Run(context.Background(), "-Tz")
	if err == nil || !strings.Contains(err.Error(), "Cannot find module (SNMPv2-SMI)") {
		t.Fatalf("error=%v", err)
	}
}

// TestCommandRunnerReturnsCleanStdout verifies diagnostics handling preserves valid translator output.
func TestCommandRunnerReturnsCleanStdout(t *testing.T) {
	tool := filepath.Join(t.TempDir(), "snmptranslate")
	if err := os.WriteFile(tool, []byte("#!/bin/sh\nprintf 'symbol-output\\n'\n"), 0o700); err != nil {
		t.Fatal(err)
	}

	output, err := (commandRunner{path: tool}).Run(context.Background(), "-Tz")
	if err != nil || output != "symbol-output\n" {
		t.Fatalf("output=%q error=%v", output, err)
	}
}

// TestCommandRunnerReturnsSilentProcessFailure verifies an empty diagnostic cannot hide the exit error.
func TestCommandRunnerReturnsSilentProcessFailure(t *testing.T) {
	tool := filepath.Join(t.TempDir(), "snmptranslate")
	if err := os.WriteFile(tool, []byte("#!/bin/sh\nexit 7\n"), 0o700); err != nil {
		t.Fatal(err)
	}

	if _, err := (commandRunner{path: tool}).Run(context.Background(), "-Tz"); err == nil {
		t.Fatal("silent process failure returned nil error")
	}
}

// TestRunWritesRuntimeCompatibleJSON verifies required flags and stdout output.
func TestRunWritesRuntimeCompatibleJSON(t *testing.T) {
	var stdout, stderr bytes.Buffer
	code := run([]string{"--module", "TEST-MIB", "--mib-dir", "/mibs", "--object", "temperature", "--output", "-"}, &stdout, &stderr, cannedRunner{})
	if code != 0 {
		t.Fatalf("code=%d stderr=%q", code, stderr.String())
	}
	var definitions []metrics.Definition
	if err := json.Unmarshal(stdout.Bytes(), &definitions); err != nil {
		t.Fatalf("JSON: %v output=%q", err, stdout.String())
	}
	if len(definitions) != 1 || definitions[0].OID != "1.3.6.1.4.1.999.2" || definitions[0].Name != "temperature" {
		t.Fatalf("definitions=%+v", definitions)
	}
}

// TestRunListsSymbolsWithoutPreselectedObjects verifies operators can discover names before choosing metadata.
func TestRunListsSymbolsWithoutPreselectedObjects(t *testing.T) {
	var stdout, stderr bytes.Buffer
	code := run([]string{"--module", "TEST-MIB", "--mib-dir", "/mibs", "--list-symbols"}, &stdout, &stderr, cannedRunner{})
	if code != 0 {
		t.Fatalf("code=%d stderr=%q", code, stderr.String())
	}
	if !strings.Contains(stdout.String(), "temperature") || !strings.Contains(stdout.String(), "1.3.6.1.4.1.999.2") {
		t.Fatalf("stdout=%q", stdout.String())
	}
}

// TestRunRejectsObjectsInSymbolListingMode keeps discovery and conversion unambiguous.
func TestRunRejectsObjectsInSymbolListingMode(t *testing.T) {
	var stdout, stderr bytes.Buffer
	code := run([]string{"--module", "TEST-MIB", "--mib-dir", "/mibs", "--list-symbols", "--object", "temperature"}, &stdout, &stderr, cannedRunner{})
	if code != 2 || !strings.Contains(stderr.String(), "does not accept --object") {
		t.Fatalf("code=%d stderr=%q", code, stderr.String())
	}
}

// TestRunAtomicallyWritesLoadableMetadata verifies file output is accepted by the production metadata loader.
func TestRunAtomicallyWritesLoadableMetadata(t *testing.T) {
	path := filepath.Join(t.TempDir(), "metadata.json")
	var stdout, stderr bytes.Buffer
	code := run([]string{"--module", "TEST-MIB", "--mib-dir", "/mibs", "--object", "temperature", "--output", path}, &stdout, &stderr, cannedRunner{})
	if code != 0 {
		t.Fatalf("code=%d stderr=%q", code, stderr.String())
	}
	metadata, err := snmpdriver.LoadMetadata(path)
	if err != nil {
		t.Fatalf("LoadMetadata: %v", err)
	}
	if metadata["1.3.6.1.4.1.999.2"].Name != "temperature" {
		t.Fatalf("metadata=%+v", metadata)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o644 {
		t.Fatalf("new file mode=%#o", info.Mode().Perm())
	}
	if err := os.Chmod(path, 0o600); err != nil {
		t.Fatal(err)
	}
	stdout.Reset()
	stderr.Reset()
	if code := run([]string{"--module", "TEST-MIB", "--mib-dir", "/mibs", "--object", "temperature", "--output", path}, &stdout, &stderr, cannedRunner{}); code != 0 {
		t.Fatalf("replacement code=%d stderr=%q", code, stderr.String())
	}
	info, err = os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o600 {
		t.Fatalf("replacement mode=%#o", info.Mode().Perm())
	}
}

// TestRunRejectsIncompleteInvocation verifies conversion cannot silently use ambient defaults.
func TestRunRejectsIncompleteInvocation(t *testing.T) {
	var stdout, stderr bytes.Buffer
	if code := run([]string{"--module", "TEST-MIB"}, &stdout, &stderr, cannedRunner{}); code != 2 {
		t.Fatalf("code=%d stderr=%q", code, stderr.String())
	}
}

// TestRunVersionDoesNotInvokeConverter verifies version reporting is independent of local MIB tooling.
func TestRunVersionDoesNotInvokeConverter(t *testing.T) {
	old := version
	version = "1.2.3-test"
	defer func() { version = old }()
	var stdout, stderr bytes.Buffer
	if code := run([]string{"--version"}, &stdout, &stderr, nil); code != 0 || !strings.Contains(stdout.String(), "1.2.3-test") {
		t.Fatalf("code=%d stdout=%q stderr=%q", code, stdout.String(), stderr.String())
	}
}
