// File: internal/app/app.go
// Purpose: Assemble collectors and atomically manage coherent runtime generations.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package app

import (
	"context"
	"crypto/sha256"
	"crypto/tls"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/netip"
	"sync"
	"sync/atomic"
	"time"

	"github.com/tseiman/HomeAuthMonitorGW/internal/cache"
	"github.com/tseiman/HomeAuthMonitorGW/internal/config"
	"github.com/tseiman/HomeAuthMonitorGW/internal/drivers"
	"github.com/tseiman/HomeAuthMonitorGW/internal/drivers/nut"
	snmpdriver "github.com/tseiman/HomeAuthMonitorGW/internal/drivers/snmp"
	"github.com/tseiman/HomeAuthMonitorGW/internal/tlsreload"
)

type sourceSpec struct {
	name, driver                      string
	interval, stale, discoveryTimeout time.Duration
	collector                         drivers.Collector
	discoverer                        drivers.Discoverer
	identity                          [sha256.Size]byte
}

type candidate struct {
	cfg   config.Config
	cert  *tls.Certificate
	specs []sourceSpec
}

type generation struct {
	cfg            config.Config
	cert           *tls.Certificate
	store          *cache.Store
	tokenDigests   [][sha256.Size]byte
	allowedClients []netip.Prefix
	identities     map[string][sha256.Size]byte
}

// RuntimeView is one coherent cache and authorization-policy generation for an HTTP request.
type RuntimeView struct {
	Store               *cache.Store
	TokenDigests        [][sha256.Size]byte
	AllowedClients      []netip.Prefix
	CertificateNotAfter time.Time
}

// Runtime owns the active generation and collector workers.
type Runtime struct {
	paths  []string
	logger *slog.Logger
	active atomic.Pointer[generation]
	mu     sync.Mutex
	cancel context.CancelFunc
	wg     sync.WaitGroup
	closed bool
	done   chan struct{}
}

// Check prepares the configuration at path without starting collectors and returns any validation or referenced-file error.
func Check(path string) error {
	return CheckFiles([]string{path})

}

// CheckFiles prepares the ordered configuration stack without starting collectors.
func CheckFiles(paths []string) error {
	_, err := prepare(paths)
	return err
}

// New prepares path, creates a runtime, atomically publishes its first generation, and starts active collectors.
func New(path string, logger *slog.Logger) (*Runtime, error) {
	return NewFiles([]string{path}, logger)
}

// NewFiles prepares ordered configuration layers and starts one runtime from their merged result.
func NewFiles(paths []string, logger *slog.Logger) (*Runtime, error) {
	cand, err := prepare(paths)
	if err != nil {
		return nil, err
	}
	runtime := &Runtime{paths: append([]string(nil), paths...), logger: logger}
	active := buildGeneration(cand.cfg, cand.cert, cand.specs, nil)
	runtime.active.Store(active)
	runtime.start(cand.specs, active.store)
	return runtime, nil
}

// prepare loads path and builds a complete inactive candidate before active runtime state can change.
func prepare(paths []string) (candidate, error) {
	cfg, err := config.LoadFiles(paths, true)
	if err != nil {
		return candidate{}, err
	}
	cert, err := tlsreload.Load(cfg.Server.Certificate, cfg.Server.PrivateKey)
	if err != nil {
		return candidate{}, err
	}
	specs, err := prepareSources(cfg)
	if err != nil {
		return candidate{}, err
	}
	return candidate{cfg: cfg, cert: cert, specs: specs}, nil
}

// prepareSources translates every active generic source into a statically linked collector specification.
func prepareSources(cfg config.Config) ([]sourceSpec, error) {
	var out []sourceSpec
	for _, source := range cfg.Sources {
		if !source.Enabled {
			continue
		}
		switch source.Driver {
		case "nut":
			collector := nut.Collector{Client: nut.Client{Address: source.NUT.Server, Timeout: source.Timeout.Duration}, UPS: source.NUT.UPS}
			out = append(out, sourceSpec{name: source.Name, driver: "nut", interval: source.PollInterval.Duration, stale: source.StaleAfter.Duration, collector: collector, identity: sourceIdentity(source, nil)})
		case "snmp":
			meta, err := snmpdriver.LoadMetadata(source.SNMP.MetadataFile)
			if err != nil {
				return nil, fmt.Errorf("source %q metadata: %w", source.Name, err)
			}
			secrets := cfg.Secrets.Sources[source.Name]
			client, err := snmpdriver.NewGoSNMP(source.SNMP.Address, source.SNMP.Port, source.SNMP.Security.Username, secrets.SNMPAuthPassphrase, secrets.SNMPPrivPassphrase, source.Timeout.Duration)
			if err != nil {
				return nil, fmt.Errorf("source %q: %w", source.Name, err)
			}
			client.MaxOids = source.SNMP.MaxOIDsPerRequest
			reader := &snmpdriver.GoSNMPReader{Template: client}
			collector := &snmpdriver.Collector{Reader: reader, OIDs: source.SNMP.OIDs, Roots: source.SNMP.Discovery.RootOIDs, MaxDiscoveryObjects: source.SNMP.Discovery.MaxObjects, Metadata: meta}
			var discoverer drivers.Discoverer
			if source.SNMP.Discovery.Enabled {
				discoverer = collector
			}
			out = append(out, sourceSpec{name: source.Name, driver: "snmp", interval: source.PollInterval.Duration, stale: source.StaleAfter.Duration, discoveryTimeout: source.SNMP.Discovery.Timeout.Duration, collector: collector, discoverer: discoverer, identity: sourceIdentity(source, meta)})
		default:
			return nil, fmt.Errorf("source %q has unsupported driver %q", source.Name, source.Driver)
		}
	}
	return out, nil
}

// sourceIdentity hashes non-secret source configuration and parsed metadata to constrain snapshot carryover.
func sourceIdentity(source config.Source, metadata snmpdriver.Metadata) [sha256.Size]byte {
	encoded, err := json.Marshal(struct {
		Source   config.Source
		Metadata snmpdriver.Metadata
	}{Source: source, Metadata: metadata})
	if err != nil {
		panic(fmt.Sprintf("marshal validated source identity: %v", err))
	}
	return sha256.Sum256(encoded)
}

// buildGeneration pre-registers every source, carries compatible snapshots forward, and hashes all bearer tokens.
func buildGeneration(cfg config.Config, cert *tls.Certificate, specs []sourceSpec, previous *generation) *generation {
	store := cache.New(time.Now)
	identities := make(map[string][sha256.Size]byte, len(specs))
	for _, spec := range specs {
		identities[spec.name] = spec.identity
		store.Register(spec.name, spec.driver, spec.stale)
		if previous != nil {
			if previousIdentity, compatible := previous.identities[spec.name]; compatible && previousIdentity == spec.identity {
				if snapshot, ok := previous.store.Snapshot(spec.name); ok {
					store.Restore(spec.name, snapshot)
				}
			}
		}
	}
	digests := make([][sha256.Size]byte, len(cfg.Secrets.BearerTokens))
	for index, token := range cfg.Secrets.BearerTokens {
		digests[index] = sha256.Sum256([]byte(token))
	}
	return &generation{
		cfg: cfg, cert: cert, store: store, tokenDigests: digests,
		allowedClients: append([]netip.Prefix(nil), cfg.Secrets.AllowedClients...),
		identities:     identities,
	}
}

// Reload prepares and atomically commits one complete cache, config, and authorization generation.
func (r *Runtime) Reload() error {
	cand, err := prepare(r.paths)
	if err != nil {
		return err
	}
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.closed {
		return errors.New("runtime is closed")
	}
	old := r.active.Load()
	if old != nil && !reloadCompatible(old.cfg, cand.cfg) {
		return errors.New("server listener, timeouts, and header limit require restart")
	}
	if r.cancel != nil {
		r.cancel()
		r.cancel = nil
	}
	next := buildGeneration(cand.cfg, cand.cert, cand.specs, old)
	// This single store prevents new credentials from ever observing an old or partially registered cache.
	r.active.Store(next)
	r.startLocked(cand.specs, next.store)
	return nil
}

// reloadCompatible compares settings that require rebuilding the HTTP server.
func reloadCompatible(a, b config.Config) bool {
	return a.Server.Listen == b.Server.Listen &&
		a.Server.ReadTimeout == b.Server.ReadTimeout &&
		a.Server.WriteTimeout == b.Server.WriteTimeout &&
		a.Server.IdleTimeout == b.Server.IdleTimeout &&
		a.Server.ShutdownTimeout == b.Server.ShutdownTimeout &&
		a.Server.MaxHeaderBytes == b.Server.MaxHeaderBytes
}

// start acquires the runtime lock and starts the supplied collectors against store.
func (r *Runtime) start(specs []sourceSpec, store *cache.Store) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.startLocked(specs, store)
}

// startLocked launches polling and optional discovery against an already complete generation store.
func (r *Runtime) startLocked(specs []sourceSpec, store *cache.Store) {
	ctx, cancel := context.WithCancel(context.Background())
	r.cancel = cancel
	for _, spec := range specs {
		r.wg.Add(1)
		go func(spec sourceSpec) {
			defer r.wg.Done()
			drivers.Run(ctx, spec.name, spec.interval, spec.collector, store, r.logger)
		}(spec)
		if spec.discoverer != nil {
			r.wg.Add(1)
			go func(spec sourceSpec) {
				defer r.wg.Done()
				discoveryContext, cancel := context.WithTimeout(ctx, spec.discoveryTimeout)
				defer cancel()
				definitions, err := spec.discoverer.Discover(discoveryContext)
				if err != nil {
					if r.logger != nil {
						r.logger.Warn("source discovery failed", "source", spec.name)
					}
					return
				}
				store.SetDiscovery(spec.name, definitions)
			}(spec)
		}
	}
}

// Close stops all collector and discovery workers and waits for their completion.
func (r *Runtime) Close() {
	_ = r.CloseContext(context.Background())
}

// CloseContext cancels every collector generation and waits only until all workers exit or ctx expires.
func (r *Runtime) CloseContext(ctx context.Context) error {
	r.mu.Lock()
	if !r.closed {
		r.closed = true
		if r.cancel != nil {
			r.cancel()
			r.cancel = nil
		}
		r.done = make(chan struct{})
		done := r.done
		go func() {
			r.wg.Wait()
			close(done)
		}()
	}
	done := r.done
	r.mu.Unlock()
	select {
	case <-done:
		return nil
	case <-ctx.Done():
		return ctx.Err()
	}
}

// View returns one coherent active generation with detached policy slices and its generation-specific store.
func (r *Runtime) View() RuntimeView {
	active := r.active.Load()
	if active == nil {
		return RuntimeView{}
	}
	return RuntimeView{
		Store: active.store, TokenDigests: append([][sha256.Size]byte(nil), active.tokenDigests...),
		AllowedClients:      append([]netip.Prefix(nil), active.allowedClients...),
		CertificateNotAfter: active.cert.Leaf.NotAfter,
	}
}

// GetCertificate returns the certificate from the same active generation used for configuration and policy.
func (r *Runtime) GetCertificate(*tls.ClientHelloInfo) (*tls.Certificate, error) {
	active := r.active.Load()
	if active == nil || active.cert == nil {
		return nil, errors.New("no active TLS certificate")
	}
	return active.cert, nil
}

// CertificateNotAfter returns the active generation's leaf expiration time or zero when unavailable.
func (r *Runtime) CertificateNotAfter() time.Time {
	active := r.active.Load()
	if active == nil || active.cert == nil || active.cert.Leaf == nil {
		return time.Time{}
	}
	return active.cert.Leaf.NotAfter
}

// Config returns the currently active configuration, or a zero value when none is published.
func (r *Runtime) Config() config.Config {
	active := r.active.Load()
	if active == nil {
		return config.Config{}
	}
	return active.cfg
}

// ValidateActive returns nil when a generation is active and an error otherwise.
func (r *Runtime) ValidateActive() error {
	if r.active.Load() == nil {
		return fmt.Errorf("no active configuration")
	}
	return nil
}
