// File: internal/app/app_test.go
// Purpose: Verify runtime reload commits and last-known-good preservation.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package app

import (
	"context"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"errors"
	"math/big"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/tseiman/HomeAuthMonitorGW/internal/config"
	"github.com/tseiman/HomeAuthMonitorGW/internal/metrics"
)

// pair creates a self-signed certificate and key named n in d for serial, returning their paths; unrecoverable setup failures are reported through t.
func pair(t *testing.T, d, n string, serial int64) (string, string) {
	k, _ := rsa.GenerateKey(rand.Reader, 2048)
	x := x509.Certificate{SerialNumber: big.NewInt(serial), Subject: pkix.Name{CommonName: "test"}, NotBefore: time.Now().Add(-time.Hour), NotAfter: time.Now().Add(time.Hour)}
	der, _ := x509.CreateCertificate(rand.Reader, &x, &x, &k.PublicKey, k)
	c, kp := filepath.Join(d, n+".crt"), filepath.Join(d, n+".key")
	os.WriteFile(c, pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}), 0o600)
	os.WriteFile(kp, pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(k)}), 0o600)
	return c, kp
}

// writeConfig writes a minimal gateway configuration to path using the supplied certificate, key, and token paths, and reports write errors through t.
func writeConfig(t *testing.T, path, cert, key, token string) {
	s := "server:\n  listen: '127.0.0.1:8443'\n  certificate: '" + cert + "'\n  private_key: '" + key + "'\nauthentication:\n  bearer_token_files:\n    - '" + token + "'\n  allowed_clients:\n    - '127.0.0.1'\nsources: []\n"
	if err := os.WriteFile(path, []byte(s), 0o600); err != nil {
		t.Fatal(err)
	}
}

// TestReloadCommitsValidCandidate verifies that a valid reload publishes the candidate token and certificate.
func TestReloadCommitsValidCandidate(t *testing.T) {
	d := t.TempDir()
	c1, k1 := pair(t, d, "one", 1)
	token := filepath.Join(d, "token")
	os.WriteFile(token, []byte("first-token-value-0001"), 0o600)
	cfg := filepath.Join(d, "config.yaml")
	writeConfig(t, cfg, c1, k1, token)
	a, err := New(cfg, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer a.Close()
	c2, k2 := pair(t, d, "two", 2)
	os.WriteFile(token, []byte("second-token-value-0002"), 0o600)
	writeConfig(t, cfg, c2, k2, token)
	if err := a.Reload(); err != nil {
		t.Fatal(err)
	}
	if got := a.Config().Secrets.BearerTokens; len(got) != 1 || got[0] != "second-token-value-0002" {
		t.Fatalf("tokens=%q", got)
	}
	cert, _ := a.GetCertificate(nil)
	x, _ := x509.ParseCertificate(cert.Certificate[0])
	if x.SerialNumber.Int64() != 2 {
		t.Fatalf("serial=%s", x.SerialNumber)
	}
}

// TestReloadFailurePreservesActiveState verifies that an invalid candidate leaves the active token unchanged.
func TestReloadFailurePreservesActiveState(t *testing.T) {
	d := t.TempDir()
	c, k := pair(t, d, "one", 1)
	token := filepath.Join(d, "token")
	os.WriteFile(token, []byte("first-token-value-0001"), 0o600)
	cfg := filepath.Join(d, "config.yaml")
	writeConfig(t, cfg, c, k, token)
	a, err := New(cfg, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer a.Close()
	os.WriteFile(token, []byte("changed-token-value-0002"), 0o600)
	os.WriteFile(cfg, []byte("server:\n  unknown: true\n"), 0o600)
	if err := a.Reload(); err == nil {
		t.Fatal("expected error")
	}
	if got := a.Config().Secrets.BearerTokens; len(got) != 1 || got[0] != "first-token-value-0001" {
		t.Fatalf("active tokens changed: %q", got)
	}
}

// TestPrepareSourcesSkipsDisabledAndSupportsNUTOnly verifies disabled entries never reach driver setup.
func TestPrepareSourcesSkipsDisabledAndSupportsNUTOnly(t *testing.T) {
	cfg := config.Config{Sources: []config.Source{
		{Name: "ignored", Driver: "snmp", Enabled: false, SNMP: &config.SNMPSource{MetadataFile: "/does/not/exist"}},
		{Name: "ups-main", Driver: "nut", Enabled: true, PollInterval: config.Duration{Duration: time.Second}, StaleAfter: config.Duration{Duration: 2 * time.Second}, Timeout: config.Duration{Duration: time.Second}, NUT: &config.NUTSource{Server: "127.0.0.1:3493", UPS: "main"}},
	}}
	specs, err := prepareSources(cfg)
	if err != nil {
		t.Fatalf("prepareSources: %v", err)
	}
	if len(specs) != 1 || specs[0].name != "ups-main" || specs[0].driver != "nut" {
		t.Fatalf("specs=%+v", specs)
	}
}

// TestRuntimeOmitsDisabledSources verifies disabled entries create no worker-facing cache or API state.
func TestRuntimeOmitsDisabledSources(t *testing.T) {
	d := t.TempDir()
	certificate, key := pair(t, d, "disabled", 3)
	token := filepath.Join(d, "token")
	if err := os.WriteFile(token, []byte("disabled-test-token-value"), 0o600); err != nil {
		t.Fatal(err)
	}
	configuration := filepath.Join(d, "config.yaml")
	body := "server:\n  listen: '127.0.0.1:8443'\n  certificate: '" + certificate + "'\n  private_key: '" + key + "'\nauthentication:\n  bearer_token_files: ['" + token + "']\n  allowed_clients: ['127.0.0.1']\nsources:\n  - enabled: false\n    driver: unsupported\n    snmp:\n      metadata_file: /does/not/exist\n"
	if err := os.WriteFile(configuration, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	runtime, err := New(configuration, nil)
	if err != nil {
		t.Fatalf("New validated a disabled source: %v", err)
	}
	defer runtime.Close()
	if snapshots := runtime.View().Store.All(); len(snapshots) != 0 {
		t.Fatalf("disabled source was registered: %+v", snapshots)
	}
}

// TestCheckFilesUsesEveryOrderedLayer verifies app validation consumes the complete CLI configuration stack.
func TestCheckFilesUsesEveryOrderedLayer(t *testing.T) {
	directory := t.TempDir()
	certificate, key := pair(t, directory, "layers", 4)
	token := filepath.Join(directory, "token")
	if err := os.WriteFile(token, []byte("layer-check-token-value"), 0o600); err != nil {
		t.Fatal(err)
	}
	base := filepath.Join(directory, "base.yaml")
	overlay := filepath.Join(directory, "overlay.yaml")
	body := "server:\n  listen: '127.0.0.1:8443'\n  certificate: '" + certificate + "'\n  private_key: '" + key + "'\nauthentication:\n  bearer_token_files: ['" + token + "']\n  allowed_clients: ['127.0.0.1']\nsources: []\n"
	if err := os.WriteFile(base, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(overlay, []byte("logging:\n  level: debug\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := CheckFiles([]string{base, overlay}); err != nil {
		t.Fatalf("CheckFiles: %v", err)
	}
}

// TestPrepareSourcesSupportsSNMPOnly verifies one SNMP source is prepared without NUT or network access.
func TestPrepareSourcesSupportsSNMPOnly(t *testing.T) {
	cfg := config.Config{
		Sources: []config.Source{{
			Name: "controller-main", Driver: "snmp", Enabled: true,
			PollInterval: config.Duration{Duration: time.Second}, StaleAfter: config.Duration{Duration: 2 * time.Second}, Timeout: config.Duration{Duration: time.Second},
			SNMP: &config.SNMPSource{Address: "192.0.2.10", Port: 161, OIDs: []string{"1.3.6.1.2.1.1.3.0"}, Security: config.SNMPSecurity{Username: "monitor"}},
		}},
		Secrets: config.Secrets{Sources: map[string]config.SourceSecrets{"controller-main": {SNMPAuthPassphrase: "auth-passphrase", SNMPPrivPassphrase: "priv-passphrase"}}},
	}
	specs, err := prepareSources(cfg)
	if err != nil {
		t.Fatalf("prepareSources: %v", err)
	}
	if len(specs) != 1 || specs[0].name != "controller-main" || specs[0].driver != "snmp" {
		t.Fatalf("specs=%+v", specs)
	}
}

// TestBuildGenerationPublishesCompletePolicyAndCompatibleCache verifies atomic-generation preparation.
func TestBuildGenerationPublishesCompletePolicyAndCompatibleCache(t *testing.T) {
	oldConfig := config.Config{Secrets: config.Secrets{BearerTokens: []string{"old-token-value"}}}
	oldSpecs := []sourceSpec{{name: "removed", driver: "nut", stale: time.Minute}, {name: "retained", driver: "nut", stale: time.Minute}}
	oldGeneration := buildGeneration(oldConfig, nil, oldSpecs, nil)
	oldGeneration.store.Success("removed", []metrics.Metric{{Name: "private-old"}}, time.Millisecond)
	oldGeneration.store.Success("retained", []metrics.Metric{{Name: "charge", Value: 80}}, time.Millisecond)

	newConfig := config.Config{Secrets: config.Secrets{BearerTokens: []string{"new-token-value"}}}
	newSpecs := []sourceSpec{{name: "retained", driver: "nut", stale: time.Minute}, {name: "added", driver: "snmp", stale: time.Minute}}
	next := buildGeneration(newConfig, nil, newSpecs, oldGeneration)

	if _, ok := next.store.Snapshot("removed"); ok {
		t.Fatal("removed source leaked into replacement generation")
	}
	retained, ok := next.store.Snapshot("retained")
	if !ok || len(retained.Metrics) != 1 || retained.Metrics[0].Name != "charge" {
		t.Fatalf("compatible snapshot not retained: %+v", retained)
	}
	if all := next.store.All(); len(all) != 2 {
		t.Fatalf("partially registered generation: %+v", all)
	}
	if len(next.tokenDigests) != 1 || next.tokenDigests[0] != sha256.Sum256([]byte("new-token-value")) {
		t.Fatalf("unexpected token digests: %x", next.tokenDigests)
	}
	changed := buildGeneration(newConfig, nil, []sourceSpec{{name: "retained", driver: "nut", stale: time.Minute, identity: sha256.Sum256([]byte("changed target"))}}, oldGeneration)
	changedSnapshot, _ := changed.store.Snapshot("retained")
	if len(changedSnapshot.Metrics) != 0 {
		t.Fatalf("snapshot crossed incompatible source identity: %+v", changedSnapshot)
	}
}

// TestCloseContextHonorsDeadline verifies a non-cooperative worker cannot block process shutdown indefinitely.
func TestCloseContextHonorsDeadline(t *testing.T) {
	runtime := &Runtime{}
	release := make(chan struct{})
	cancelled := make(chan struct{})
	runtime.cancel = func() { close(cancelled) }
	runtime.wg.Add(1)
	go func() {
		defer runtime.wg.Done()
		<-release
	}()
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Millisecond)
	defer cancel()
	started := time.Now()
	err := runtime.CloseContext(ctx)
	if !errors.Is(err, context.DeadlineExceeded) {
		t.Fatalf("CloseContext error=%v", err)
	}
	if time.Since(started) > time.Second {
		t.Fatal("CloseContext ignored deadline")
	}
	select {
	case <-cancelled:
	default:
		t.Fatal("worker context was not cancelled")
	}
	close(release)
	runtime.Close()
}
