// File: internal/app/app_test.go
// Purpose: Verify runtime reload commits and last-known-good preservation.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package app

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"math/big"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// pair creates a self-signed certificate and key named n in d for serial, returning their paths; unrecoverable setup failures are reported through t.
func pair(t *testing.T, d, n string, serial int64) (string, string) {
	k, _ := rsa.GenerateKey(rand.Reader, 2048)
	x := x509.Certificate{SerialNumber: big.NewInt(serial), Subject: pkix.Name{CommonName: "test"}, NotBefore: time.Now().Add(-time.Hour), NotAfter: time.Now().Add(time.Hour)}
	der, _ := x509.CreateCertificate(rand.Reader, &x, &x, &k.PublicKey, k)
	c, kp := filepath.Join(d, n+".crt"), filepath.Join(d, n+".key")
	os.WriteFile(c, pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}), 0o600)
	os.WriteFile(kp, pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(k)}), 0o600)
	return c, kp
}

// writeConfig writes a minimal gateway configuration to path using the supplied certificate, key, and token paths, and reports write errors through t.
func writeConfig(t *testing.T, path, cert, key, token string) {
	s := "server:\n  listen: '127.0.0.1:8443'\n  certificate: '" + cert + "'\n  private_key: '" + key + "'\nauthentication:\n  bearer_token_file: '" + token + "'\n"
	if err := os.WriteFile(path, []byte(s), 0o600); err != nil {
		t.Fatal(err)
	}
}

// TestReloadCommitsValidCandidate verifies that a valid reload publishes the candidate token and certificate.
func TestReloadCommitsValidCandidate(t *testing.T) {
	d := t.TempDir()
	c1, k1 := pair(t, d, "one", 1)
	token := filepath.Join(d, "token")
	os.WriteFile(token, []byte("first-token"), 0o600)
	cfg := filepath.Join(d, "config.yaml")
	writeConfig(t, cfg, c1, k1, token)
	a, err := New(cfg, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer a.Close()
	c2, k2 := pair(t, d, "two", 2)
	os.WriteFile(token, []byte("second-token"), 0o600)
	writeConfig(t, cfg, c2, k2, token)
	if err := a.Reload(); err != nil {
		t.Fatal(err)
	}
	if a.Token() != "second-token" {
		t.Fatalf("token=%q", a.Token())
	}
	cert, _ := a.TLS.GetCertificate(nil)
	x, _ := x509.ParseCertificate(cert.Certificate[0])
	if x.SerialNumber.Int64() != 2 {
		t.Fatalf("serial=%s", x.SerialNumber)
	}
}

// TestReloadFailurePreservesActiveState verifies that an invalid candidate leaves the active token unchanged.
func TestReloadFailurePreservesActiveState(t *testing.T) {
	d := t.TempDir()
	c, k := pair(t, d, "one", 1)
	token := filepath.Join(d, "token")
	os.WriteFile(token, []byte("first-token"), 0o600)
	cfg := filepath.Join(d, "config.yaml")
	writeConfig(t, cfg, c, k, token)
	a, err := New(cfg, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer a.Close()
	os.WriteFile(token, []byte("changed-token"), 0o600)
	os.WriteFile(cfg, []byte("server:\n  unknown: true\n"), 0o600)
	if err := a.Reload(); err == nil {
		t.Fatal("expected error")
	}
	if a.Token() != "first-token" {
		t.Fatalf("active token changed: %q", a.Token())
	}
}
