// File: internal/mibconvert/convert_test.go
// Purpose: Verify deterministic Net-SNMP detail conversion without installed MIB tools or device access.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package mibconvert

import (
	"context"
	"errors"
	"reflect"
	"strings"
	"testing"
)

type fakeRunner struct {
	outputs map[string]string
}

// Run returns one canned snmptranslate response keyed by its exact argument vector.
func (f fakeRunner) Run(_ context.Context, args ...string) (string, error) {
	output, ok := f.outputs[strings.Join(args, "\x00")]
	if !ok {
		return "", errors.New("unexpected command: " + strings.Join(args, " "))
	}
	return output, nil
}

// TestConvertParsesMetadataAndSortsNumericOIDs verifies all runtime metadata fields and deterministic numeric ordering.
func TestConvertParsesMetadataAndSortsNumericOIDs(t *testing.T) {
	prefix := []string{"-M", "/vendor:/dependencies", "-m", "TEST-MIB"}
	key := func(extra ...string) string {
		return strings.Join(append(append([]string(nil), prefix...), extra...), "\x00")
	}
	runner := fakeRunner{outputs: map[string]string{
		key("-On", "TEST-MIB::alarmState"): ".1.3.6.1.4.1.999.10\n",
		key("-Td", "TEST-MIB::alarmState"): `TEST-MIB::alarmState
alarmState OBJECT-TYPE
  -- FROM TEST-MIB
  SYNTAX	INTEGER { normal(1), warning(2), alarm(3) }
  UNITS	"state"
  MAX-ACCESS read-only
  STATUS current
  DESCRIPTION	"Current device
               alarm state"
  REFERENCE	"A reference that must not enter the description"
::= { testObjects 10 }
`,
		key("-On", "TEST-MIB::temperature"): ".1.3.6.1.4.1.999.2\n",
		key("-Td", "TEST-MIB::temperature"): `TEST-MIB::temperature
temperature OBJECT-TYPE
  SYNTAX Integer32 (-40..125)
  UNITS "degrees Celsius"
  MAX-ACCESS read-only
  DESCRIPTION
    "Measured temperature"
::= { testObjects 2 }
`,
	}}

	definitions, err := Convert(context.Background(), runner, Options{
		Module: "TEST-MIB", MIBDirs: []string{"/vendor", "/dependencies"}, Objects: []string{"alarmState", "temperature"},
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(definitions) != 2 || definitions[0].Name != "temperature" || definitions[1].Name != "alarmState" {
		t.Fatalf("definitions=%+v", definitions)
	}
	if definitions[0].OID != "1.3.6.1.4.1.999.2" || definitions[0].Type != "Integer32" || definitions[0].Unit != "degrees Celsius" {
		t.Fatalf("temperature=%+v", definitions[0])
	}
	wantEnum := map[string]string{"1": "normal", "2": "warning", "3": "alarm"}
	if definitions[1].Type != "INTEGER" || definitions[1].Description != "Current device alarm state" || !reflect.DeepEqual(definitions[1].Enum, wantEnum) {
		t.Fatalf("alarm=%+v", definitions[1])
	}
}

// TestConvertRejectsInvalidAndDuplicateSelections verifies shell-free identifiers and bounded unique object selection.
func TestConvertRejectsInvalidAndDuplicateSelections(t *testing.T) {
	for _, options := range []Options{
		{},
		{Module: "BAD;MODULE", MIBDirs: []string{"/mibs"}, Objects: []string{"x"}},
		{Module: "TEST-MIB", MIBDirs: []string{"/mibs"}, Objects: []string{"bad::object"}},
		{Module: "TEST-MIB", MIBDirs: []string{"/mibs"}, Objects: []string{"same", "same"}},
	} {
		if _, err := Convert(context.Background(), fakeRunner{}, options); err == nil {
			t.Fatalf("accepted %+v", options)
		}
	}
}

// TestParseOIDRejectsOutOfRangeComponents verifies numeric ordering never ignores integer overflow.
func TestParseOIDRejectsOutOfRangeComponents(t *testing.T) {
	for _, value := range []string{"1.3.6.4294967296", "1..3", "symbolic.1"} {
		if _, err := parseOID(value); err == nil {
			t.Fatalf("accepted OID %q", value)
		}
	}
}
