// File: internal/mibconvert/convert.go
// Purpose: Convert explicitly selected Net-SNMP MIB objects into deterministic gateway metadata.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package mibconvert

import (
	"context"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/tseiman/HomeAuthMonitorGW/internal/metrics"
)

const maxObjects = 10000

var (
	identifierPattern = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9-]*$`)
	oidPattern        = regexp.MustCompile(`^\.?[0-9]+(?:\.[0-9]+)*$`)
	enumPattern       = regexp.MustCompile(`([A-Za-z][A-Za-z0-9-]*)\s*\(\s*(-?[0-9]+)\s*\)`)
)

// Runner executes snmptranslate with a direct argument vector and returns its standard output.
type Runner interface {
	Run(context.Context, ...string) (string, error)
}

// Options identifies one MIB module, its complete search path, and the explicitly approved objects to export.
type Options struct {
	Module  string
	MIBDirs []string
	Objects []string
}

// ListSymbols returns Net-SNMP's numeric symbol listing for one module and its explicit dependency path.
func ListSymbols(ctx context.Context, runner Runner, module string, directories []string) (string, error) {
	if runner == nil {
		return "", errors.New("runner is required")
	}
	base, err := moduleArgs(module, directories)
	if err != nil {
		return "", err
	}
	output, err := runner.Run(ctx, appendArgs(base, "-Tz")...)
	if err != nil {
		return "", fmt.Errorf("list symbols for %s: %w", module, err)
	}
	return output, nil
}

// moduleArgs validates one module and its complete search path and returns the common snmptranslate arguments.
func moduleArgs(module string, directories []string) ([]string, error) {
	if !identifierPattern.MatchString(module) {
		return nil, errors.New("module must be a valid MIB identifier")
	}
	if len(directories) == 0 {
		return nil, errors.New("at least one MIB directory is required")
	}
	for _, directory := range directories {
		if directory == "" || strings.ContainsAny(directory, ":\x00") {
			return nil, fmt.Errorf("invalid MIB directory %q", directory)
		}
	}
	return []string{"-M", strings.Join(directories, ":"), "-m", module}, nil
}

// Convert resolves every selected object through snmptranslate and returns definitions in numeric OID order.
func Convert(ctx context.Context, runner Runner, options Options) ([]metrics.Definition, error) {
	if runner == nil {
		return nil, errors.New("runner is required")
	}
	base, err := moduleArgs(options.Module, options.MIBDirs)
	if err != nil {
		return nil, err
	}
	if len(options.Objects) == 0 || len(options.Objects) > maxObjects {
		return nil, fmt.Errorf("one to %d objects are required", maxObjects)
	}
	seenObjects := make(map[string]struct{}, len(options.Objects))
	definitions := make([]metrics.Definition, 0, len(options.Objects))
	for _, object := range options.Objects {
		if !identifierPattern.MatchString(object) {
			return nil, fmt.Errorf("object %q is not a valid MIB identifier", object)
		}
		if _, duplicate := seenObjects[object]; duplicate {
			return nil, fmt.Errorf("duplicate object %q", object)
		}
		seenObjects[object] = struct{}{}
		qualified := options.Module + "::" + object
		oidOutput, err := runner.Run(ctx, appendArgs(base, "-On", qualified)...)
		if err != nil {
			return nil, fmt.Errorf("resolve numeric OID for %s: %w", qualified, err)
		}
		oid, err := parseOID(oidOutput)
		if err != nil {
			return nil, fmt.Errorf("resolve numeric OID for %s: %w", qualified, err)
		}
		detailOutput, err := runner.Run(ctx, appendArgs(base, "-Td", qualified)...)
		if err != nil {
			return nil, fmt.Errorf("read MIB details for %s: %w", qualified, err)
		}
		definition, err := parseDetail(object, oid, detailOutput)
		if err != nil {
			return nil, fmt.Errorf("parse MIB details for %s: %w", qualified, err)
		}
		definitions = append(definitions, definition)
	}
	sort.Slice(definitions, func(i, j int) bool { return compareOIDs(definitions[i].OID, definitions[j].OID) < 0 })
	for index := 1; index < len(definitions); index++ {
		if definitions[index-1].OID == definitions[index].OID {
			return nil, fmt.Errorf("objects %q and %q resolve to duplicate OID %s", definitions[index-1].Name, definitions[index].Name, definitions[index].OID)
		}
	}
	return definitions, nil
}

// appendArgs returns a detached argument vector with extra appended.
func appendArgs(base []string, extra ...string) []string {
	args := append([]string(nil), base...)
	return append(args, extra...)
}

// parseOID accepts exactly one numeric dotted OID and removes its optional leading dot.
func parseOID(output string) (string, error) {
	value := strings.TrimSpace(output)
	if !oidPattern.MatchString(value) {
		return "", fmt.Errorf("unexpected numeric OID output %q", value)
	}
	value = strings.TrimPrefix(value, ".")
	parts := strings.Split(value, ".")
	if len(parts) < 2 {
		return "", fmt.Errorf("numeric OID %q has fewer than two arcs", value)
	}
	arcs := make([]uint64, len(parts))
	for index, part := range parts {
		arc, err := strconv.ParseUint(part, 10, 32)
		if err != nil {
			return "", fmt.Errorf("numeric OID %q has an invalid arc: %w", value, err)
		}
		arcs[index] = arc
	}
	if arcs[0] > 2 || (arcs[0] < 2 && arcs[1] > 39) {
		return "", fmt.Errorf("numeric OID %q has an invalid root", value)
	}
	return value, nil
}

// parseDetail extracts the syntax, unit, description, and integer enumeration from snmptranslate -Td output.
func parseDetail(name, oid, output string) (metrics.Definition, error) {
	lines := strings.Split(strings.ReplaceAll(output, "\r\n", "\n"), "\n")
	syntax := directiveBlock(lines, "SYNTAX")
	if syntax == "" {
		return metrics.Definition{}, errors.New("SYNTAX is missing")
	}
	definition := metrics.Definition{
		OID:         oid,
		Name:        name,
		Type:        syntaxType(syntax),
		Unit:        quotedDirective(lines, "UNITS"),
		Description: quotedDirective(lines, "DESCRIPTION"),
	}
	matches := enumPattern.FindAllStringSubmatch(syntax, -1)
	if len(matches) != 0 {
		definition.Enum = make(map[string]string, len(matches))
		for _, match := range matches {
			definition.Enum[match[2]] = match[1]
		}
	}
	return definition, nil
}

// directiveBlock returns one directive value plus indented continuation lines up to the next known directive.
func directiveBlock(lines []string, directive string) string {
	for index, line := range lines {
		value, matches := detailDirectiveValue(line, directive)
		if !matches {
			continue
		}
		parts := []string{value}
		for next := index + 1; next < len(lines); next++ {
			candidate := strings.TrimSpace(lines[next])
			if candidate == "" {
				continue
			}
			if isDetailDirective(candidate) {
				break
			}
			parts = append(parts, candidate)
		}
		return strings.TrimSpace(strings.Join(parts, " "))
	}
	return ""
}

// detailDirectiveValue recognizes an uppercase Net-SNMP field followed by any ASCII whitespace.
func detailDirectiveValue(line, directive string) (string, bool) {
	trimmed := strings.TrimSpace(line)
	if len(trimmed) < len(directive) || trimmed[:len(directive)] != directive {
		return "", false
	}
	if len(trimmed) == len(directive) {
		return "", true
	}
	separator := trimmed[len(directive)]
	if separator != ' ' && separator != '	' && separator != '\r' && separator != '\n' {
		return "", false
	}
	return strings.TrimSpace(trimmed[len(directive):]), true
}

// isDetailDirective reports whether line starts a new snmptranslate detail field.
func isDetailDirective(line string) bool {
	for _, directive := range []string{
		"SYNTAX", "DISPLAY-HINT", "UNITS", "MAX-ACCESS", "MIN-ACCESS", "ACCESS", "STATUS",
		"DESCRIPTION", "REFERENCE", "INDEX", "AUGMENTS", "DEFVAL", "OBJECTS", "NOTIFICATIONS",
		"MODULE", "ENTERPRISE", "VARIABLES", "SUPPORTS", "INCLUDES", "VARIATION", "WRITE-SYNTAX",
		"CREATION-REQUIRES", "PRODUCT-RELEASE", "CONTACT-INFO", "LAST-UPDATED", "ORGANIZATION", "REVISION",
	} {
		if _, matches := detailDirectiveValue(line, directive); matches {
			return true
		}
	}
	return strings.HasPrefix(strings.TrimSpace(line), "::=")
}

// quotedDirective extracts and whitespace-normalizes one quoted detail directive.
func quotedDirective(lines []string, directive string) string {
	block := directiveBlock(lines, directive)
	first := strings.IndexByte(block, '"')
	last := strings.LastIndexByte(block, '"')
	if first < 0 || last <= first {
		return ""
	}
	quoted := block[first : last+1]
	value, err := strconv.Unquote(quoted)
	if err != nil {
		value = strings.Trim(quoted, "\"")
	}
	return strings.Join(strings.Fields(value), " ")
}

// syntaxType removes constraints and enumerations while retaining common multi-word ASN.1 types.
func syntaxType(syntax string) string {
	if index := strings.IndexAny(syntax, "{("); index >= 0 {
		syntax = strings.TrimSpace(syntax[:index])
	}
	fields := strings.Fields(syntax)
	if len(fields) >= 2 && ((fields[0] == "OCTET" && fields[1] == "STRING") || (fields[0] == "OBJECT" && fields[1] == "IDENTIFIER")) {
		return fields[0] + " " + fields[1]
	}
	if len(fields) == 0 {
		return ""
	}
	return fields[0]
}

// compareOIDs compares dotted numeric OIDs component by component.
func compareOIDs(left, right string) int {
	leftParts, rightParts := strings.Split(left, "."), strings.Split(right, ".")
	for index := 0; index < len(leftParts) && index < len(rightParts); index++ {
		leftValue, _ := strconv.ParseUint(leftParts[index], 10, 64)
		rightValue, _ := strconv.ParseUint(rightParts[index], 10, 64)
		if leftValue < rightValue {
			return -1
		}
		if leftValue > rightValue {
			return 1
		}
	}
	if len(leftParts) < len(rightParts) {
		return -1
	}
	if len(leftParts) > len(rightParts) {
		return 1
	}
	return 0
}
