// File: internal/drivers/snmp/client.go
// Purpose: Configure and execute serialized read-only SNMPv3 operations.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package snmp

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"sync"
	"time"

	gosnmp "github.com/gosnmp/gosnmp"
)

// NewGoSNMP validates required connection values and returns an SNMPv3 authPriv client template fixed to SHA-1 authentication and DES privacy.
func NewGoSNMP(target string, port uint16, username, authPassphrase, privacyPassphrase string, timeout time.Duration) (*gosnmp.GoSNMP, error) {
	if target == "" || username == "" || authPassphrase == "" || privacyPassphrase == "" {
		return nil, fmt.Errorf("SNMPv3 authPriv parameters are required")
	}
	return &gosnmp.GoSNMP{Target: target, Port: port, Version: gosnmp.Version3, Timeout: timeout, Retries: 1, ExponentialTimeout: true, MsgFlags: gosnmp.AuthPriv, SecurityModel: gosnmp.UserSecurityModel, SecurityParameters: &gosnmp.UsmSecurityParameters{UserName: username, AuthenticationProtocol: gosnmp.SHA, AuthenticationPassphrase: authPassphrase, PrivacyProtocol: gosnmp.DES, PrivacyPassphrase: privacyPassphrase}, MaxOids: 16, MaxRepetitions: 20}, nil
}

// GoSNMPReader serializes operations that reuse one mutable gosnmp client template.
type GoSNMPReader struct {
	Template *gosnmp.GoSNMP
	mu       sync.Mutex
}

// connect binds ctx to the reader template and opens its SNMP connection, returning an error for missing configuration or connection failure.
func (r *GoSNMPReader) connect(ctx context.Context) error {
	if r.Template == nil {
		return fmt.Errorf("nil SNMP configuration")
	}
	r.Template.Context = ctx
	if err := r.Template.Connect(); err != nil {
		return fmt.Errorf("connect SNMP: %w", err)
	}
	return nil
}

// Get serializes a read-only SNMP GET for oids under ctx and returns response PDUs or a connection, transport, or protocol error.
func (r *GoSNMPReader) Get(ctx context.Context, oids []string) ([]gosnmp.SnmpPDU, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	if err := r.connect(ctx); err != nil {
		return nil, err
	}
	defer r.Template.Conn.Close()
	// Polling is limited to the caller-supplied fixed OIDs and uses only the read-only GET operation.
	return getBatches(oids, r.Template.MaxOids, r.Template.Get)
}

// getBatches executes fixed-OID GETs in bounded batches and concatenates successful responses.
func getBatches(oids []string, maximum int, get func([]string) (*gosnmp.SnmpPacket, error)) ([]gosnmp.SnmpPDU, error) {
	var out []gosnmp.SnmpPDU
	for start := 0; start < len(oids); start += maximum {
		end := start + maximum
		if end > len(oids) {
			end = len(oids)
		}
		packet, err := get(oids[start:end])
		if err != nil {
			return nil, fmt.Errorf("SNMP get OIDs %d-%d of %d: %w", start+1, end, len(oids), err)
		}
		if packet.Error != gosnmp.NoError {
			return nil, fmt.Errorf("SNMP response error %s", packet.Error.String())
		}
		out = append(out, packet.Variables...)
	}
	return out, nil
}

// Walk serializes read-only bulk walks for roots under ctx and returns accumulated PDUs or the first cancellation, connection, or walk error.
func (r *GoSNMPReader) Walk(ctx context.Context, roots []string, maxObjects int) ([]gosnmp.SnmpPDU, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	if err := r.connect(ctx); err != nil {
		return nil, err
	}
	defer r.Template.Conn.Close()
	return walkBounded(ctx, roots, maxObjects, r.Template.BulkWalk)
}

var errDiscoveryLimit = errors.New("SNMP discovery object limit exceeded")

// walkBounded removes overlapping roots and duplicate OIDs while enforcing a hard object limit during streaming.
func walkBounded(ctx context.Context, roots []string, maxObjects int, walk func(string, gosnmp.WalkFunc) error) ([]gosnmp.SnmpPDU, error) {
	var out []gosnmp.SnmpPDU
	seen := make(map[string]struct{})
	for _, root := range deduplicateRoots(roots) {
		err := walk(root, func(p gosnmp.SnmpPDU) error {
			select {
			case <-ctx.Done():
				return ctx.Err()
			default:
				oid := strings.TrimPrefix(strings.TrimSpace(p.Name), ".")
				if _, ok := seen[oid]; ok {
					return nil
				}
				if len(out) >= maxObjects {
					return errDiscoveryLimit
				}
				seen[oid] = struct{}{}
				out = append(out, p)
				return nil
			}
		})
		if err != nil {
			if errors.Is(err, errDiscoveryLimit) {
				return nil, errDiscoveryLimit
			}
			return nil, fmt.Errorf("SNMP walk: %w", err)
		}
	}
	return out, nil
}

// deduplicateRoots canonicalizes roots and drops duplicates and descendants of already selected roots.
func deduplicateRoots(roots []string) []string {
	var out []string
	for _, candidate := range roots {
		candidate = strings.TrimPrefix(strings.TrimSpace(candidate), ".")
		covered := false
		for _, root := range out {
			if candidate == root || strings.HasPrefix(candidate, root+".") {
				covered = true
				break
			}
		}
		if !covered {
			out = append(out, candidate)
		}
	}
	return out
}
