// File: internal/drivers/snmp/snmp_test.go
// Purpose: Verify SNMP conversion, metadata validation, and separate read operations.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package snmp

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
	"time"

	gosnmp "github.com/gosnmp/gosnmp"
)

type fakeReader struct {
	getCalls, walkCalls int
	pdus                []gosnmp.SnmpPDU
}

// Get records one fake fixed-OID read and returns the configured PDUs without an error.
func (f *fakeReader) Get(context.Context, []string) ([]gosnmp.SnmpPDU, error) {
	f.getCalls++
	return f.pdus, nil
}

// Walk records one fake discovery read and returns the configured PDUs without an error.
func (f *fakeReader) Walk(_ context.Context, _ []string, _ int) ([]gosnmp.SnmpPDU, error) {
	f.walkCalls++
	return f.pdus, nil
}

// TestConvertPDUUsesMetadataAndSafeTypes verifies metadata enrichment and JSON-safe counter conversion.
func TestConvertPDUUsesMetadataAndSafeTypes(t *testing.T) {
	meta := Metadata{"1.3.6.1.2.1.1.3.0": {OID: "1.3.6.1.2.1.1.3.0", Name: "sysUpTime", Type: "TimeTicks", Unit: "centiseconds", Description: "Uptime"}}
	m, err := ConvertPDU(gosnmp.SnmpPDU{Name: ".1.3.6.1.2.1.1.3.0", Type: gosnmp.TimeTicks, Value: uint32(123)}, meta, time.Unix(1, 0).UTC())
	if err != nil {
		t.Fatal(err)
	}
	if m.Name != "sysUpTime" || m.Value != uint64(123) || m.ValueType != "counter" || m.Unit != "centiseconds" {
		t.Fatalf("metric=%+v", m)
	}
}

// TestConvertPDURejectsUnsupportedValue verifies that unsupported SNMP exception values return an error.
func TestConvertPDURejectsUnsupportedValue(t *testing.T) {
	if _, err := ConvertPDU(gosnmp.SnmpPDU{Name: ".1", Type: gosnmp.NoSuchObject}, nil, time.Now()); err == nil {
		t.Fatal("expected error")
	}
}

// TestPollingAndDiscoveryAreSeparateReadOperations verifies fixed polling uses GET while discovery alone uses WALK.
func TestPollingAndDiscoveryAreSeparateReadOperations(t *testing.T) {
	f := &fakeReader{pdus: []gosnmp.SnmpPDU{{Name: ".1.2.3", Type: gosnmp.Integer, Value: 5}}}
	c := Collector{Reader: f, OIDs: []string{"1.2.3"}, Roots: []string{"1.2"}}
	if _, err := c.Poll(context.Background()); err != nil {
		t.Fatal(err)
	}
	if f.getCalls != 1 || f.walkCalls != 0 {
		t.Fatalf("get=%d walk=%d", f.getCalls, f.walkCalls)
	}
	defs, err := c.Discover(context.Background())
	if err != nil || len(defs) != 1 {
		t.Fatalf("defs=%v err=%v", defs, err)
	}
	if f.walkCalls != 1 {
		t.Fatalf("walk=%d", f.walkCalls)
	}
}

// TestLoadMetadataRejectsUnknownFields verifies strict metadata JSON decoding.
func TestLoadMetadataRejectsUnknownFields(t *testing.T) {
	p := filepath.Join(t.TempDir(), "mib.json")
	b, _ := json.Marshal([]map[string]any{{"oid": "1.2.3", "name": "x", "unexpected": true}})
	os.WriteFile(p, b, 0o600)
	if _, err := LoadMetadata(p); err == nil {
		t.Fatal("expected unknown field error")
	}
}

// TestWAGO750880ExampleMetadata verifies the checked-in device sample remains valid, complete, and instance-specific.
func TestWAGO750880ExampleMetadata(t *testing.T) {
	path := filepath.Join("..", "..", "..", "configs", "wago-750-880-metadata.example.json")
	metadata, err := LoadMetadata(path)
	if err != nil {
		t.Fatal(err)
	}
	if len(metadata) != 132 {
		t.Fatalf("definitions=%d want 132", len(metadata))
	}
	task := metadata["1.3.6.1.4.1.13576.10.1.30.9.1.3.1"]
	if task.Name != "wioIecTaskStatus[1]" || task.Description == "" {
		t.Fatalf("task metadata=%+v", task)
	}
}
