// File: internal/drivers/snmp/snmp.go
// Purpose: Load SNMP metadata and convert polling or discovery results.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package snmp

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"strings"
	"time"
	"unicode/utf8"

	gosnmp "github.com/gosnmp/gosnmp"
	"github.com/tseiman/HomeAuthMonitorGW/internal/metrics"
)

// Metadata indexes metric definitions by normalized OID.
type Metadata map[string]metrics.Definition

// LoadMetadata reads strict JSON definitions from path and returns an OID-indexed map; an empty path yields an empty map, while malformed or duplicate entries return errors.
func LoadMetadata(path string) (Metadata, error) {
	if path == "" {
		return Metadata{}, nil
	}
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read metadata: %w", err)
	}
	dec := json.NewDecoder(bytes.NewReader(b))
	dec.DisallowUnknownFields()
	var defs []metrics.Definition
	if err := dec.Decode(&defs); err != nil {
		return nil, fmt.Errorf("parse metadata: %w", err)
	}
	m := make(Metadata, len(defs))
	for _, d := range defs {
		oid := normalizeOID(d.OID)
		if oid == "" {
			return nil, errors.New("metadata OID is required")
		}
		if _, ok := m[oid]; ok {
			return nil, fmt.Errorf("duplicate metadata OID %s", oid)
		}
		d.OID = oid
		m[oid] = d
	}
	return m, nil
}

// Reader exposes the fixed GET and separate discovery WALK operations used by Collector.
type Reader interface {
	// Get reads the supplied fixed OIDs and returns their PDUs or an operation error.
	Get(context.Context, []string) ([]gosnmp.SnmpPDU, error)
	// Walk reads configured discovery roots and returns discovered PDUs or an operation error.
	Walk(context.Context, []string, int) ([]gosnmp.SnmpPDU, error)
}

// Collector converts fixed SNMP reads and optional discovery walks into API models.
type Collector struct {
	Reader              Reader
	OIDs, Roots         []string
	MaxDiscoveryObjects int
	Metadata            Metadata
	Now                 func() time.Time
}

// Poll performs a fixed-OID read through the collector Reader and converts every PDU at one timestamp, returning the first read or conversion error.
func (c Collector) Poll(ctx context.Context) ([]metrics.Metric, error) {
	// Routine polling is constrained to the configured OID list; it never performs discovery walks.
	pdus, err := c.Reader.Get(ctx, c.OIDs)
	if err != nil {
		return nil, err
	}
	now := time.Now().UTC()
	if c.Now != nil {
		now = c.Now().UTC()
	}
	out := make([]metrics.Metric, 0, len(pdus))
	for _, p := range pdus {
		m, e := ConvertPDU(p, c.Metadata, now)
		if e != nil {
			return nil, e
		}
		out = append(out, m)
	}
	return out, nil
}

// Discover walks the configured roots, deduplicates returned OIDs, and returns metadata-backed or inferred definitions, propagating reader errors.
func (c Collector) Discover(ctx context.Context) ([]metrics.Definition, error) {
	// Discovery walks only configured roots and remains separate from the polling cache.
	pdus, err := c.Reader.Walk(ctx, c.Roots, c.MaxDiscoveryObjects)
	if err != nil {
		return nil, err
	}
	out := make([]metrics.Definition, 0, len(pdus))
	seen := map[string]bool{}
	for _, p := range pdus {
		oid := normalizeOID(p.Name)
		if seen[oid] {
			continue
		}
		seen[oid] = true
		if d, ok := c.Metadata[oid]; ok {
			out = append(out, d)
		} else {
			out = append(out, metrics.Definition{OID: oid, Name: oid, Type: p.Type.String()})
		}
	}
	return out, nil
}

// ConvertPDU maps p and optional metadata into a JSON-safe metric timestamped at, returning an error for malformed or unsupported SNMP values.
func ConvertPDU(p gosnmp.SnmpPDU, metadata Metadata, at time.Time) (metrics.Metric, error) {
	oid := normalizeOID(p.Name)
	d, ok := metadata[oid]
	name := oid
	if ok && d.Name != "" {
		name = d.Name
	}
	var value any
	var typ string
	switch p.Type {
	case gosnmp.Integer:
		switch v := p.Value.(type) {
		case int:
			value = int64(v)
		case int64:
			value = v
		case uint:
			value = int64(v)
		default:
			value = gosnmp.ToBigInt(p.Value).Int64()
		}
		typ = "integer"
	case gosnmp.Counter32, gosnmp.Gauge32, gosnmp.TimeTicks:
		value = gosnmp.ToBigInt(p.Value).Uint64()
		typ = "counter"
	case gosnmp.Counter64:
		value = gosnmp.ToBigInt(p.Value).Uint64()
		typ = "counter"
	case gosnmp.OctetString:
		b, ok := p.Value.([]byte)
		if !ok {
			return metrics.Metric{}, errors.New("invalid octet string")
		}
		if utf8.Valid(b) {
			value = string(b)
			typ = "string"
		} else {
			value = fmt.Sprintf("%x", b)
			typ = "hex"
		}
	case gosnmp.ObjectIdentifier, gosnmp.IPAddress:
		value = fmt.Sprint(p.Value)
		typ = "string"
	default:
		return metrics.Metric{}, fmt.Errorf("unsupported SNMP value type %s", p.Type.String())
	}
	return metrics.Metric{Name: name, Value: value, ValueType: typ, Unit: d.Unit, Description: d.Description, Timestamp: at, Labels: map[string]string{"oid": oid}}, nil
}

// normalizeOID trims surrounding whitespace and one leading dot from s, returning the canonical lookup form.
func normalizeOID(s string) string { return strings.TrimPrefix(strings.TrimSpace(s), ".") }
