// File: cmd/gateway/main_test.go
// Purpose: Verify command-line version and configuration-check behavior.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package main

import (
	"bytes"
	"strings"
	"testing"
)

// TestVersionFlag verifies that run prints the injected build version and reports success.
func TestVersionFlag(t *testing.T) {
	old := version
	version = "1.2.3-test"
	defer func() { version = old }()
	var out, errOut bytes.Buffer
	if code := run([]string{"--version"}, &out, &errOut); code != 0 {
		t.Fatalf("code=%d stderr=%s", code, errOut.String())
	}
	if !strings.Contains(out.String(), "1.2.3-test") {
		t.Fatalf("output=%q", out.String())
	}
}

// TestCheckReportsMissingConfiguration verifies that run returns failure and a validation diagnostic for a missing config path.
func TestCheckReportsMissingConfiguration(t *testing.T) {
	var out, errOut bytes.Buffer
	if code := run([]string{"--config", "/does/not/exist", "--check"}, &out, &errOut); code == 0 {
		t.Fatal("expected failure")
	}
	if !strings.Contains(errOut.String(), "configuration invalid") {
		t.Fatalf("stderr=%q", errOut.String())
	}
}
