// File: cmd/gateway/main.go
// Purpose: Provide the automation gateway command-line entry point and server lifecycle.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package main

import (
	"context"
	"crypto/tls"
	"errors"
	"flag"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"

	"github.com/tseiman/HomeAutomationMonitorGW/internal/app"
	"github.com/tseiman/HomeAutomationMonitorGW/internal/config"
	"github.com/tseiman/HomeAutomationMonitorGW/internal/httpapi"
)

var (
	version   = "dev"
	commit    = "unknown"
	buildTime = "unknown"
)

const maxConfigFiles = 32

type commandOptions struct {
	configPaths []string
	check       bool
	showVersion bool
	foreground  bool
	logLevel    string
}

type configPaths []string

// String renders configured paths for flag package diagnostics.
func (p *configPaths) String() string { return fmt.Sprint([]string(*p)) }

// Set appends one non-empty configuration path.
func (p *configPaths) Set(value string) error {
	if value == "" {
		return errors.New("configuration path must not be empty")
	}
	if len(*p) >= maxConfigFiles {
		return fmt.Errorf("at most %d configuration files are allowed", maxConfigFiles)
	}
	*p = append(*p, value)
	return nil
}

// parseOptions validates command-line syntax and applies production defaults without starting the service.
func parseOptions(args []string, diagnostics io.Writer) (commandOptions, error) {
	var options commandOptions
	var paths configPaths
	fs := flag.NewFlagSet("automation-gateway", flag.ContinueOnError)
	fs.SetOutput(diagnostics)
	fs.Usage = func() {
		fmt.Fprint(diagnostics, `Usage: automation-gateway [options]

Options:
  --config=PATH, -C=PATH       Configuration file; repeat for ordered overlays.
  --check, -c                  Validate configuration and referenced files, then exit.
  --foreground, -f             Use human-readable foreground logging.
  --log-level=LEVEL, -l=LEVEL  Override log level: debug, info, warn, or error.
  --version, -V                Print version and exit.
  --help, -h                   Show this help text.
`)
	}
	fs.Var(&paths, "config", "configuration file; repeat for ordered overlays")
	fs.Var(&paths, "C", "short form of --config")
	fs.BoolVar(&options.check, "check", false, "validate configuration and referenced files, then exit")
	fs.BoolVar(&options.check, "c", false, "short form of --check")
	fs.BoolVar(&options.showVersion, "version", false, "print version and exit")
	fs.BoolVar(&options.showVersion, "V", false, "short form of --version")
	fs.BoolVar(&options.foreground, "foreground", false, "use human-readable foreground logging")
	fs.BoolVar(&options.foreground, "f", false, "short form of --foreground")
	fs.StringVar(&options.logLevel, "log-level", "", "override log level: debug, info, warn, or error")
	fs.StringVar(&options.logLevel, "l", "", "short form of --log-level")
	if err := fs.Parse(args); err != nil {
		return commandOptions{}, err
	}
	if fs.NArg() != 0 {
		return commandOptions{}, errors.New("unexpected positional arguments")
	}
	if options.logLevel != "" && options.logLevel != "debug" && options.logLevel != "info" && options.logLevel != "warn" && options.logLevel != "error" {
		return commandOptions{}, fmt.Errorf("invalid --log-level %q", options.logLevel)
	}
	if len(paths) == 0 {
		paths = append(paths, "/etc/automation-gateway/config.yaml")
	}
	options.configPaths = append([]string(nil), paths...)
	return options, nil
}

// configuredLogLevel returns the slog level represented by one validated configuration value.
func configuredLogLevel(name string) slog.Level {
	switch name {
	case "debug":
		return slog.LevelDebug
	case "warn":
		return slog.LevelWarn
	case "error":
		return slog.LevelError
	default:
		return slog.LevelInfo
	}
}

// newLoggerWithLevel creates text or JSON output controlled by a fixed or dynamic level.
func newLoggerWithLevel(output io.Writer, foreground bool, level slog.Leveler) *slog.Logger {
	options := &slog.HandlerOptions{Level: level}
	if foreground {
		return slog.New(slog.NewTextHandler(output, options))
	}
	return slog.New(slog.NewJSONHandler(output, options))
}

// newLogger creates text output for explicit foreground use and JSON otherwise, with an optional level override.
func newLogger(output io.Writer, foreground bool, configuredLevel, override string) *slog.Logger {
	levelName := configuredLevel
	if override != "" {
		levelName = override
	}
	return newLoggerWithLevel(output, foreground, configuredLogLevel(levelName))
}

// main passes process arguments and standard streams to run, then exits with the returned status code.
func main() { os.Exit(run(os.Args[1:], os.Stdout, os.Stderr)) }

// run parses args, writes normal and diagnostic output to the supplied writers, and returns a process exit code without exiting directly.
func run(args []string, stdout, stderr io.Writer) int {
	options, err := parseOptions(args, stderr)
	if err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return 0
		}
		fmt.Fprintln(stderr, err)
		return 2
	}
	if options.showVersion {
		fmt.Fprintf(stdout, "automation-gateway %s (commit %s, built %s)\n", version, commit, buildTime)
		return 0
	}
	if options.check {
		if err := app.CheckFiles(options.configPaths); err != nil {
			fmt.Fprintf(stderr, "configuration invalid: %v\n", err)
			return 1
		}
		fmt.Fprintln(stdout, "configuration OK")
		return 0
	}
	logOutput := stderr
	if options.foreground {
		logOutput = stdout
	}
	if err := serve(options.configPaths, logOutput, options.foreground, options.logLevel); err != nil {
		fmt.Fprintf(stderr, "automation-gateway: %v\n", err)
		return 1
	}
	return 0
}

// serve loads configPaths, runs the HTTPS gateway using logOutput, logs reload failures without exiting, and returns any startup, serving, or graceful-shutdown error.
func serve(configPaths []string, logOutput io.Writer, foreground bool, levelOverride string) error {
	loaded, err := config.LoadFiles(configPaths, true)
	if err != nil {
		return err
	}
	levelName := loaded.Logging.Level
	if levelOverride != "" {
		levelName = levelOverride
	}
	var dynamicLevel slog.LevelVar
	dynamicLevel.Set(configuredLogLevel(levelName))
	logger := newLoggerWithLevel(logOutput, foreground, &dynamicLevel)
	runtime, err := app.NewFiles(configPaths, logger)
	if err != nil {
		return err
	}
	cfg := runtime.Config()
	handler := httpapi.New(func() httpapi.View {
		view := runtime.View()
		return httpapi.View{Store: view.Store, TokenDigests: view.TokenDigests, AllowedClients: view.AllowedClients, CertificateNotAfter: view.CertificateNotAfter}
	}, httpapi.Options{Version: version, Logger: logger})
	server := &http.Server{Addr: cfg.Server.Listen, Handler: handler, ReadHeaderTimeout: cfg.Server.ReadTimeout.Duration, ReadTimeout: cfg.Server.ReadTimeout.Duration, WriteTimeout: cfg.Server.WriteTimeout.Duration, IdleTimeout: cfg.Server.IdleTimeout.Duration, MaxHeaderBytes: cfg.Server.MaxHeaderBytes, TLSConfig: &tls.Config{MinVersion: tls.VersionTLS12, GetCertificate: runtime.GetCertificate}}
	errs := make(chan error, 1)
	go func() {
		logger.Info("gateway starting", "version", version, "listen", cfg.Server.Listen)
		errs <- server.ListenAndServeTLS("", "")
	}()
	signals := make(chan os.Signal, 2)
	// SIGHUP reloads validated state in place; termination signals enter the bounded graceful-shutdown path.
	signal.Notify(signals, syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM)
	defer signal.Stop(signals)
	for {
		select {
		case sig := <-signals:
			if sig == syscall.SIGHUP {
				if err := runtime.Reload(); err != nil {
					logger.Error("reload failed", "error", err)
				} else {
					if levelOverride == "" {
						dynamicLevel.Set(configuredLogLevel(runtime.Config().Logging.Level))
					}
					logger.Info("configuration and certificate reloaded")
				}
				continue
			}
			logger.Info("shutdown requested", "signal", sig.String())
			// HTTP and collector shutdown share one deadline, so their combined latency remains bounded.
			ctx, cancel := context.WithTimeout(context.Background(), cfg.Server.ShutdownTimeout.Duration)
			serverErr := server.Shutdown(ctx)
			runtimeErr := runtime.CloseContext(ctx)
			cancel()
			if serverErr != nil || runtimeErr != nil {
				return fmt.Errorf("graceful shutdown: %w", errors.Join(serverErr, runtimeErr))
			}
			err = <-errs
			if errors.Is(err, http.ErrServerClosed) {
				return nil
			}
			return err
		case err := <-errs:
			ctx, cancel := context.WithTimeout(context.Background(), cfg.Server.ShutdownTimeout.Duration)
			closeErr := runtime.CloseContext(ctx)
			cancel()
			if !errors.Is(err, http.ErrServerClosed) {
				return errors.Join(err, closeErr)
			}
			return closeErr
		}
	}
}
