#!/usr/bin/env bash
# File: scripts/install.sh
# Purpose: Install or update HomeAuthMonitorGW without replacing site-owned configuration or secrets.
# Generated by: aiAgentTseiman (Hermes Agent)
# Generated on: 2026-10-04

set -euo pipefail

readonly SERVICE_NAME="automation-gateway"
readonly SERVICE_USER="automation-gateway"
readonly SERVICE_GROUP="automation-gateway"
readonly SYSTEM_ID_LIMIT=1000
readonly DEFAULT_BINARY="/usr/local/sbin/automation-gateway"
readonly DEFAULT_CONFIG_DIR="/etc/automation-gateway"
readonly DEFAULT_UNIT="/etc/systemd/system/automation-gateway.service"

SCRIPT_PATH="$(readlink -f -- "${BASH_SOURCE[0]}")"
PROJECT_ROOT="$(CDPATH= cd -- "$(dirname -- "$SCRIPT_PATH")/.." && pwd -P)"
SOURCE_BINARY=""
FORCE_START=false
SKIP_TESTS=false
TEST_ROOT="${HOMEAUTH_INSTALL_TEST_ROOT:-}"
TESTING="${HOMEAUTH_INSTALL_TESTING:-0}"
BUILD_TEMP=""
CURRENT_TEMP=""
STAGE_DIR=""

usage() {
    cat <<'USAGE'
Usage: ./scripts/install.sh [--binary PATH] [--start] [--skip-tests]

Without --binary, the script runs the Go tests and vet, builds a deterministic
static binary as the invoking user, and then uses sudo only for installation.

Options:
  --binary PATH  Install an already built binary instead of building locally.
  --start        Start and enable an existing but currently inactive service.
  --skip-tests   Skip go test and go vet before a local build.
  --help         Show this help text.
USAGE
}

log() {
    printf '[install] %s\n' "$*"
}

warn() {
    printf '[install] WARNING: %s\n' "$*" >&2
}

die() {
    printf '[install] ERROR: %s\n' "$*" >&2
    exit 1
}

cleanup() {
    if [[ -n "$CURRENT_TEMP" && -e "$CURRENT_TEMP" ]]; then
        rm -f -- "$CURRENT_TEMP"
    fi
    if [[ -n "$BUILD_TEMP" && -e "$BUILD_TEMP" ]]; then
        rm -f -- "$BUILD_TEMP"
    fi
    if [[ -n "$STAGE_DIR" && -d "$STAGE_DIR" ]]; then
        rm -f -- "$STAGE_DIR/gateway" "$STAGE_DIR/config.yaml" "$STAGE_DIR/mib-metadata.json" "$STAGE_DIR/automation-gateway.service"
        rmdir -- "$STAGE_DIR" 2>/dev/null || true
    fi
}
trap cleanup EXIT

root_path() {
    local path="$1"
    if [[ -n "$TEST_ROOT" ]]; then
        printf '%s%s\n' "$TEST_ROOT" "$path"
    else
        printf '%s\n' "$path"
    fi
}

require_command() {
    command -v -- "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

reject_symlink() {
    local path="$1"
    [[ ! -L "$path" ]] || die "refusing symlink target: $path"
}

ensure_source_file() {
    local path="$1"
    [[ -f "$path" && ! -L "$path" ]] || die "required repository file is not a regular non-symlink: $path"
}

install_owned() {
    local source="$1"
    local target="$2"
    local mode="$3"
    local owner="$4"
    local group="$5"

    reject_symlink "$target"
    CURRENT_TEMP="$(mktemp -- "${target}.tmp.XXXXXX")"
    if [[ "$TESTING" == "1" ]]; then
        if ! install -m "$mode" -- "$source" "$CURRENT_TEMP"; then
            rm -f -- "$CURRENT_TEMP"
            CURRENT_TEMP=""
            return 1
        fi
    else
        if ! install -o "$owner" -g "$group" -m "$mode" -- "$source" "$CURRENT_TEMP"; then
            rm -f -- "$CURRENT_TEMP"
            CURRENT_TEMP=""
            return 1
        fi
    fi
    if ! mv -fT -- "$CURRENT_TEMP" "$target"; then
        rm -f -- "$CURRENT_TEMP"
        CURRENT_TEMP=""
        return 1
    fi
    CURRENT_TEMP=""
}

backup_file() {
    local source="$1"
    local target="$2"
    local mode="$3"
    local owner="$4"
    local group="$5"

    install_owned "$source" "$target" "$mode" "$owner" "$group" || return 1
    log "saved rollback copy $target"
}

ensure_directory() {
    local target="$1"
    local mode="$2"
    local metadata

    reject_symlink "$target"
    if [[ -e "$target" ]]; then
        [[ -d "$target" ]] || die "expected directory: $target"
        if [[ "$TESTING" != "1" ]]; then
            metadata="$(stat -c '%U:%G:%a' -- "$target")"
            [[ "$metadata" == "root:${SERVICE_GROUP}:${mode#0}" ]] || die "unsafe existing directory ownership or mode for $target: $metadata"
        fi
        log "validated existing directory $target"
        return
    fi
    if [[ "$TESTING" == "1" ]]; then
        install -d -m "$mode" -- "$target"
    else
        install -d -o root -g "$SERVICE_GROUP" -m "$mode" -- "$target"
    fi
    log "created directory $target"
}

validate_installed_file() {
    local target="$1"
    local expected="$2"
    local metadata

    reject_symlink "$target"
    [[ -f "$target" ]] || die "expected regular file: $target"
    if [[ "$TESTING" != "1" ]]; then
        metadata="$(stat -c '%U:%G:%a' -- "$target")"
        [[ "$metadata" == "$expected" ]] || die "unsafe existing file ownership or mode for $target: $metadata"
    fi
}

install_default_if_missing() {
    local source="$1"
    local target="$2"

    reject_symlink "$target"
    if [[ -e "$target" ]]; then
        validate_installed_file "$target" "root:${SERVICE_GROUP}:640"
        log "preserved existing site file $target"
        return 1
    fi
    install_owned "$source" "$target" 0640 root "$SERVICE_GROUP"
    log "installed initial editable copy $target"
    return 0
}

files_differ() {
    local source="$1"
    local target="$2"
    [[ ! -e "$target" ]] || ! cmp -s -- "$source" "$target"
}

run_config_check() {
    local binary="$1"
    local config="$2"
    if [[ "$TESTING" == "1" ]]; then
        "$binary" --config "$config" --check
    else
        runuser -u "$SERVICE_USER" -- "$binary" --config "$config" --check
    fi
}

systemctl_is_active() {
    systemctl is-active --quiet "$SERVICE_NAME"
}

systemctl_is_enabled() {
    systemctl is-enabled --quiet "$SERVICE_NAME"
}

ensure_identity() {
    local group_entry user_entry service_gid user_gid user_uid user_home user_shell

    if group_entry="$(getent group "$SERVICE_GROUP")"; then
        service_gid="$(cut -d: -f3 <<<"$group_entry")"
    else
        addgroup --system "$SERVICE_GROUP"
        service_gid="$(getent group "$SERVICE_GROUP" | cut -d: -f3)"
        log "created system group $SERVICE_GROUP"
    fi
    [[ "$service_gid" != "0" ]] || die "$SERVICE_GROUP must not use GID 0"
    (( service_gid < SYSTEM_ID_LIMIT )) || die "$SERVICE_GROUP must use a system GID below $SYSTEM_ID_LIMIT"

    if user_entry="$(getent passwd "$SERVICE_USER")"; then
        user_uid="$(cut -d: -f3 <<<"$user_entry")"
        user_gid="$(cut -d: -f4 <<<"$user_entry")"
        user_home="$(cut -d: -f6 <<<"$user_entry")"
        user_shell="$(cut -d: -f7 <<<"$user_entry")"
        [[ "$user_uid" != "0" ]] || die "$SERVICE_USER must not be root"
        (( user_uid < SYSTEM_ID_LIMIT )) || die "$SERVICE_USER must use a system UID below $SYSTEM_ID_LIMIT"
        [[ "$user_gid" == "$service_gid" ]] || die "$SERVICE_USER must use $SERVICE_GROUP as its primary group"
        [[ "$user_home" == "/nonexistent" ]] || die "$SERVICE_USER must use /nonexistent as its home"
        [[ "$user_shell" == "/usr/sbin/nologin" ]] || die "$SERVICE_USER must use /usr/sbin/nologin as its shell"
        log "validated existing service identity $SERVICE_USER"
    else
        adduser --system --ingroup "$SERVICE_GROUP" --no-create-home --home /nonexistent --shell /usr/sbin/nologin "$SERVICE_USER"
        log "created system user $SERVICE_USER"
    fi
}

build_binary() {
    local version commit build_time ldflags go_version go_major go_minor

    require_command go
    require_command git
    [[ -f "$PROJECT_ROOT/go.mod" ]] || die "go.mod not found below $PROJECT_ROOT"
    [[ -z "$(git -C "$PROJECT_ROOT" status --porcelain)" ]] || die "refusing to build from a dirty Git worktree"

    go_version="$(GOTOOLCHAIN=local go env GOVERSION)"
    [[ "$go_version" =~ ^go([0-9]+)\.([0-9]+)(\.|$) ]] || die "cannot parse Go version: $go_version"
    go_major="${BASH_REMATCH[1]}"
    go_minor="${BASH_REMATCH[2]}"
    if (( go_major < 1 || (go_major == 1 && go_minor < 23) )); then
        die "Go 1.23 or newer is required; found $go_version"
    fi

    version="$(git -C "$PROJECT_ROOT" describe --tags --always --dirty)"
    commit="$(git -C "$PROJECT_ROOT" rev-parse HEAD)"
    build_time="$(git -C "$PROJECT_ROOT" show -s --format=%cI HEAD)"
    [[ "$version" =~ ^[0-9A-Za-z._+-]+$ ]] || die "unsafe generated version string"
    [[ "$commit" =~ ^[0-9a-f]{40}$ ]] || die "invalid Git commit identifier"
    [[ "$build_time" =~ ^[0-9T:+-]+$ ]] || die "invalid Git commit time"

    log "downloading the checksummed Go module dependencies"
    (cd "$PROJECT_ROOT" && GOTOOLCHAIN=local go mod download)
    [[ -z "$(git -C "$PROJECT_ROOT" status --porcelain)" ]] || die "dependency resolution changed the Git worktree"
    if [[ "$SKIP_TESTS" != "true" ]]; then
        log "running test and vet gates"
        (cd "$PROJECT_ROOT" && GOTOOLCHAIN=local GOPROXY=off go test ./...)
        (cd "$PROJECT_ROOT" && GOTOOLCHAIN=local GOPROXY=off go vet ./...)
    fi

    [[ -z "$(git -C "$PROJECT_ROOT" status --porcelain)" ]] || die "Git worktree changed during verification"
    BUILD_TEMP="$(mktemp -- "${TMPDIR:-/tmp}/automation-gateway.build.XXXXXX")"
    ldflags="-s -w -X main.version=$version -X main.commit=$commit -X main.buildTime=$build_time"
    log "building static gateway binary for the local userspace architecture"
    (cd "$PROJECT_ROOT" && CGO_ENABLED=0 GOTOOLCHAIN=local GOPROXY=off go build -trimpath -ldflags "$ldflags" -o "$BUILD_TEMP" ./cmd/gateway)
    chmod 0755 -- "$BUILD_TEMP"
    SOURCE_BINARY="$BUILD_TEMP"
}

manual_rollback_required() {
    warn "$1"
    warn "the installer did not roll back automatically"
    warn "inspect the installed files and their .previous copies, then decide whether to restore them"
    exit 1
}

install_phase() {
    local binary_target config_dir secrets_dir tokens_dir config_target metadata_target unit_target
    local source_config source_metadata source_unit check_binary
    local had_binary=false had_unit=false binary_changed=false unit_changed=false config_created=false
    local config_valid=false was_active=false was_enabled=false deployment_changed=false

    require_command cmp
    require_command install
    require_command mktemp
    require_command stat
    require_command systemctl
    require_command systemd-analyze

    if [[ "$TESTING" == "1" ]]; then
        local canonical_test_root canonical_temp_root
        [[ -n "$TEST_ROOT" && "$TEST_ROOT" == /* && "$TEST_ROOT" != "/" ]] || die "invalid test root"
        canonical_test_root="$(readlink -f -- "$TEST_ROOT")"
        canonical_temp_root="$(readlink -f -- "${TMPDIR:-/tmp}")"
        [[ "$canonical_test_root" == "$canonical_temp_root"/* ]] || die "test root must be below $canonical_temp_root"
        [[ -f "$canonical_test_root/.homeauth-install-test-root" && ! -L "$canonical_test_root/.homeauth-install-test-root" ]] || die "test root marker is missing"
        TEST_ROOT="$canonical_test_root"
        mkdir -p -- "$TEST_ROOT/usr/local/sbin" "$TEST_ROOT/etc/systemd/system"
    else
        [[ -z "$TEST_ROOT" ]] || die "HOMEAUTH_INSTALL_TEST_ROOT requires HOMEAUTH_INSTALL_TESTING=1"
        [[ "$(id -u)" == "0" ]] || die "installation phase requires root"
        require_command addgroup
        require_command adduser
        require_command getent
        require_command runuser
        ensure_identity
    fi

    binary_target="$(root_path "$DEFAULT_BINARY")"
    config_dir="$(root_path "$DEFAULT_CONFIG_DIR")"
    secrets_dir="$config_dir/secrets"
    tokens_dir="$config_dir/tokens"
    config_target="$config_dir/config.yaml"
    metadata_target="$config_dir/mib-metadata.json"
    unit_target="$(root_path "$DEFAULT_UNIT")"
    source_config="$PROJECT_ROOT/configs/config.example.yaml"
    source_metadata="$PROJECT_ROOT/configs/mib-metadata.example.json"
    source_unit="$PROJECT_ROOT/systemd/automation-gateway.service"

    ensure_source_file "$SOURCE_BINARY"
    ensure_source_file "$source_config"
    ensure_source_file "$source_metadata"
    ensure_source_file "$source_unit"

    if [[ "$TESTING" == "1" ]]; then
        STAGE_DIR="$(mktemp -d -- "$TEST_ROOT/install-stage.XXXXXX")"
        install -m 0755 -- "$SOURCE_BINARY" "$STAGE_DIR/gateway"
        install -m 0644 -- "$source_config" "$STAGE_DIR/config.yaml"
        install -m 0644 -- "$source_metadata" "$STAGE_DIR/mib-metadata.json"
        install -m 0644 -- "$source_unit" "$STAGE_DIR/automation-gateway.service"
    else
        STAGE_DIR="$(mktemp -d -- /var/tmp/automation-gateway-install.XXXXXX)"
        chmod 0700 -- "$STAGE_DIR"
        install -o root -g root -m 0755 -- "$SOURCE_BINARY" "$STAGE_DIR/gateway"
        install -o root -g root -m 0644 -- "$source_config" "$STAGE_DIR/config.yaml"
        install -o root -g root -m 0644 -- "$source_metadata" "$STAGE_DIR/mib-metadata.json"
        install -o root -g root -m 0644 -- "$source_unit" "$STAGE_DIR/automation-gateway.service"
    fi
    SOURCE_BINARY="$STAGE_DIR/gateway"
    source_config="$STAGE_DIR/config.yaml"
    source_metadata="$STAGE_DIR/mib-metadata.json"
    source_unit="$STAGE_DIR/automation-gateway.service"

    ensure_directory "$config_dir" 0750
    ensure_directory "$secrets_dir" 0750
    ensure_directory "$tokens_dir" 0750
    if install_default_if_missing "$source_config" "$config_target"; then
        config_created=true
    fi
    install_default_if_missing "$source_metadata" "$metadata_target" || true

    reject_symlink "$binary_target"
    reject_symlink "$unit_target"
    if [[ -e "$binary_target" ]]; then
        validate_installed_file "$binary_target" "root:root:755"
        had_binary=true
    fi
    if [[ -e "$unit_target" ]]; then
        validate_installed_file "$unit_target" "root:root:644"
        had_unit=true
    fi
    if files_differ "$SOURCE_BINARY" "$binary_target"; then
        binary_changed=true
    fi
    if files_differ "$source_unit" "$unit_target"; then
        unit_changed=true
    fi

    CURRENT_TEMP="$(mktemp -- "${binary_target}.candidate.XXXXXX")"
    if [[ "$TESTING" == "1" ]]; then
        install -m 0755 -- "$SOURCE_BINARY" "$CURRENT_TEMP"
    else
        install -o root -g root -m 0755 -- "$SOURCE_BINARY" "$CURRENT_TEMP"
    fi
    check_binary="$CURRENT_TEMP"
    if run_config_check "$check_binary" "$config_target"; then
        config_valid=true
        log "configuration check passed with the candidate binary"
    fi
    rm -f -- "$CURRENT_TEMP"
    CURRENT_TEMP=""

    if [[ "$config_valid" == "true" ]]; then
        :
    elif [[ "$had_binary" == "true" && ( "$binary_changed" == "true" || "$unit_changed" == "true" ) ]]; then
        die "existing configuration is invalid with the candidate; installed binary and unit were not changed"
    elif [[ "$had_binary" == "true" ]]; then
        warn "configuration still requires provisioning; installed binary and unit are already current"
        return 0
    else
        warn "initial example configuration requires site token/source setup and externally provisioned TLS files; the service will not be enabled or started"
    fi

    if systemctl_is_active; then
        was_active=true
    fi
    if systemctl_is_enabled; then
        was_enabled=true
    fi

    if [[ "$binary_changed" == "true" || "$unit_changed" == "true" ]]; then
        if [[ "$had_binary" == "true" ]]; then
            backup_file "$binary_target" "${binary_target}.previous" 0755 root root
        fi
        if [[ "$had_unit" == "true" ]]; then
            backup_file "$unit_target" "${unit_target}.previous" 0644 root root
        fi
    fi

    if [[ "$binary_changed" == "true" ]]; then
        if ! install_owned "$SOURCE_BINARY" "$binary_target" 0755 root root; then
            die "failed to install $binary_target; no deployment file was replaced"
        fi
        deployment_changed=true
        log "installed $binary_target"
    else
        log "binary is already current"
    fi

    if [[ "$unit_changed" == "true" ]]; then
        if ! install_owned "$source_unit" "$unit_target" 0644 root root; then
            if [[ "$deployment_changed" == "true" ]]; then
                manual_rollback_required "failed to install $unit_target after replacing another deployment file"
            fi
            die "failed to install $unit_target; no deployment file was replaced"
        fi
        deployment_changed=true
        log "installed $unit_target"
    else
        log "systemd unit is already current"
    fi

    if ! systemd-analyze verify "$unit_target"; then
        if [[ "$deployment_changed" == "true" ]]; then
            manual_rollback_required "systemd unit verification failed after file installation"
        fi
        die "systemd unit verification failed; deployment files were unchanged"
    fi

    if [[ "$unit_changed" == "true" ]]; then
        if ! systemctl daemon-reload; then
            manual_rollback_required "systemd daemon-reload failed after file installation"
        fi
    fi

    if [[ "$config_valid" != "true" ]]; then
        log "installation files are ready; edit $config_target, provision secrets, and point it at externally managed TLS files"
        log "the installer never creates, copies, changes, renews, or removes TLS certificate/key files"
        log "then rerun this script with --start"
        return 0
    fi

    if [[ "$had_binary" == "false" && "$config_created" == "false" ]]; then
        FORCE_START=true
    fi

    if [[ "$FORCE_START" == "true" ]]; then
        if ! systemctl enable --now "$SERVICE_NAME"; then
            if [[ "$deployment_changed" == "true" ]]; then
                manual_rollback_required "failed to enable and start $SERVICE_NAME after file installation"
            fi
            die "failed to enable and start $SERVICE_NAME; deployment files were unchanged"
        fi
        log "enabled and started $SERVICE_NAME"
    elif [[ "$was_active" == "true" && "$deployment_changed" == "true" ]]; then
        if ! systemctl restart "$SERVICE_NAME"; then
            manual_rollback_required "service restart failed after file installation"
        fi
        log "restarted active service $SERVICE_NAME"
    elif [[ "$was_active" == "true" ]]; then
        log "active service is unchanged; restart skipped"
    elif [[ "$was_enabled" == "true" ]]; then
        log "service remains enabled but inactive; use --start to start it"
    else
        log "service remains inactive; use --start when site provisioning is complete"
    fi
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --binary)
            [[ $# -ge 2 ]] || die "--binary requires a path"
            SOURCE_BINARY="$(readlink -f -- "$2")"
            shift 2
            ;;
        --start)
            FORCE_START=true
            shift
            ;;
        --skip-tests)
            SKIP_TESTS=true
            shift
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            die "unknown argument: $1"
            ;;
    esac
done

if [[ -z "$SOURCE_BINARY" ]]; then
    if [[ "$TESTING" == "1" ]]; then
        die "test mode requires --binary"
    fi
    if [[ "$(id -u)" == "0" ]]; then
        die "run without sudo so tests and compilation are unprivileged, or pass --binary PATH"
    fi
    build_binary
fi

SOURCE_BINARY="$(readlink -f -- "$SOURCE_BINARY")"
ensure_source_file "$SOURCE_BINARY"

if [[ "$TESTING" == "1" || "$(id -u)" == "0" ]]; then
    install_phase
else
    require_command sudo
    args=(--binary "$SOURCE_BINARY")
    [[ "$FORCE_START" == "true" ]] && args+=(--start)
    sudo -- "$SCRIPT_PATH" "${args[@]}"
fi
