// File: scripts/install_test.go
// Purpose: Exercise the production installer against an isolated filesystem and fake systemd commands.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package scripts

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// TestInstallAndUpdateLifecycle proves fresh installation, preservation, update, rollback gating, and idempotency.
func TestInstallAndUpdateLifecycle(t *testing.T) {
	projectRoot := projectRoot(t)
	testRoot := t.TempDir()
	fakeBinDir := filepath.Join(t.TempDir(), "bin")
	stateDir := filepath.Join(t.TempDir(), "state")
	mustMkdirAll(t, fakeBinDir)
	mustMkdirAll(t, stateDir)
	writeFakeSystemTools(t, fakeBinDir)

	candidateV1 := writeCandidate(t, t.TempDir(), "v1")
	runInstaller(t, projectRoot, testRoot, fakeBinDir, stateDir, candidateV1, true)

	installedBinary := filepath.Join(testRoot, "usr/local/sbin/automation-gateway")
	config := filepath.Join(testRoot, "etc/automation-gateway/config.yaml")
	metadata := filepath.Join(testRoot, "etc/automation-gateway/mib-metadata.json")
	unit := filepath.Join(testRoot, "etc/systemd/system/automation-gateway.service")
	assertContains(t, installedBinary, "VERSION=v1")
	assertContains(t, config, "server:")
	assertContains(t, unit, "User=automation-gateway")
	if _, err := os.Stat(filepath.Join(stateDir, "active")); !os.IsNotExist(err) {
		t.Fatalf("fresh unprovisioned install unexpectedly started the service: %v", err)
	}

	customConfig := "# site-owned configuration\n"
	customMetadata := "{\"site\":\"owned\"}\n"
	mustWriteFile(t, config, customConfig, 0o640)
	mustWriteFile(t, metadata, customMetadata, 0o640)
	mustWriteFile(t, config+".ready", "ready\n", 0o600)
	secret := filepath.Join(testRoot, "etc/automation-gateway/tokens/site-token")
	mustWriteFile(t, secret, "preserve-me\n", 0o640)
	snmpSecret := filepath.Join(testRoot, "etc/automation-gateway/secrets/wago-auth")
	mustWriteFile(t, snmpSecret, "preserve-snmp-secret\n", 0o640)
	nutConfig := filepath.Join(testRoot, "etc/nut/ups.conf")
	mustWriteFile(t, nutConfig, "[ups]\n  driver = usbhid-ups\n", 0o640)
	certificate := filepath.Join(testRoot, "etc/site-tls/gateway.crt")
	privateKey := filepath.Join(testRoot, "etc/site-tls/gateway.key")
	mustWriteFile(t, certificate, "externally-managed-certificate\n", 0o640)
	mustWriteFile(t, privateKey, "externally-managed-private-key\n", 0o640)

	runInstaller(t, projectRoot, testRoot, fakeBinDir, stateDir, candidateV1, true, "--start")
	assertFileEquals(t, config, customConfig)
	assertFileEquals(t, metadata, customMetadata)
	assertFileEquals(t, secret, "preserve-me\n")
	assertFileEquals(t, certificate, "externally-managed-certificate\n")
	assertFileEquals(t, privateKey, "externally-managed-private-key\n")
	mustExist(t, filepath.Join(stateDir, "active"))
	mustExist(t, filepath.Join(stateDir, "enabled"))

	candidateV2 := writeCandidate(t, t.TempDir(), "v2")
	mustWriteFile(t, unit, "[Unit]\nDescription=stale test unit\n", 0o644)
	runInstaller(t, projectRoot, testRoot, fakeBinDir, stateDir, candidateV2, true)
	assertContains(t, installedBinary, "VERSION=v2")
	assertContains(t, installedBinary+".previous", "VERSION=v1")
	mustExist(t, unit+".previous")
	assertContains(t, unit+".previous", "stale test unit")
	assertContains(t, unit, "ProtectSystem=strict")
	assertFileEquals(t, config, customConfig)
	assertFileEquals(t, secret, "preserve-me\n")
	assertFileEquals(t, snmpSecret, "preserve-snmp-secret\n")
	assertFileEquals(t, nutConfig, "[ups]\n  driver = usbhid-ups\n")
	assertFileEquals(t, certificate, "externally-managed-certificate\n")
	assertFileEquals(t, privateKey, "externally-managed-private-key\n")
	restartsAfterUpdate := countLogLine(t, filepath.Join(stateDir, "systemctl.log"), "restart automation-gateway")
	if restartsAfterUpdate != 1 {
		t.Fatalf("restart count after update = %d, want 1", restartsAfterUpdate)
	}

	runInstaller(t, projectRoot, testRoot, fakeBinDir, stateDir, candidateV2, true)
	if got := countLogLine(t, filepath.Join(stateDir, "systemctl.log"), "restart automation-gateway"); got != restartsAfterUpdate {
		t.Fatalf("idempotent rerun added a restart: got %d, want %d", got, restartsAfterUpdate)
	}

	olderCandidate := writeCandidate(t, t.TempDir(), "v1-operator-selected")
	runInstaller(t, projectRoot, testRoot, fakeBinDir, stateDir, olderCandidate, true)
	assertContains(t, installedBinary, "VERSION=v1-operator-selected")
	assertContains(t, installedBinary+".previous", "VERSION=v2")
	runInstaller(t, projectRoot, testRoot, fakeBinDir, stateDir, candidateV2, true)
	assertContains(t, installedBinary, "VERSION=v2")

	candidateV3 := writeCandidate(t, t.TempDir(), "v3")
	mustWriteFile(t, filepath.Join(stateDir, "fail-restart"), "fail\n", 0o600)
	runInstaller(t, projectRoot, testRoot, fakeBinDir, stateDir, candidateV3, false)
	assertContains(t, installedBinary, "VERSION=v3")
	assertContains(t, installedBinary+".previous", "VERSION=v2")
	mustCopyFile(t, installedBinary+".previous", installedBinary, 0o755)
	assertContains(t, installedBinary, "VERSION=v2")
	if err := os.Remove(filepath.Join(stateDir, "fail-restart")); err != nil {
		t.Fatal(err)
	}

	if err := os.Remove(config + ".ready"); err != nil {
		t.Fatal(err)
	}
	runInstaller(t, projectRoot, testRoot, fakeBinDir, stateDir, candidateV3, false)
	assertContains(t, installedBinary, "VERSION=v2")
	assertFileEquals(t, config, customConfig)
}

// TestInstallerRejectsConfigurationSymlink proves a site file cannot redirect a privileged write.
func TestInstallerRejectsConfigurationSymlink(t *testing.T) {
	projectRoot := projectRoot(t)
	testRoot := t.TempDir()
	fakeBinDir := filepath.Join(t.TempDir(), "bin")
	stateDir := filepath.Join(t.TempDir(), "state")
	mustMkdirAll(t, fakeBinDir)
	mustMkdirAll(t, stateDir)
	writeFakeSystemTools(t, fakeBinDir)

	configDir := filepath.Join(testRoot, "etc/automation-gateway")
	mustMkdirAll(t, configDir)
	external := filepath.Join(t.TempDir(), "external-config")
	mustWriteFile(t, external, "external\n", 0o600)
	if err := os.Symlink(external, filepath.Join(configDir, "config.yaml")); err != nil {
		t.Fatal(err)
	}

	candidate := writeCandidate(t, t.TempDir(), "v1")
	runInstaller(t, projectRoot, testRoot, fakeBinDir, stateDir, candidate, false)
	assertFileEquals(t, external, "external\n")
}

// projectRoot returns the repository root used by the test process.
func projectRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs("..")
	if err != nil {
		t.Fatal(err)
	}
	return root
}

// runInstaller invokes the real shell installer with only its destination and system tools isolated.
func runInstaller(t *testing.T, projectRoot, testRoot, fakeBinDir, stateDir, candidate string, wantSuccess bool, extraArgs ...string) {
	t.Helper()
	marker := filepath.Join(testRoot, ".homeauth-install-test-root")
	if _, err := os.Stat(marker); os.IsNotExist(err) {
		mustWriteFile(t, marker, "isolated installer test root\n", 0o600)
	} else if err != nil {
		t.Fatal(err)
	}
	args := []string{filepath.Join(projectRoot, "scripts/install.sh"), "--binary", candidate}
	args = append(args, extraArgs...)
	cmd := exec.Command("bash", args...)
	cmd.Env = append(os.Environ(),
		"HOMEAUTH_INSTALL_TESTING=1",
		"HOMEAUTH_INSTALL_TEST_ROOT="+testRoot,
		"HOMEAUTH_INSTALL_TEST_STATE="+stateDir,
		"PATH="+fakeBinDir+":"+os.Getenv("PATH"),
	)
	output, err := cmd.CombinedOutput()
	if wantSuccess && err != nil {
		t.Fatalf("installer failed: %v\n%s", err, output)
	}
	if !wantSuccess && err == nil {
		t.Fatalf("installer unexpectedly succeeded:\n%s", output)
	}
}

// writeCandidate creates an executable that models only the gateway's configuration-check interface.
func writeCandidate(t *testing.T, directory, version string) string {
	t.Helper()
	path := filepath.Join(directory, "automation-gateway")
	content := fmt.Sprintf(`#!/bin/sh
VERSION=%s
config=
while [ "$#" -gt 0 ]; do
    case "$1" in
        --config) config=$2; shift 2 ;;
        --check) shift ;;
        *) shift ;;
    esac
done
[ -n "$config" ] && [ -f "${config}.ready" ]
`, version)
	mustWriteFile(t, path, content, 0o755)
	return path
}

// writeFakeSystemTools creates stateful systemctl and successful systemd-analyze stand-ins.
func writeFakeSystemTools(t *testing.T, directory string) {
	t.Helper()
	systemctl := `#!/bin/sh
set -eu
state=${HOMEAUTH_INSTALL_TEST_STATE:?}
case "$1" in
    is-active) [ -f "$state/active" ] ;;
    is-enabled) [ -f "$state/enabled" ] ;;
    daemon-reload) printf '%s\n' 'daemon-reload' >> "$state/systemctl.log" ;;
    enable)
        printf '%s\n' 'enable --now automation-gateway' >> "$state/systemctl.log"
        : > "$state/enabled"
        : > "$state/active"
        ;;
    restart)
        printf '%s\n' 'restart automation-gateway' >> "$state/systemctl.log"
        [ ! -f "$state/fail-restart" ]
        [ -f "$state/active" ]
        ;;
    *) exit 64 ;;
esac
`
	analyze := `#!/bin/sh
set -eu
[ "$1" = verify ]
printf '%s\n' "verify $2" >> "${HOMEAUTH_INSTALL_TEST_STATE:?}/analyze.log"
`
	mustWriteFile(t, filepath.Join(directory, "systemctl"), systemctl, 0o755)
	mustWriteFile(t, filepath.Join(directory, "systemd-analyze"), analyze, 0o755)
}

// mustCopyFile copies a regular test artifact while preserving explicit test control over rollback.
func mustCopyFile(t *testing.T, source, target string, mode os.FileMode) {
	t.Helper()
	data, err := os.ReadFile(source)
	if err != nil {
		t.Fatal(err)
	}
	mustWriteFile(t, target, string(data), mode)
}

// mustWriteFile writes a test fixture or terminates the test.
func mustWriteFile(t *testing.T, path, content string, mode os.FileMode) {
	t.Helper()
	mustMkdirAll(t, filepath.Dir(path))
	if err := os.WriteFile(path, []byte(content), mode); err != nil {
		t.Fatal(err)
	}
}

// mustMkdirAll creates a fixture directory or terminates the test.
func mustMkdirAll(t *testing.T, path string) {
	t.Helper()
	if err := os.MkdirAll(path, 0o755); err != nil {
		t.Fatal(err)
	}
}

// mustExist requires a path to exist.
func mustExist(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("expected %s to exist: %v", path, err)
	}
}

// assertContains requires a file to contain a selected string.
func assertContains(t *testing.T, path, needle string) {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(content), needle) {
		t.Fatalf("%s does not contain %q", path, needle)
	}
}

// assertFileEquals requires a file's complete content to match.
func assertFileEquals(t *testing.T, path, want string) {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(content) != want {
		t.Fatalf("%s content = %q, want %q", path, content, want)
	}
}

// countLogLine counts exact action records in a fake systemctl log.
func countLogLine(t *testing.T, path, line string) int {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	count := 0
	for _, candidate := range strings.Split(strings.TrimSpace(string(content)), "\n") {
		if candidate == line {
			count++
		}
	}
	return count
}
