#!/usr/bin/env bash
# File: scripts/package_release.sh
# Purpose: Build versioned cross-platform gateway binaries and minimal installation packages.
# Generated by: aiAgentTseiman (Hermes Agent)
# Generated on: 2026-10-09

set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
PROJECT_ROOT="$(CDPATH= cd "$SCRIPT_DIR/.." && pwd -P)"
OUTPUT_DIR="${PACKAGE_OUTPUT_DIR:-$PROJECT_ROOT}"
ALLOW_DIRTY="${PACKAGE_ALLOW_DIRTY:-0}"
BUILD_DEB=false
STAGE_DIR=""
WINDOWS_STAGE_DIR=""
DEB_STAGE_DIR=""
LINUX_BUILD_TEMP=""

usage() {
    cat <<'USAGE'
Usage: ./scripts/package_release.sh ARCH [--deb]

Build release material for one target architecture.

Architectures:
  armhf, armv7   Linux ARMv7 (GOARCH=arm GOARM=7; Debian armhf)
  i386, 386      Linux 32-bit x86 (GOARCH=386; Debian i386)
  arm64          Linux 64-bit ARM (GOARCH=arm64; Debian arm64)
  amd64, x86_64  Linux 64-bit Intel/AMD (GOARCH=amd64; Debian amd64)

Outputs are written to the repository root by default:
  automation-gateway-linux-ARCH
  automation-gateway-linux-ARCH.sha256
  automation-gateway-VERSION-linux-ARCH.tar.gz
  automation-gateway-VERSION-linux-ARCH.tar.gz.sha256

A Windows executable and ZIP are emitted only when the current source tree
successfully cross-compiles for the corresponding Windows architecture.
Pass --deb to additionally create a Debian package and checksum.
USAGE
}

log() {
    printf '[package] %s\n' "$*"
}

warn() {
    printf '[package] WARNING: %s\n' "$*" >&2
}

die() {
    printf '[package] ERROR: %s\n' "$*" >&2
    exit 1
}

cleanup() {
    if [[ -n "$STAGE_DIR" && -d "$STAGE_DIR" ]]; then
        rm -rf "$STAGE_DIR"
    fi
    if [[ -n "$WINDOWS_STAGE_DIR" && -d "$WINDOWS_STAGE_DIR" ]]; then
        rm -rf "$WINDOWS_STAGE_DIR"
    fi
    if [[ -n "$DEB_STAGE_DIR" && -d "$DEB_STAGE_DIR" ]]; then
        rm -rf "$DEB_STAGE_DIR"
    fi
    if [[ -n "$LINUX_BUILD_TEMP" && -f "$LINUX_BUILD_TEMP" ]]; then
        rm -f "$LINUX_BUILD_TEMP"
    fi
}
trap cleanup EXIT

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

write_sha256() {
    local path="$1"
    local directory base
    directory="$(dirname "$path")"
    base="$(basename "$path")"
    if command -v sha256sum >/dev/null 2>&1; then
        (cd "$directory" && sha256sum "$base" > "${base}.sha256")
    elif command -v shasum >/dev/null 2>&1; then
        (cd "$directory" && shasum -a 256 "$base" > "${base}.sha256")
    else
        die "sha256sum or shasum is required"
    fi
}

safe_filename_version() {
    printf '%s' "$1" | tr -c '0-9A-Za-z._-' '_'
}

repository_version() {
    local exact_tag
    if exact_tag="$(git -C "$PROJECT_ROOT" describe --tags --exact-match HEAD 2>/dev/null)"; then
        printf '%s\n' "$exact_tag"
    else
        git -C "$PROJECT_ROOT" rev-parse --short=12 HEAD
    fi
}

debian_version() {
    local source="$1"
    local candidate
    if [[ "$source" =~ ^v[0-9] ]]; then
        candidate="${source#v}"
    elif [[ "$source" =~ ^[0-9] ]]; then
        candidate="$source"
    else
        candidate="0.0.0+git${source}"
    fi
    candidate="$(printf '%s' "$candidate" | tr -c '0-9A-Za-z.+:~-' '+')"
    printf '%s\n' "$candidate"
}

copy_linux_material() {
    local binary="$1"
    local destination="$2"
    local install_text="$destination/INSTALL.txt"

    install -d -m 0755 "$destination/scripts" "$destination/configs" "$destination/systemd"
    install -m 0755 "$binary" "$destination/$LINUX_BINARY_NAME"
    install -m 0755 "$PROJECT_ROOT/scripts/install.sh" "$destination/scripts/install.sh"
    install -m 0644 "$PROJECT_ROOT/configs/config.example.yaml" "$destination/configs/config.example.yaml"
    install -m 0644 "$PROJECT_ROOT/configs/mib-metadata.example.json" "$destination/configs/mib-metadata.example.json"
    install -m 0644 "$PROJECT_ROOT/systemd/automation-gateway.service" "$destination/systemd/automation-gateway.service"
    install -m 0644 "$PROJECT_ROOT/LICENSE" "$destination/LICENSE"
    cat > "$install_text" <<EOF_INSTALL
HomeAutomationMonitorGW $VERSION for Linux $ARCH_LABEL

Verify the adjacent release checksum before extracting this archive.
From the extracted directory install the prebuilt binary with:

  sudo ./scripts/install.sh --binary=./$LINUX_BINARY_NAME

On a first installation, configure /etc/automation-gateway and provision the
site-owned token and TLS files before starting the service. Existing site-owned
configuration, tokens, secrets, and TLS files are preserved during updates.
EOF_INSTALL
    chmod 0644 "$install_text"
}

build_windows_package_if_supported() {
    local windows_binary_name windows_binary_path windows_log windows_archive
    local windows_install

    windows_binary_name="automation-gateway-windows-${ARCH_LABEL}.exe"
    windows_binary_path="$OUTPUT_DIR/$windows_binary_name"
    windows_log="$(mktemp "${PACKAGE_TMPDIR:-/tmp}/automation-gateway.windows.XXXXXX")"

    log "probing Windows $ARCH_LABEL cross-build support"
    if [[ -n "$GOARM_VALUE" ]]; then
        if ! (cd "$PROJECT_ROOT" && CGO_ENABLED=0 GOOS=windows GOARCH="$GOARCH_VALUE" GOARM="$GOARM_VALUE" GOPROXY=off go build -trimpath -ldflags "$LDFLAGS" -o "$windows_binary_path" ./cmd/gateway) >"$windows_log" 2>&1; then
            warn "Windows $ARCH_LABEL build is not supported by the current source; ZIP skipped"
            rm -f "$windows_binary_path" "$windows_log"
            return 0
        fi
    else
        if ! (cd "$PROJECT_ROOT" && CGO_ENABLED=0 GOOS=windows GOARCH="$GOARCH_VALUE" GOPROXY=off go build -trimpath -ldflags "$LDFLAGS" -o "$windows_binary_path" ./cmd/gateway) >"$windows_log" 2>&1; then
            warn "Windows $ARCH_LABEL build is not supported by the current source; ZIP skipped"
            rm -f "$windows_binary_path" "$windows_log"
            return 0
        fi
    fi
    rm -f "$windows_log"
    chmod 0755 "$windows_binary_path"
    write_sha256 "$windows_binary_path"

    WINDOWS_STAGE_DIR="$(mktemp -d "${PACKAGE_TMPDIR:-/tmp}/automation-gateway.windows-stage.XXXXXX")"
    install -m 0755 "$windows_binary_path" "$WINDOWS_STAGE_DIR/$windows_binary_name"
    install -m 0644 "$PROJECT_ROOT/LICENSE" "$WINDOWS_STAGE_DIR/LICENSE"
    windows_install="$WINDOWS_STAGE_DIR/INSTALL-WINDOWS.txt"
    cat > "$windows_install" <<EOF_WINDOWS
HomeAutomationMonitorGW $VERSION for Windows $ARCH_LABEL

Run $windows_binary_name --version to inspect the embedded release version.
The Linux systemd installer is intentionally not included in this ZIP.
Provide Windows-native service management and protected configuration paths.
EOF_WINDOWS
    chmod 0644 "$windows_install"

    windows_archive="$OUTPUT_DIR/automation-gateway-${FILENAME_VERSION}-windows-${ARCH_LABEL}.zip"
    rm -f "$windows_archive"
    if command -v zip >/dev/null 2>&1; then
        (cd "$WINDOWS_STAGE_DIR" && zip -q -r "$windows_archive" .)
    elif command -v python3 >/dev/null 2>&1; then
        (cd "$WINDOWS_STAGE_DIR" && python3 -m zipfile -c "$windows_archive" ./*)
    else
        die "Windows build succeeded, but zip or python3 is required to create its ZIP"
    fi
    write_sha256 "$windows_archive"
    log "created $(basename "$windows_archive")"
}

build_debian_package() {
    local deb_version deb_name deb_path control postinst prerm postrm unit_target
    require_command dpkg-deb
    deb_version="$(debian_version "$VERSION")"
    deb_name="automation-gateway_${deb_version}_${DEB_ARCH}.deb"
    deb_path="$OUTPUT_DIR/$deb_name"
    DEB_STAGE_DIR="$(mktemp -d "${PACKAGE_TMPDIR:-/tmp}/automation-gateway.deb-stage.XXXXXX")"
    chmod 0755 "$DEB_STAGE_DIR"

    install -d -m 0755 \
        "$DEB_STAGE_DIR/DEBIAN" \
        "$DEB_STAGE_DIR/usr/sbin" \
        "$DEB_STAGE_DIR/usr/share/automation-gateway" \
        "$DEB_STAGE_DIR/usr/share/doc/automation-gateway" \
        "$DEB_STAGE_DIR/lib/systemd/system"
    install -m 0755 "$LINUX_BINARY_PATH" "$DEB_STAGE_DIR/usr/sbin/automation-gateway"
    install -m 0644 "$PROJECT_ROOT/configs/config.example.yaml" "$DEB_STAGE_DIR/usr/share/automation-gateway/config.example.yaml"
    install -m 0644 "$PROJECT_ROOT/configs/mib-metadata.example.json" "$DEB_STAGE_DIR/usr/share/automation-gateway/mib-metadata.example.json"
    install -m 0644 "$PROJECT_ROOT/LICENSE" "$DEB_STAGE_DIR/usr/share/doc/automation-gateway/copyright"

    unit_target="$DEB_STAGE_DIR/lib/systemd/system/automation-gateway.service"
    while IFS= read -r line || [[ -n "$line" ]]; do
        case "$line" in
            ExecStart=*) printf '%s\n' 'ExecStart=/usr/sbin/automation-gateway --config /etc/automation-gateway/config.yaml' ;;
            *) printf '%s\n' "$line" ;;
        esac
    done < "$PROJECT_ROOT/systemd/automation-gateway.service" > "$unit_target"
    chmod 0644 "$unit_target"

    control="$DEB_STAGE_DIR/DEBIAN/control"
    cat > "$control" <<EOF_CONTROL
Package: automation-gateway
Version: $deb_version
Section: net
Priority: optional
Architecture: $DEB_ARCH
Maintainer: aiAgentTseiman <ai-agent.tseiman@tseiman.de>
Depends: adduser, systemd
Description: Read-only home and industrial automation monitoring gateway
 Collects configured NUT and SNMPv3 metrics into an authenticated HTTPS cache
 for monitoring systems such as Zabbix.
EOF_CONTROL
    chmod 0644 "$control"

    postinst="$DEB_STAGE_DIR/DEBIAN/postinst"
    cat > "$postinst" <<'EOF_POSTINST'
#!/bin/sh
set -e

die() {
    echo "automation-gateway: $*" >&2
    exit 1
}

reject_symlink() {
    if [ -L "$1" ]; then
        die "refusing symlink: $1"
    fi
}

require_directory_or_missing() {
    reject_symlink "$1"
    if [ -e "$1" ] && [ ! -d "$1" ]; then
        die "expected directory: $1"
    fi
}

install_default_if_missing() {
    source_path="$1"
    target_path="$2"
    reject_symlink "$source_path"
    [ -f "$source_path" ] || die "missing regular package default: $source_path"
    reject_symlink "$target_path"
    if [ -e "$target_path" ]; then
        [ -f "$target_path" ] || die "expected regular file: $target_path"
        return 0
    fi
    install -o root -g automation-gateway -m 0640 "$source_path" "$target_path"
}

if ! getent group automation-gateway >/dev/null; then
    addgroup --system automation-gateway
fi
if ! getent passwd automation-gateway >/dev/null; then
    adduser --system --ingroup automation-gateway --no-create-home --home /nonexistent --shell /usr/sbin/nologin automation-gateway
fi
for directory in /etc/automation-gateway /etc/automation-gateway/secrets /etc/automation-gateway/tokens; do
    require_directory_or_missing "$directory"
done
install -d -o root -g automation-gateway -m 0750 /etc/automation-gateway /etc/automation-gateway/secrets /etc/automation-gateway/tokens
install_default_if_missing /usr/share/automation-gateway/config.example.yaml /etc/automation-gateway/config.yaml
install_default_if_missing /usr/share/automation-gateway/mib-metadata.example.json /etc/automation-gateway/mib-metadata.json
if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload || true
fi
exit 0
EOF_POSTINST
    chmod 0755 "$postinst"

    prerm="$DEB_STAGE_DIR/DEBIAN/prerm"
    cat > "$prerm" <<'EOF_PRERM'
#!/bin/sh
set -e
case "${1:-}" in
    remove|deconfigure)
        if command -v systemctl >/dev/null 2>&1; then
            systemctl stop automation-gateway.service || true
        fi
        ;;
esac
exit 0
EOF_PRERM
    chmod 0755 "$prerm"

    postrm="$DEB_STAGE_DIR/DEBIAN/postrm"
    cat > "$postrm" <<'EOF_POSTRM'
#!/bin/sh
set -e
if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload || true
fi
exit 0
EOF_POSTRM
    chmod 0755 "$postrm"

    rm -f "$deb_path"
    dpkg-deb --root-owner-group --build "$DEB_STAGE_DIR" "$deb_path" >/dev/null
    write_sha256 "$deb_path"
    log "created $deb_name"
}

[[ $# -ge 1 && $# -le 2 ]] || { usage >&2; exit 2; }
TARGET_ARCH="$1"
if [[ $# -eq 2 ]]; then
    [[ "$2" == "--deb" ]] || die "unknown option: $2"
    BUILD_DEB=true
fi

case "$TARGET_ARCH" in
    armhf|armv7)
        ARCH_LABEL="armv7"
        GOARCH_VALUE="arm"
        GOARM_VALUE="7"
        DEB_ARCH="armhf"
        ;;
    i386|386)
        ARCH_LABEL="386"
        GOARCH_VALUE="386"
        GOARM_VALUE=""
        DEB_ARCH="i386"
        ;;
    arm64)
        ARCH_LABEL="arm64"
        GOARCH_VALUE="arm64"
        GOARM_VALUE=""
        DEB_ARCH="arm64"
        ;;
    amd64|x86_64)
        ARCH_LABEL="amd64"
        GOARCH_VALUE="amd64"
        GOARM_VALUE=""
        DEB_ARCH="amd64"
        ;;
    *)
        die "unsupported target architecture: $TARGET_ARCH"
        ;;
esac

require_command git
require_command go
require_command install
require_command mktemp
require_command tar
require_command tr

[[ -d "$OUTPUT_DIR" ]] || mkdir -p "$OUTPUT_DIR"
OUTPUT_DIR="$(CDPATH= cd "$OUTPUT_DIR" && pwd -P)"

if [[ "$ALLOW_DIRTY" != "1" ]]; then
    [[ -z "$(git -C "$PROJECT_ROOT" status --porcelain --untracked-files=normal)" ]] || die "worktree changes must be committed before packaging"
fi

VERSION="$(repository_version)"
[[ "$VERSION" =~ ^[0-9A-Za-z._+-]+$ ]] || die "tag/version contains unsupported characters: $VERSION"
FILENAME_VERSION="$(safe_filename_version "$VERSION")"
COMMIT="$(git -C "$PROJECT_ROOT" rev-parse HEAD)"
BUILD_TIME="$(git -C "$PROJECT_ROOT" show -s --format=%cI HEAD)"
[[ "$COMMIT" =~ ^[0-9a-f]{40}$ ]] || die "invalid Git commit identifier"
[[ "$BUILD_TIME" =~ ^[0-9T:+-]+$ ]] || die "invalid Git commit timestamp"
LDFLAGS="-s -w -X main.version=$VERSION -X main.commit=$COMMIT -X main.buildTime=$BUILD_TIME"

log "version: $VERSION"
log "downloading checksummed Go module dependencies"
(cd "$PROJECT_ROOT" && go mod download)

LINUX_BINARY_NAME="automation-gateway-linux-${ARCH_LABEL}"
LINUX_BINARY_PATH="$OUTPUT_DIR/$LINUX_BINARY_NAME"
LINUX_BUILD_TEMP="$(mktemp "${PACKAGE_TMPDIR:-/tmp}/automation-gateway.linux.XXXXXX")"
if [[ -n "$GOARM_VALUE" ]]; then
    (cd "$PROJECT_ROOT" && CGO_ENABLED=0 GOOS=linux GOARCH="$GOARCH_VALUE" GOARM="$GOARM_VALUE" GOPROXY=off go build -trimpath -ldflags "$LDFLAGS" -o "$LINUX_BUILD_TEMP" ./cmd/gateway)
else
    (cd "$PROJECT_ROOT" && CGO_ENABLED=0 GOOS=linux GOARCH="$GOARCH_VALUE" GOPROXY=off go build -trimpath -ldflags "$LDFLAGS" -o "$LINUX_BUILD_TEMP" ./cmd/gateway)
fi
install -m 0755 "$LINUX_BUILD_TEMP" "$LINUX_BINARY_PATH"
rm -f "$LINUX_BUILD_TEMP"
LINUX_BUILD_TEMP=""
write_sha256 "$LINUX_BINARY_PATH"
log "created $LINUX_BINARY_NAME"

STAGE_DIR="$(mktemp -d "${PACKAGE_TMPDIR:-/tmp}/automation-gateway.linux-stage.XXXXXX")"
copy_linux_material "$LINUX_BINARY_PATH" "$STAGE_DIR"
LINUX_ARCHIVE="$OUTPUT_DIR/automation-gateway-${FILENAME_VERSION}-linux-${ARCH_LABEL}.tar.gz"
rm -f "$LINUX_ARCHIVE"
tar -C "$STAGE_DIR" -czf "$LINUX_ARCHIVE" .
write_sha256 "$LINUX_ARCHIVE"
log "created $(basename "$LINUX_ARCHIVE")"

build_windows_package_if_supported
if [[ "$BUILD_DEB" == "true" ]]; then
    build_debian_package
fi

log "release material written to $OUTPUT_DIR"
