// File: scripts/package_release_test.go
// Purpose: Verify reproducible cross-build release archives and embedded Git version metadata.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-09

package scripts

import (
	"archive/tar"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

func TestPackageReleaseBuildsMinimalLinuxBundle(t *testing.T) {
	root := projectRoot(t)
	output := t.TempDir()
	fakeBin := t.TempDir()
	writeFakePackageGo(t, fakeBin)

	cmd := exec.Command("bash", filepath.Join(root, "scripts/package_release.sh"), "arm64")
	cmd.Dir = root
	cmd.Env = append(os.Environ(),
		"PACKAGE_OUTPUT_DIR="+output,
		"PACKAGE_ALLOW_DIRTY=1",
		"PATH="+fakeBin+":"+os.Getenv("PATH"),
	)
	combined, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("package_release.sh failed: %v\n%s", err, combined)
	}

	version := repositoryVersion(t, root)
	binaryName := "automation-gateway-linux-arm64"
	binaryPath := filepath.Join(output, binaryName)
	archiveName := fmt.Sprintf("automation-gateway-%s-linux-arm64.tar.gz", filenameVersion(version))
	archivePath := filepath.Join(output, archiveName)

	assertSHA256File(t, binaryPath, binaryPath+".sha256")
	assertSHA256File(t, archivePath, archivePath+".sha256")

	versionOutput, err := exec.Command(binaryPath, "--version").CombinedOutput()
	if err != nil {
		t.Fatalf("packaged binary --version failed: %v\n%s", err, versionOutput)
	}
	if !strings.Contains(string(versionOutput), "automation-gateway "+version+" ") {
		t.Fatalf("version output %q does not contain %q", versionOutput, version)
	}

	gotEntries := tarGzipEntries(t, archivePath)
	wantEntries := []string{
		"INSTALL.txt",
		"LICENSE",
		binaryName,
		"configs/config.example.yaml",
		"configs/mib-metadata.example.json",
		"scripts/install.sh",
		"systemd/automation-gateway.service",
	}
	sort.Strings(wantEntries)
	if strings.Join(gotEntries, "\n") != strings.Join(wantEntries, "\n") {
		t.Fatalf("archive entries:\n%s\nwant:\n%s", strings.Join(gotEntries, "\n"), strings.Join(wantEntries, "\n"))
	}

	matches, err := filepath.Glob(filepath.Join(output, "*.zip"))
	if err != nil {
		t.Fatal(err)
	}
	if len(matches) != 0 {
		t.Fatalf("unexpected Windows archive for unsupported build: %v", matches)
	}
}

func TestPackageReleaseBuildsDebianPackage(t *testing.T) {
	if _, err := exec.LookPath("dpkg-deb"); err != nil {
		t.Skip("dpkg-deb is not available")
	}
	root := projectRoot(t)
	output := t.TempDir()
	fakeBin := t.TempDir()
	writeFakePackageGo(t, fakeBin)

	cmd := exec.Command("bash", filepath.Join(root, "scripts/package_release.sh"), "arm64", "--deb")
	cmd.Dir = root
	cmd.Env = append(os.Environ(),
		"PACKAGE_OUTPUT_DIR="+output,
		"PACKAGE_ALLOW_DIRTY=1",
		"PATH="+fakeBin+":"+os.Getenv("PATH"),
	)
	combined, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("package_release.sh --deb failed: %v\n%s", err, combined)
	}

	matches, err := filepath.Glob(filepath.Join(output, "*.deb"))
	if err != nil {
		t.Fatal(err)
	}
	if len(matches) != 1 {
		t.Fatalf("Debian packages = %v, want exactly one", matches)
	}
	debPath := matches[0]
	assertSHA256File(t, debPath, debPath+".sha256")

	fields, err := exec.Command("dpkg-deb", "-f", debPath, "Package", "Architecture", "Version").CombinedOutput()
	if err != nil {
		t.Fatalf("dpkg-deb metadata failed: %v\n%s", err, fields)
	}
	metadata := string(fields)
	version := repositoryVersion(t, root)
	wantDebianVersion := testDebianVersion(version)
	if !strings.Contains(metadata, "Package: automation-gateway") || !strings.Contains(metadata, "Architecture: arm64") || !strings.Contains(metadata, "Version: "+wantDebianVersion) {
		t.Fatalf("unexpected Debian metadata:\n%s", metadata)
	}

	extracted := t.TempDir()
	if output, err := exec.Command("dpkg-deb", "-x", debPath, extracted).CombinedOutput(); err != nil {
		t.Fatalf("dpkg-deb extraction failed: %v\n%s", err, output)
	}
	for _, relative := range []string{
		"usr/sbin/automation-gateway",
		"usr/share/automation-gateway/config.example.yaml",
		"usr/share/automation-gateway/mib-metadata.example.json",
		"lib/systemd/system/automation-gateway.service",
	} {
		if _, err := os.Stat(filepath.Join(extracted, relative)); err != nil {
			t.Fatalf("missing Debian payload %s: %v", relative, err)
		}
	}
	controlDir := t.TempDir()
	if output, err := exec.Command("dpkg-deb", "-e", debPath, controlDir).CombinedOutput(); err != nil {
		t.Fatalf("dpkg-deb control extraction failed: %v\n%s", err, output)
	}
	for _, scriptName := range []string{"postinst", "prerm", "postrm"} {
		scriptPath := filepath.Join(controlDir, scriptName)
		if output, err := exec.Command("sh", "-n", scriptPath).CombinedOutput(); err != nil {
			t.Fatalf("%s syntax failed: %v\n%s", scriptName, err, output)
		}
	}
	postinst, err := os.ReadFile(filepath.Join(controlDir, "postinst"))
	if err != nil {
		t.Fatal(err)
	}
	for _, required := range []string{"reject_symlink", "refusing symlink", "install_default_if_missing"} {
		if !strings.Contains(string(postinst), required) {
			t.Fatalf("Debian postinst lacks %q protection:\n%s", required, postinst)
		}
	}

	if err := filepath.Walk(extracted, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if strings.HasSuffix(info.Name(), ".go") {
			t.Fatalf("Go source leaked into Debian package: %s", path)
		}
		return nil
	}); err != nil {
		t.Fatal(err)
	}
}

func TestPackageReleaseRejectsUnsupportedArchitecture(t *testing.T) {
	root := projectRoot(t)
	cmd := exec.Command("bash", filepath.Join(root, "scripts/package_release.sh"), "mips64")
	cmd.Dir = root
	cmd.Env = append(os.Environ(), "PACKAGE_OUTPUT_DIR="+t.TempDir(), "PACKAGE_ALLOW_DIRTY=1")
	combined, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("unsupported architecture succeeded:\n%s", combined)
	}
	if !strings.Contains(string(combined), "unsupported target architecture") {
		t.Fatalf("unexpected diagnostic: %s", combined)
	}
}

func repositoryVersion(t *testing.T, root string) string {
	t.Helper()
	if output, err := exec.Command("git", "-C", root, "describe", "--tags", "--exact-match", "HEAD").Output(); err == nil {
		return strings.TrimSpace(string(output))
	}
	output, err := exec.Command("git", "-C", root, "rev-parse", "--short=12", "HEAD").Output()
	if err != nil {
		t.Fatal(err)
	}
	return strings.TrimSpace(string(output))
}

func testDebianVersion(version string) string {
	if len(version) > 1 && version[0] == 'v' && version[1] >= '0' && version[1] <= '9' {
		return version[1:]
	}
	if len(version) > 0 && version[0] >= '0' && version[0] <= '9' {
		return version
	}
	return "0.0.0+git" + version
}

func filenameVersion(version string) string {
	var result strings.Builder
	for _, character := range version {
		if (character >= 'a' && character <= 'z') || (character >= 'A' && character <= 'Z') || (character >= '0' && character <= '9') || character == '.' || character == '_' || character == '-' {
			result.WriteRune(character)
		} else {
			result.WriteByte('_')
		}
	}
	return result.String()
}

func assertSHA256File(t *testing.T, payloadPath, checksumPath string) {
	t.Helper()
	payload, err := os.ReadFile(payloadPath)
	if err != nil {
		t.Fatal(err)
	}
	checksum, err := os.ReadFile(checksumPath)
	if err != nil {
		t.Fatal(err)
	}
	fields := strings.Fields(string(checksum))
	if len(fields) != 2 || fields[1] != filepath.Base(payloadPath) {
		t.Fatalf("invalid checksum file %s: %q", checksumPath, checksum)
	}
	sum := sha256.Sum256(payload)
	if fields[0] != hex.EncodeToString(sum[:]) {
		t.Fatalf("checksum mismatch for %s", payloadPath)
	}
}

func tarGzipEntries(t *testing.T, archivePath string) []string {
	t.Helper()
	file, err := os.Open(archivePath)
	if err != nil {
		t.Fatal(err)
	}
	defer file.Close()
	compressed, err := gzip.NewReader(file)
	if err != nil {
		t.Fatal(err)
	}
	defer compressed.Close()
	reader := tar.NewReader(compressed)
	var entries []string
	for {
		header, err := reader.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			t.Fatal(err)
		}
		name := strings.TrimPrefix(header.Name, "./")
		if name == "" || strings.HasSuffix(name, "/") {
			continue
		}
		if strings.HasSuffix(name, ".go") {
			t.Fatalf("source file leaked into release archive: %s", name)
		}
		entries = append(entries, name)
	}
	sort.Strings(entries)
	return entries
}

func writeFakePackageGo(t *testing.T, directory string) {
	t.Helper()
	path := filepath.Join(directory, "go")
	content := `#!/usr/bin/env python3
import os
import re
import stat
import sys

if os.environ.get("GOOS") == "windows":
    print("Windows build intentionally unsupported by test fixture", file=sys.stderr)
    sys.exit(1)

args = sys.argv[1:]
if args == ["mod", "download"]:
    sys.exit(0)
output = args[args.index("-o") + 1]
ldflags = args[args.index("-ldflags") + 1]
def value(name):
    match = re.search(r"(?:^| )-X main\." + name + r"=([^ ]+)", ldflags)
    if not match:
        raise SystemExit("missing linker value " + name)
    return match.group(1)

script = "#!/bin/sh\nprintf '%s\\n' " + repr(
    "automation-gateway %s (commit %s, built %s)" % (value("version"), value("commit"), value("buildTime"))
) + "\n"
with open(output, "w", encoding="utf-8") as handle:
    handle.write(script)
os.chmod(output, os.stat(output).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
`
	if err := os.WriteFile(path, []byte(content), 0o755); err != nil {
		t.Fatal(err)
	}
}
