// File: internal/config/config_test.go
// Purpose: Verify generic source parsing, validation, defaults, and secret-file safeguards.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package config

import (
	"fmt"
	"net/netip"
	"os"
	"path/filepath"
	"strings"
	"syscall"
	"testing"
	"time"
)

func writeSecret(t *testing.T, dir, name, value string) string {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(value+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

func writeConfigFile(t *testing.T, dir, body string) string {
	t.Helper()
	path := filepath.Join(dir, "config.yaml")
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

func baseYAML(tokens []string, clients []string) string {
	var b strings.Builder
	b.WriteString("server:\n  listen: '127.0.0.1:8443'\n  certificate: '/tmp/cert.pem'\n  private_key: '/tmp/key.pem'\nauthentication:\n  bearer_token_files:\n")
	for _, token := range tokens {
		b.WriteString("    - '" + token + "'\n")
	}
	b.WriteString("  allowed_clients:\n")
	for _, client := range clients {
		b.WriteString("    - '" + client + "'\n")
	}
	return b.String()
}

// TestLoadGenericMixedSourcesAndAuthentication verifies source defaults, independent secrets, multiple tokens, and normalized client prefixes.
func TestLoadGenericMixedSourcesAndAuthentication(t *testing.T) {
	d := t.TempDir()
	token1 := writeSecret(t, d, "token1", "first-token-value")
	token2 := writeSecret(t, d, "token2", "second-token-value")
	auth := writeSecret(t, d, "auth", "test-auth-passphrase")
	priv := writeSecret(t, d, "priv", "test-privacy-passphrase")
	body := baseYAML([]string{token1, token2}, []string{"192.0.2.5", "2001:db8::/64"}) + `sources:
  - name: quint-main
    driver: nut
    poll_interval: "10s"
    stale_after: "30s"
    nut:
      server: "127.0.0.1:3493"
      ups: "quint"
  - name: wago-main
    driver: snmp
    poll_interval: "30s"
    stale_after: "90s"
    snmp:
      address: "192.0.2.10"
      oids: ["1.3.6.1.2.1.1.3.0"]
      security:
        version: "3"
        username: "monitor"
        auth_protocol: "SHA"
        auth_passphrase_file: "` + auth + `"
        privacy_protocol: "DES"
        privacy_passphrase_file: "` + priv + `"
      discovery:
        enabled: true
        root_oids: ["1.3.6.1.2.1"]
`
	got, err := Load(writeConfigFile(t, d, body), true)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if len(got.Sources) != 2 || !got.Sources[0].Enabled || !got.Sources[1].Enabled {
		t.Fatalf("sources=%+v", got.Sources)
	}
	if got.Sources[0].Timeout.Duration != 5*time.Second || got.Sources[1].SNMP.Port != 161 {
		t.Fatalf("defaults not applied: %+v", got.Sources)
	}
	if got.Sources[1].SNMP.Discovery.MaxObjects != 2048 || got.Sources[1].SNMP.Discovery.Timeout.Duration != 2*time.Minute {
		t.Fatalf("discovery defaults=%+v", got.Sources[1].SNMP.Discovery)
	}
	if strings.Join(got.Secrets.BearerTokens, ",") != "first-token-value,second-token-value" {
		t.Fatalf("tokens=%q", got.Secrets.BearerTokens)
	}
	if got.Secrets.Sources["wago-main"].SNMPAuthPassphrase != "test-auth-passphrase" {
		t.Fatalf("source secrets=%+v", got.Secrets.Sources)
	}
	want := []netip.Prefix{netip.MustParsePrefix("192.0.2.5/32"), netip.MustParsePrefix("2001:db8::/64")}
	for i := range want {
		if got.Secrets.AllowedClients[i] != want[i] {
			t.Fatalf("allowed[%d]=%v want %v", i, got.Secrets.AllowedClients[i], want[i])
		}
	}
}

// TestDisabledSourceSkipsValuesAndFiles verifies disabled entries are completely inert while their recognized fields may contain invalid values.
func TestDisabledSourceSkipsValuesAndFiles(t *testing.T) {
	d := t.TempDir()
	token := writeSecret(t, d, "token", "test-token-value")
	body := baseYAML([]string{token}, []string{"127.0.0.1"}) + `sources:
  - name: "not/a/path"
    driver: unsupported
    enabled: false
    poll_interval: definitely-not-a-duration
    stale_after: -3s
    timeout: [wrong, type]
    nut:
      server: 123
      ups: {}
    snmp:
      address: not-an-ip
      metadata_file: /does/not/exist
      security:
        auth_passphrase_file: /does/not/exist
        privacy_passphrase_file: /does/not/exist
`
	got, err := Load(writeConfigFile(t, d, body), true)
	if err != nil {
		t.Fatalf("disabled source was validated: %v", err)
	}
	if len(got.Sources) != 1 || got.Sources[0].Enabled {
		t.Fatalf("sources=%+v", got.Sources)
	}

	body = strings.Replace(body, "      server: 123", "      server: 123\n      typo: true", 1)
	if _, err := Load(writeConfigFile(t, d, body), true); err == nil || !strings.Contains(err.Error(), "typo") {
		t.Fatalf("disabled source unknown key accepted: %v", err)
	}
}

// TestSourceValidation verifies active source names, uniqueness, drivers, and exactly one matching nested configuration.
func TestSourceValidation(t *testing.T) {
	valid := Config{
		Server:         Server{Listen: ":8443", Certificate: "/cert", PrivateKey: "/key"},
		Authentication: Authentication{BearerTokenFiles: []string{"/token"}, AllowedClients: []string{"127.0.0.1"}},
		Sources:        []Source{{Name: "ups-1", Driver: "nut", Enabled: true, PollInterval: Duration{Duration: time.Second}, StaleAfter: Duration{Duration: 2 * time.Second}, Timeout: Duration{Duration: time.Second}, NUT: &NUTSource{Server: "127.0.0.1:3493", UPS: "quint"}}},
		Logging:        Logging{Level: "info"},
	}
	valid.defaults()
	if err := valid.Validate(); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"", ".", "..", "a/b", "a%2fb", "with space", strings.Repeat("a", 65)} {
		cfg := valid
		cfg.Sources = append([]Source(nil), valid.Sources...)
		cfg.Sources[0].Name = name
		if err := cfg.Validate(); err == nil {
			t.Errorf("unsafe name %q accepted", name)
		}
	}
	cfg := valid
	cfg.Sources = append(cfg.Sources, cfg.Sources[0])
	if err := cfg.Validate(); err == nil || !strings.Contains(err.Error(), "duplicate") {
		t.Fatalf("duplicate source error=%v", err)
	}
	cfg = valid
	cfg.Sources = append([]Source(nil), valid.Sources...)
	cfg.Sources[0].SNMP = &SNMPSource{}
	if err := cfg.Validate(); err == nil || !strings.Contains(err.Error(), "exactly") {
		t.Fatalf("mixed nested config error=%v", err)
	}
}

// TestAuthenticationValidationAndSecretDuplicates verifies non-empty auth lists and duplicate path, token, and normalized-client rejection.
func TestAuthenticationValidationAndSecretDuplicates(t *testing.T) {
	d := t.TempDir()
	token1 := writeSecret(t, d, "token1", "duplicate-token-value")
	token2 := writeSecret(t, d, "token2", "duplicate-token-value")
	for _, tc := range []struct {
		name, yaml, contains string
	}{
		{"no tokens", baseYAML(nil, []string{"127.0.0.1"}), "bearer_token_files"},
		{"no clients", baseYAML([]string{token1}, nil), "allowed_clients"},
		{"duplicate path", baseYAML([]string{token1, token1}, []string{"127.0.0.1"}), "duplicate"},
		{"duplicate token", baseYAML([]string{token1, token2}, []string{"127.0.0.1"}), "duplicate bearer token"},
		{"invalid client", baseYAML([]string{token1}, []string{"host.example"}), "allowed_clients"},
		{"duplicate client", baseYAML([]string{token1}, []string{"192.0.2.1", "192.0.2.1/32"}), "duplicate"},
		{"IPv4 host bits", baseYAML([]string{token1}, []string{"192.0.2.25/24"}), "host bits"},
		{"IPv6 host bits", baseYAML([]string{token1}, []string{"2001:db8::1/64"}), "host bits"},
		{"mapped IPv4 CIDR", baseYAML([]string{token1}, []string{"::ffff:192.0.2.0/120"}), "IPv4-mapped"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := Load(writeConfigFile(t, d, tc.yaml), true)
			if err == nil || !strings.Contains(err.Error(), tc.contains) {
				t.Fatalf("error=%v, want containing %q", err, tc.contains)
			}
		})
	}
}

// TestAuthenticationListBounds verifies configured policy size cannot amplify every request without limit.
func TestAuthenticationListBounds(t *testing.T) {
	base := Config{Server: Server{Listen: ":8443", Certificate: "/cert", PrivateKey: "/key"}, Logging: Logging{Level: "info"}}
	base.defaults()
	for index := 0; index < maxBearerTokenFiles; index++ {
		base.Authentication.BearerTokenFiles = append(base.Authentication.BearerTokenFiles, fmt.Sprintf("/token/%d", index))
	}
	for index := 0; index < maxAllowedClients; index++ {
		base.Authentication.AllowedClients = append(base.Authentication.AllowedClients, fmt.Sprintf("2001:db8::%x", index+1))
	}
	if err := base.Validate(); err != nil {
		t.Fatalf("maximum-sized policy rejected: %v", err)
	}
	tokensTooLarge := base
	tokensTooLarge.Authentication.BearerTokenFiles = append(append([]string(nil), base.Authentication.BearerTokenFiles...), "/token/overflow")
	if err := tokensTooLarge.Validate(); err == nil || !strings.Contains(err.Error(), "at most") {
		t.Fatalf("token overflow error=%v", err)
	}
	clientsTooLarge := base
	clientsTooLarge.Authentication.AllowedClients = append(append([]string(nil), base.Authentication.AllowedClients...), "2001:db8::ffff")
	if err := clientsTooLarge.Validate(); err == nil || !strings.Contains(err.Error(), "at most") {
		t.Fatalf("client overflow error=%v", err)
	}
}

// TestDisabledSourceRejectsDuplicateAndAmbiguousKeys verifies bypass decoding remains syntactically unambiguous.
func TestDisabledSourceRejectsDuplicateAndAmbiguousKeys(t *testing.T) {
	d := t.TempDir()
	token := writeSecret(t, d, "token", "test-token-value")
	for _, fragment := range []string{
		"    enabled: false\n    enabled: false\n",
		"    name: one\n    name: two\n    enabled: false\n",
		"    enabled: false\n    nut:\n      server: one\n      server: two\n",
		"    enabled: null\n",
	} {
		body := baseYAML([]string{token}, []string{"127.0.0.1"}) + "sources:\n  - " + strings.TrimPrefix(fragment, "    ")
		if _, err := Load(writeConfigFile(t, d, body), true); err == nil {
			t.Fatalf("ambiguous disabled source accepted:\n%s", fragment)
		}
	}
}

// TestZeroSourcesIsValid verifies authentication can protect a service with no active collectors.
func TestZeroSourcesIsValid(t *testing.T) {
	d := t.TempDir()
	token := writeSecret(t, d, "token", "test-token-value")
	got, err := Load(writeConfigFile(t, d, baseYAML([]string{token}, []string{"::1"})+"sources: []\n"), true)
	if err != nil || len(got.Sources) != 0 {
		t.Fatalf("config=%+v error=%v", got, err)
	}
}

// TestOmittedSourcesIsValid verifies an absent sources key creates no implicit collector.
func TestOmittedSourcesIsValid(t *testing.T) {
	d := t.TempDir()
	token := writeSecret(t, d, "token", "test-token-value")
	got, err := Load(writeConfigFile(t, d, baseYAML([]string{token}, []string{"127.0.0.1"})), true)
	if err != nil || len(got.Sources) != 0 {
		t.Fatalf("config=%+v error=%v", got, err)
	}
}

// TestMultipleSourcesUsingSameDriver verifies source identity is independent from driver type.
func TestMultipleSourcesUsingSameDriver(t *testing.T) {
	d := t.TempDir()
	token := writeSecret(t, d, "token", "test-token-value")
	body := baseYAML([]string{token}, []string{"127.0.0.1"}) + `sources:
  - name: ups-primary
    driver: nut
    poll_interval: 10s
    stale_after: 30s
    nut: {server: "127.0.0.1:3493", ups: primary}
  - name: ups-secondary
    driver: nut
    poll_interval: 15s
    stale_after: 45s
    nut: {server: "127.0.0.1:3494", ups: secondary}
`
	got, err := Load(writeConfigFile(t, d, body), true)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if len(got.Sources) != 2 || got.Sources[0].Driver != "nut" || got.Sources[1].Driver != "nut" {
		t.Fatalf("sources=%+v", got.Sources)
	}
}

// TestExampleConfigurationParses keeps the distributed operator example synchronized with the strict schema.
func TestExampleConfigurationParses(t *testing.T) {
	got, err := Load("../../configs/config.example.yaml", false)
	if err != nil {
		t.Fatalf("example configuration: %v", err)
	}
	if len(got.Sources) != 3 || !got.Sources[0].Enabled || !got.Sources[1].Enabled || got.Sources[2].Enabled {
		t.Fatalf("example sources=%+v", got.Sources)
	}
}

// TestReadSecretRejectsUnsafeFilesAndContent verifies no-follow, regular-file, size, and control-character safeguards.
func TestReadSecretRejectsUnsafeFilesAndContent(t *testing.T) {
	d := t.TempDir()
	regular := filepath.Join(d, "regular")
	if err := os.WriteFile(regular, []byte("safe-secret-value\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	link := filepath.Join(d, "link")
	if err := os.Symlink(regular, link); err != nil {
		t.Fatal(err)
	}
	if _, err := readSecret(link); err == nil {
		t.Fatal("symlink accepted")
	}
	large := filepath.Join(d, "large")
	if err := os.WriteFile(large, []byte(strings.Repeat("x", 4097)), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := readSecret(large); err == nil {
		t.Fatal("oversized secret accepted")
	}
	control := filepath.Join(d, "control")
	if err := os.WriteFile(control, []byte("valid-prefix\nsecond-line"), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := readSecret(control); err == nil {
		t.Fatal("embedded control accepted")
	}
	fifo := filepath.Join(d, "fifo")
	if err := syscall.Mkfifo(fifo, 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := readSecret(fifo); err == nil {
		t.Fatal("non-regular secret accepted")
	}
}
