// File: internal/drivers/drivers.go
// Purpose: Define collector contracts and run periodic polling loops.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package drivers

import (
	"context"
	"log/slog"
	"time"

	"github.com/tseiman/HomeAuthMonitorGW/internal/cache"
	"github.com/tseiman/HomeAuthMonitorGW/internal/metrics"
)

// Collector retrieves the current metrics for one source.
type Collector interface {
	// Poll returns current metrics or an error describing why no new sample is available.
	Poll(context.Context) ([]metrics.Metric, error)
}

// Discoverer enumerates metric definitions independently of regular polling.
type Discoverer interface {
	// Discover returns available definitions or an error when discovery cannot complete.
	Discover(context.Context) ([]metrics.Definition, error)
}

// Run polls collector immediately and then at interval until ctx is canceled, updating store and logging every outcome when logger is provided.
func Run(ctx context.Context, name string, interval time.Duration, collector Collector, store *cache.Store, logger *slog.Logger) {
	poll := func() {
		if logger != nil {
			logger.Debug("collector poll started", "source", name)
		}
		start := time.Now()
		values, err := collector.Poll(ctx)
		duration := time.Since(start)
		if err != nil {
			// A failed poll changes availability but leaves the cached last-known-good metrics intact.
			store.Failure(name, err, duration)
			if logger != nil {
				logger.Error("collector poll failed", "source", name, "duration", duration, "error", err)
			}
		} else {
			store.Success(name, values, duration)
			if logger != nil {
				logger.Info("collector poll succeeded", "source", name, "metrics", len(values), "duration", duration)
				logger.Debug("collector poll values", "source", name, "values", values)
			}
		}
	}
	poll()
	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			poll()
		}
	}
}
