// File: internal/tlsreload/tlsreload.go
// Purpose: Load, validate, and atomically publish TLS certificates.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package tlsreload

import (
	"crypto/tls"
	"crypto/x509"
	"errors"
	"fmt"
	"sync/atomic"
	"time"
)

// Manager provides lock-free access to a validated active TLS certificate.
type Manager struct {
	current atomic.Pointer[tls.Certificate]
}

// New loads the certificate and key files, publishes the validated pair, and returns a Manager or the load error.
func New(certFile, keyFile string) (*Manager, error) {
	c, err := Load(certFile, keyFile)
	if err != nil {
		return nil, err
	}
	m := &Manager{}
	m.Activate(c)
	return m, nil
}

// Load reads and parses the certificate and private key files, returning a pair with its leaf populated or a contextual validation error.
func Load(certFile, keyFile string) (*tls.Certificate, error) {
	pair, err := tls.LoadX509KeyPair(certFile, keyFile)
	if err != nil {
		return nil, fmt.Errorf("load TLS keypair: %w", err)
	}
	if len(pair.Certificate) == 0 {
		return nil, errors.New("TLS certificate chain is empty")
	}
	leaf, err := x509.ParseCertificate(pair.Certificate[0])
	if err != nil {
		return nil, fmt.Errorf("parse TLS leaf: %w", err)
	}
	pair.Leaf = leaf
	return &pair, nil
}

// Activate atomically publishes c for subsequent TLS handshakes; callers must provide a fully initialized immutable certificate.
func (m *Manager) Activate(c *tls.Certificate) {
	// Publishing a new immutable certificate pointer prevents handshakes from observing partial state.
	m.current.Store(c)
}

// Reload fully loads and validates the files before atomically replacing the active certificate, returning errors without changing the prior certificate.
func (m *Manager) Reload(certFile, keyFile string) error {
	// Validate a complete immutable pair before atomically replacing the last-known-good certificate.
	c, err := Load(certFile, keyFile)
	if err != nil {
		return err
	}
	m.Activate(c)
	return nil
}

// GetCertificate ignores ClientHello details and returns the currently published certificate, or an error when none is active.
func (m *Manager) GetCertificate(*tls.ClientHelloInfo) (*tls.Certificate, error) {
	c := m.current.Load()
	if c == nil {
		return nil, errors.New("no TLS certificate loaded")
	}
	return c, nil
}

// NotAfter returns the active leaf certificate expiry, or the zero time when no parsed leaf is available.
func (m *Manager) NotAfter() time.Time {
	c := m.current.Load()
	if c == nil || c.Leaf == nil {
		return time.Time{}
	}
	return c.Leaf.NotAfter
}
