// File: internal/metrics/metrics.go
// Purpose: Define protocol-independent metric and discovery data models.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package metrics

import "time"

// Metric is one timestamped, protocol-independent observed value.
type Metric struct {
	Name        string            `json:"name"`
	Value       any               `json:"value"`
	ValueType   string            `json:"value_type"`
	Unit        string            `json:"unit,omitempty"`
	Description string            `json:"description,omitempty"`
	Timestamp   time.Time         `json:"timestamp"`
	Labels      map[string]string `json:"labels,omitempty"`
}

// Definition describes a discoverable metric and optional enum metadata.
type Definition struct {
	OID         string            `json:"oid"`
	Name        string            `json:"name,omitempty"`
	Type        string            `json:"type,omitempty"`
	Unit        string            `json:"unit,omitempty"`
	Description string            `json:"description,omitempty"`
	Enum        map[string]string `json:"enum,omitempty"`
}
