// File: internal/cache/cache.go
// Purpose: Maintain concurrency-safe collector snapshots and stale-state tracking.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package cache

import (
	"sort"
	"sync"
	"time"

	"github.com/tseiman/HomeAuthMonitorGW/internal/metrics"
)

// Snapshot describes the latest state and retained data for one collector source.
type Snapshot struct {
	Name             string               `json:"name"`
	Driver           string               `json:"driver"`
	Available        bool                 `json:"available"`
	Stale            bool                 `json:"stale"`
	LastAttempt      time.Time            `json:"last_attempt,omitempty"`
	LastSuccess      time.Time            `json:"last_success,omitempty"`
	UnavailableSince time.Time            `json:"unavailable_since"`
	PollDuration     time.Duration        `json:"poll_duration_ns"`
	Error            string               `json:"error,omitempty"`
	Metrics          []metrics.Metric     `json:"metrics"`
	Discovery        []metrics.Definition `json:"discovery,omitempty"`
}

type entry struct {
	snapshot   Snapshot
	staleAfter time.Duration
}

// Store provides concurrency-safe registration and snapshot state for collector sources.
type Store struct {
	mu  sync.RWMutex
	now func() time.Time
	m   map[string]*entry
}

// New creates an empty Store using now as its clock, or time.Now when now is nil.
func New(now func() time.Time) *Store {
	if now == nil {
		now = time.Now
	}
	return &Store{now: now, m: make(map[string]*entry)}
}

// Register replaces name with an initially stale source entry for driver and the supplied staleAfter threshold.
func (s *Store) Register(name, driver string, staleAfter time.Duration) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.m[name] = &entry{snapshot: Snapshot{Name: name, Driver: driver, Stale: true, Metrics: []metrics.Metric{}}, staleAfter: staleAfter}
}

// Restore replaces an already registered source with a detached compatible snapshot and reports whether it was accepted.
func (s *Store) Restore(name string, snapshot Snapshot) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	entry, ok := s.m[name]
	if !ok || entry.snapshot.Driver != snapshot.Driver || snapshot.Name != name {
		return false
	}
	entry.snapshot = cloneSnapshot(snapshot)
	return true
}

// Reset removes every registered source and cached snapshot from the store.
func (s *Store) Reset() {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.m = make(map[string]*entry)
}

// Success records a completed poll for name, copies values into the last-known-good snapshot, and ignores unknown names.
func (s *Store) Success(name string, values []metrics.Metric, duration time.Duration) {
	s.mu.Lock()
	defer s.mu.Unlock()
	e, ok := s.m[name]
	if !ok {
		return
	}
	now := s.now().UTC()
	// A successful poll replaces the last-known-good values and clears stale state.
	e.snapshot.Available, e.snapshot.Stale, e.snapshot.Error = true, false, ""
	e.snapshot.UnavailableSince = time.Time{}
	e.snapshot.LastAttempt, e.snapshot.LastSuccess, e.snapshot.PollDuration = now, now, duration
	e.snapshot.Metrics = cloneMetrics(values)
}

// Failure marks name unavailable and stale with a sanitized error while retaining prior metrics; duration is recorded and unknown names are ignored.
func (s *Store) Failure(name string, _ error, duration time.Duration) {
	s.mu.Lock()
	defer s.mu.Unlock()
	e, ok := s.m[name]
	if !ok {
		return
	}
	// Preserve the last-known-good metrics while exposing only a sanitized failure state.
	now := s.now().UTC()
	if e.snapshot.UnavailableSince.IsZero() {
		e.snapshot.UnavailableSince = now
	}
	e.snapshot.Available, e.snapshot.Stale, e.snapshot.Error = false, true, "collector unavailable"
	e.snapshot.LastAttempt, e.snapshot.PollDuration = now, duration
}

// SetDiscovery deep-copies defs into the discovery cache for name and ignores unknown names.
func (s *Store) SetDiscovery(name string, defs []metrics.Definition) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if e, ok := s.m[name]; ok {
		e.snapshot.Discovery = cloneDefinitions(defs)
	}
}

// Snapshot returns an isolated copy for name with age-based staleness applied, plus false when the source is unknown.
func (s *Store) Snapshot(name string) (Snapshot, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	e, ok := s.m[name]
	if !ok {
		return Snapshot{}, false
	}
	v := cloneSnapshot(e.snapshot)
	// Age can make otherwise available cached data stale without mutating stored state.
	if !v.LastSuccess.IsZero() && s.now().Sub(v.LastSuccess) > e.staleAfter {
		v.Stale = true
	}
	return v, true
}

// All returns isolated snapshots for every source in deterministic name order.
func (s *Store) All() []Snapshot {
	s.mu.RLock()
	names := make([]string, 0, len(s.m))
	for n := range s.m {
		names = append(names, n)
	}
	s.mu.RUnlock()
	sort.Strings(names)
	out := make([]Snapshot, 0, len(names))
	for _, n := range names {
		if v, ok := s.Snapshot(n); ok {
			out = append(out, v)
		}
	}
	return out
}

// cloneSnapshot returns v with metric labels and discovery values detached from cached storage.
func cloneSnapshot(v Snapshot) Snapshot {
	v.Metrics = cloneMetrics(v.Metrics)
	v.Discovery = cloneDefinitions(v.Discovery)
	return v
}

// cloneDefinitions deep-copies definitions and their enum maps so callers cannot mutate cached metadata.
func cloneDefinitions(in []metrics.Definition) []metrics.Definition {
	out := append([]metrics.Definition(nil), in...)
	for i := range out {
		if in[i].Enum == nil {
			continue
		}
		out[i].Enum = make(map[string]string, len(in[i].Enum))
		for key, value := range in[i].Enum {
			out[i].Enum[key] = value
		}
	}
	return out
}

// cloneMetrics deep-copies in and its label maps, returning a nil slice when in is nil.
func cloneMetrics(in []metrics.Metric) []metrics.Metric {
	out := append([]metrics.Metric(nil), in...)
	for i := range out {
		if out[i].Labels != nil {
			out[i].Labels = make(map[string]string, len(out[i].Labels))
			for k, v := range in[i].Labels {
				out[i].Labels[k] = v
			}
		}
	}
	return out
}
