// File: internal/cache/cache_test.go
// Purpose: Verify snapshot retention, staleness, sanitization, and copy isolation.
// Generated by: aiAgentTseiman (Hermes Agent)
// Generated on: 2026-10-04

package cache

import (
	"encoding/json"
	"errors"
	"testing"
	"time"

	"github.com/tseiman/HomeAuthMonitorGW/internal/metrics"
)

// TestStoreKeepsLastKnownGoodAndMarksStaleAfterFailure verifies failure sanitization and retained successful metrics.
func TestStoreKeepsLastKnownGoodAndMarksStaleAfterFailure(t *testing.T) {
	now := time.Date(2026, 1, 2, 3, 4, 5, 0, time.UTC)
	s := New(func() time.Time { return now })
	s.Register("wago", "snmp", time.Minute)
	s.Success("wago", []metrics.Metric{{Name: "uptime", Value: uint64(7), Timestamp: now}}, 20*time.Millisecond)
	now = now.Add(10 * time.Second)
	s.Failure("wago", errors.New("connection details secret"), 3*time.Second)

	got, ok := s.Snapshot("wago")
	if !ok || got.Available || !got.Stale {
		t.Fatalf("snapshot=%+v ok=%v", got, ok)
	}
	if got.Error != "collector unavailable" {
		t.Fatalf("unsanitized error: %q", got.Error)
	}
	if len(got.Metrics) != 1 || got.Metrics[0].Value != uint64(7) {
		t.Fatalf("last-known-good lost: %+v", got.Metrics)
	}
	if got.LastSuccess.IsZero() || got.LastAttempt != now {
		t.Fatalf("times=%+v", got)
	}
}

// TestStoreTracksContinuousUnavailability verifies that repeated failures retain the first
// failure time and that a successful poll clears it for immediate recovery.
func TestStoreTracksContinuousUnavailability(t *testing.T) {
	now := time.Date(2026, 10, 7, 12, 0, 0, 0, time.UTC)
	s := New(func() time.Time { return now })
	s.Register("wago", "snmp", time.Minute)
	s.Failure("wago", errors.New("timeout"), time.Second)

	first, _ := s.Snapshot("wago")
	if first.UnavailableSince != now {
		t.Fatalf("first unavailable_since=%s want=%s", first.UnavailableSince, now)
	}
	encoded, err := json.Marshal(first)
	if err != nil {
		t.Fatal(err)
	}
	var payload map[string]any
	if err := json.Unmarshal(encoded, &payload); err != nil {
		t.Fatal(err)
	}
	if payload["unavailable_since"] != now.Format(time.RFC3339) {
		t.Fatalf("JSON unavailable_since=%v", payload["unavailable_since"])
	}

	now = now.Add(4 * time.Minute)
	s.Failure("wago", errors.New("timeout again"), time.Second)
	continued, _ := s.Snapshot("wago")
	if continued.UnavailableSince != first.UnavailableSince {
		t.Fatalf("continuous failure reset unavailable_since: first=%s current=%s", first.UnavailableSince, continued.UnavailableSince)
	}

	now = now.Add(time.Minute)
	s.Success("wago", []metrics.Metric{{Name: "uptime", Value: uint64(1)}}, time.Millisecond)
	recovered, _ := s.Snapshot("wago")
	if !recovered.Available || !recovered.UnavailableSince.IsZero() {
		t.Fatalf("recovery did not clear unavailable_since: %+v", recovered)
	}
}

// TestSnapshotBecomesStaleByAgeAndIsACopy verifies age-based staleness and isolation from caller mutation.
func TestSnapshotBecomesStaleByAgeAndIsACopy(t *testing.T) {
	now := time.Now().UTC()
	s := New(func() time.Time { return now })
	s.Register("quint", "nut", 5*time.Second)
	s.Success("quint", []metrics.Metric{{Name: "x", Value: "y", Labels: map[string]string{"a": "b"}}}, time.Millisecond)
	now = now.Add(6 * time.Second)
	got, _ := s.Snapshot("quint")
	if !got.Stale || !got.Available {
		t.Fatalf("snapshot=%+v", got)
	}
	got.Metrics[0].Labels["a"] = "changed"
	again, _ := s.Snapshot("quint")
	if again.Metrics[0].Labels["a"] != "b" {
		t.Fatal("snapshot aliases cache")
	}
}

// TestDiscoveryEnumMapsAreCopies verifies both cache insertion and returned snapshots detach mutable enum metadata.
func TestDiscoveryEnumMapsAreCopies(t *testing.T) {
	s := New(time.Now)
	s.Register("wago", "snmp", time.Minute)
	definitions := []metrics.Definition{{OID: "1.2.3", Enum: map[string]string{"1": "on"}}}
	s.SetDiscovery("wago", definitions)
	definitions[0].Enum["1"] = "changed before read"

	first, _ := s.Snapshot("wago")
	if first.Discovery[0].Enum["1"] != "on" {
		t.Fatalf("cache aliases inserted enum: %+v", first.Discovery)
	}
	first.Discovery[0].Enum["1"] = "changed after read"
	second, _ := s.Snapshot("wago")
	if second.Discovery[0].Enum["1"] != "on" {
		t.Fatalf("snapshot aliases cached enum: %+v", second.Discovery)
	}
}

// TestRestoreAcceptsOnlyCompatibleDetachedSnapshots verifies generation handoff and mutation isolation.
func TestRestoreAcceptsOnlyCompatibleDetachedSnapshots(t *testing.T) {
	store := New(time.Now)
	store.Register("same", "nut", time.Minute)
	snapshot := Snapshot{Name: "same", Driver: "nut", Available: true, Metrics: []metrics.Metric{{Name: "charge", Labels: map[string]string{"unit": "percent"}}}}
	if !store.Restore("same", snapshot) {
		t.Fatal("compatible snapshot rejected")
	}
	snapshot.Metrics[0].Labels["unit"] = "changed"
	got, _ := store.Snapshot("same")
	if got.Metrics[0].Labels["unit"] != "percent" {
		t.Fatal("restored snapshot aliases caller data")
	}
	store.Register("changed-driver", "snmp", time.Minute)
	if store.Restore("changed-driver", Snapshot{Name: "changed-driver", Driver: "nut"}) {
		t.Fatal("incompatible driver accepted")
	}
}
